Repository brain-tec/sale-workflow, pull requests merged in 2019-04, with the labels that each got.

#265 Syncing from upstream OCA/sale-workflow (8.0)
  account_invoice_reorder_lines/static/description/icon.png
  sale_automatic_workflow/i18n/de.po
  sale_automatic_workflow_exception/static/description/icon.png
  sale_change_price/static/description/icon.png
  sale_comment_propagation/i18n/es.po
  sale_order_line_date/static/description/icon.png
  sale_order_merge/static/description/icon.png
  sale_order_unified_menu/static/description/icon.png
  sale_order_weight/static/description/icon.png
  sale_partner_incoterm/static/description/icon.png
  sale_payment_method/static/description/icon.png
  sale_payment_method_transaction_id/static/description/icon.png
  sale_pricelist_discount/static/description/icon.png
  sale_product_multi_add/static/description/icon.png
  sale_quick_payment/static/description/icon.png
  sale_validity/i18n/de.po
Labels: 8.0

#266 Syncing from upstream OCA/sale-workflow (9.0)
  sale_automatic_workflow/i18n/es.po
  sale_automatic_workflow_payment_mode/static/description/icon.png
  sale_delivery_block/static/description/icon.png
  sale_delivery_block_proc_group_by_line/static/description/icon.png
  sale_order_line_date/static/description/icon.png
  sale_order_line_sequence/static/description/icon.png
  sale_order_product_recommendation/i18n/es.po
  sale_procurement_group_by_requested_date/static/description/icon.png
  sale_revert_done/static/description/icon.png
Labels: 9.0

#267 Syncing from upstream OCA/sale-workflow (10.0)
  product_price_category/static/description/icon.png
  sale_automatic_workflow_exception/static/description/icon.png
  sale_automatic_workflow_payment_mode/static/description/icon.png
  sale_commercial_partner/static/description/icon.png
  sale_company_currency/static/description/icon.png
  sale_invoice_auto_deliver/static/description/icon.png
  sale_layout_hidden/static/description/icon.png
  sale_mrp_link/static/description/icon.png
  sale_order_line_date/static/description/icon.png
  sale_order_line_sequence/static/description/icon.png
  sale_order_lot_generator/static/description/icon.png
  sale_order_lot_mrp/static/description/icon.png
  sale_order_margin_percent/static/description/icon.png
  sale_order_priority/static/description/icon.png
  sale_partner_incoterm/static/description/icon.png
  sale_product_multi_add/static/description/icon.png
  sale_promotion_rule/static/description/icon.png
  sale_revert_done/static/description/icon.png
  sale_stock_picking_blocking/static/description/icon.png
  sale_stock_picking_blocking_proc_group_by_line/static/description/icon.png
Labels: 10.0

#268 Syncing from upstream OCA/sale-workflow (11.0)
  partner_contact_sale_info_propagation/static/description/icon.png
  sale_automatic_workflow_payment_mode/static/description/icon.png
  sale_order_line_date/static/description/icon.png
  sale_order_line_price_history/static/description/icon.png
  sale_order_line_sequence/static/description/icon.png
  sale_stock_picking_blocking/static/description/icon.png
  sales_team_security/static/description/icon.png
Labels: 11.0

#269 Syncing from upstream OCA/sale-workflow (12.0)
  sale_order_line_sequence/static/description/icon.png
  sale_partner_incoterm/static/description/icon.png
  sale_stock_picking_blocking/static/description/icon.png
Labels: 12.0

#271 Syncing from upstream OCA/sale-workflow (12.0)
  sale_order_general_discount/README.rst
  sale_order_general_discount/__init__.py
  sale_order_general_discount/__manifest__.py
  sale_order_general_discount/i18n/es.po
  sale_order_general_discount/i18n/sale_order_general_discount.pot
  sale_order_general_discount/models/__init__.py
  sale_order_general_discount/models/res_partner.py
  sale_order_general_discount/models/sale.py
  sale_order_general_discount/readme/CONTRIBUTORS.rst
  sale_order_general_discount/readme/DESCRIPTION.rst
  sale_order_general_discount/readme/INSTALL.rst
  sale_order_general_discount/readme/USAGE.rst
  sale_order_general_discount/static/description/icon.png
  sale_order_general_discount/static/description/index.html
  sale_order_general_discount/tests/__init__.py
  sale_order_general_discount/tests/test_sale_order_general_discount.py
  sale_order_general_discount/views/res_partner_view.xml
  sale_order_general_discount/views/sale_order_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_order_general_discount/odoo/addons/sale_order_general_discount
  setup/sale_order_general_discount/setup.py
Labels: 12.0

#272 Syncing from upstream OCA/sale-workflow (11.0)
  sale_order_invoicing_finished_task/tests/test_sale_order_invoicing_finished_task.py
Labels: 11.0

#273 Syncing from upstream OCA/sale-workflow (11.0)
  sale_order_secondary_unit/__manifest__.py
  sale_order_secondary_unit/migrations/11.0.1.0.2/post-migration.py
  sale_order_secondary_unit/views/product_views.xml
  sale_order_secondary_unit/views/sale_order_views.xml
Labels: 11.0

#274 Syncing from upstream OCA/sale-workflow (12.0)
  partner_prospect/README.rst
  partner_prospect/__init__.py
  partner_prospect/__manifest__.py
  partner_prospect/i18n/de.po
  partner_prospect/i18n/es.po
  partner_prospect/i18n/fr.po
  partner_prospect/i18n/partner_prospect.pot
  partner_prospect/i18n/sl.po
  partner_prospect/models/__init__.py
  partner_prospect/models/res_partner.py
  partner_prospect/readme/CONTRIBUTORS.rst
  partner_prospect/readme/DESCRIPTION.rst
  partner_prospect/static/description/icon.png
  partner_prospect/static/description/index.html
  partner_prospect/tests/__init__.py
  partner_prospect/tests/test_partner_prospect.py
  partner_prospect/views/res_partner_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/partner_prospect/odoo/addons/partner_prospect
  setup/partner_prospect/setup.py
Labels: 12.0

#275 [t114208] Added sale_fixed_discount module from v11
  sale_fixed_discount/README.rst
  sale_fixed_discount/__init__.py
  sale_fixed_discount/__manifest__.py
  sale_fixed_discount/i18n/sale_fixed_discount.pot
  sale_fixed_discount/models/__init__.py
  sale_fixed_discount/models/sale_order.py
  sale_fixed_discount/readme/CONFIGURE.rst
  sale_fixed_discount/readme/CONTRIBUTORS.rst
  sale_fixed_discount/readme/DESCRIPTION.rst
  sale_fixed_discount/readme/INSTALL.rst
  sale_fixed_discount/readme/USAGE.rst
  sale_fixed_discount/reports/report_account_invoice.xml
  sale_fixed_discount/reports/report_sale_order.xml
  sale_fixed_discount/static/description/icon.png
  sale_fixed_discount/static/description/index.html
  sale_fixed_discount/tests/__init__.py
  sale_fixed_discount/tests/test_sale_fixed_discount.py
  sale_fixed_discount/views/account_invoice_views.xml
  sale_fixed_discount/views/sale_order_views.xml
Labels: 12.0.project_mi_465

#276 Syncing from upstream OCA/sale-workflow (12.0)
  sale_order_action_invoice_create_hook/README.rst
  sale_order_action_invoice_create_hook/__init__.py
  sale_order_action_invoice_create_hook/__manifest__.py
  sale_order_action_invoice_create_hook/i18n/ca_ES.po
  sale_order_action_invoice_create_hook/i18n/de.po
  sale_order_action_invoice_create_hook/i18n/el_GR.po
  sale_order_action_invoice_create_hook/i18n/es.po
  sale_order_action_invoice_create_hook/i18n/es_VE.po
  sale_order_action_invoice_create_hook/i18n/fi.po
  sale_order_action_invoice_create_hook/i18n/fr.po
  sale_order_action_invoice_create_hook/i18n/hr.po
  sale_order_action_invoice_create_hook/i18n/hu.po
  sale_order_action_invoice_create_hook/i18n/it.po
  sale_order_action_invoice_create_hook/i18n/nl.po
  sale_order_action_invoice_create_hook/i18n/pt_BR.po
  sale_order_action_invoice_create_hook/i18n/ro.po
  sale_order_action_invoice_create_hook/i18n/sale_order_action_invoice_create_hook.pot
  sale_order_action_invoice_create_hook/i18n/sl_SI.po
  sale_order_action_invoice_create_hook/i18n/tr.po
  sale_order_action_invoice_create_hook/i18n/vi_VN.po
  sale_order_action_invoice_create_hook/i18n/zh_CN.po
  sale_order_action_invoice_create_hook/model/__init__.py
  sale_order_action_invoice_create_hook/model/sale_order.py
  sale_order_action_invoice_create_hook/readme/CONTRIBUTORS.rst
  sale_order_action_invoice_create_hook/readme/DESCRIPTION.rst
  sale_order_action_invoice_create_hook/readme/USAGE.rst
  sale_order_action_invoice_create_hook/static/description/icon.png
  sale_order_action_invoice_create_hook/static/description/index.html
  sale_order_action_invoice_create_hook/tests/__init__.py
  sale_order_action_invoice_create_hook/tests/test_sale_order_action_create_hook.py
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_order_action_invoice_create_hook/odoo/addons/sale_order_action_invoice_create_hook
  setup/sale_order_action_invoice_create_hook/setup.py
Labels: 12.0
