Repository brain-tec/sale-workflow, pull requests merged in 2019-05, with the labels that each got.

#277 Syncing from upstream OCA/sale-workflow (11.0)
  sale_fixed_discount/i18n/sale_fixed_discount.pot
  sale_fixed_discount/models/sale_order.py
  sale_order_price_recalculation/models/sale_order.py
  sale_order_price_recalculation/tests/test_sale_order_price_recalculation.py
Labels: 11.0

#278 Syncing from upstream OCA/sale-workflow (12.0)
  sale_order_revision/README.rst
  sale_order_revision/__init__.py
  sale_order_revision/__manifest__.py
  sale_order_revision/i18n/ca.po
  sale_order_revision/i18n/de.po
  sale_order_revision/i18n/el_GR.po
  sale_order_revision/i18n/es.po
  sale_order_revision/i18n/es_ES.po
  sale_order_revision/i18n/es_VE.po
  sale_order_revision/i18n/fi.po
  sale_order_revision/i18n/fr.po
  sale_order_revision/i18n/hr.po
  sale_order_revision/i18n/hr_HR.po
  sale_order_revision/i18n/hu.po
  sale_order_revision/i18n/it.po
  sale_order_revision/i18n/nl.po
  sale_order_revision/i18n/nl_NL.po
  sale_order_revision/i18n/pt.po
  sale_order_revision/i18n/pt_BR.po
  sale_order_revision/i18n/ro.po
  sale_order_revision/i18n/sale_order_revision.pot
  sale_order_revision/i18n/sk.po
  sale_order_revision/i18n/sl.po
  sale_order_revision/i18n/tr.po
  sale_order_revision/i18n/tr_TR.po
  sale_order_revision/i18n/vi_VN.po
  sale_order_revision/i18n/zh_CN.po
  sale_order_revision/models/__init__.py
  sale_order_revision/models/sale_order.py
  sale_order_revision/readme/CONTRIBUTORS.rst
  sale_order_revision/readme/DESCRIPTION.rst
  sale_order_revision/readme/INSTALL.rst
  sale_order_revision/static/description/icon.png
  sale_order_revision/static/description/index.html
  sale_order_revision/tests/__init__.py
  sale_order_revision/tests/test_sale_order_revision.py
  sale_order_revision/view/sale_order.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_order_revision/odoo/addons/sale_order_revision
  setup/sale_order_revision/setup.py
Labels: 12.0

#279 Syncing from upstream OCA/sale-workflow (12.0)
  sale_order_line_price_history/README.rst
  sale_order_line_price_history/__init__.py
  sale_order_line_price_history/__manifest__.py
  sale_order_line_price_history/i18n/es.po
  sale_order_line_price_history/i18n/sale_order_line_price_history.pot
  sale_order_line_price_history/readme/CONTRIBUTORS.rst
  sale_order_line_price_history/readme/DESCRIPTION.rst
  sale_order_line_price_history/readme/ROADMAP.rst
  sale_order_line_price_history/readme/USAGE.rst
  sale_order_line_price_history/static/description/icon.png
  sale_order_line_price_history/static/description/index.html
  sale_order_line_price_history/tests/__init__.py
  sale_order_line_price_history/tests/test_sale_order_line_price_history.py
  sale_order_line_price_history/views/sale_views.xml
  sale_order_line_price_history/wizards/__init__.py
  sale_order_line_price_history/wizards/sale_order_line_price_history.py
  sale_order_line_price_history/wizards/sale_order_line_price_history.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_order_line_price_history/odoo/addons/sale_order_line_price_history
  setup/sale_order_line_price_history/setup.py
Labels: 12.0

#280 Syncing from upstream OCA/sale-workflow (11.0)
  sale_order_secondary_unit/__manifest__.py
  sale_order_secondary_unit/i18n/es.po
  sale_order_secondary_unit/i18n/sale_order_secondary_unit.pot
  sale_order_secondary_unit/report/sale_report_templates.xml
Labels: 11.0

#283 Syncing from upstream OCA/sale-workflow (12.0)
  sale_order_price_recalculation/README.rst
  sale_order_price_recalculation/__init__.py
  sale_order_price_recalculation/__manifest__.py
  sale_order_price_recalculation/i18n/ca.po
  sale_order_price_recalculation/i18n/de.po
  sale_order_price_recalculation/i18n/el_GR.po
  sale_order_price_recalculation/i18n/en.po
  sale_order_price_recalculation/i18n/es.po
  sale_order_price_recalculation/i18n/es_ES.po
  sale_order_price_recalculation/i18n/es_VE.po
  sale_order_price_recalculation/i18n/fi.po
  sale_order_price_recalculation/i18n/fr.po
  sale_order_price_recalculation/i18n/hr.po
  sale_order_price_recalculation/i18n/hr_HR.po
  sale_order_price_recalculation/i18n/hu.po
  sale_order_price_recalculation/i18n/it.po
  sale_order_price_recalculation/i18n/nl.po
  sale_order_price_recalculation/i18n/nl_NL.po
  sale_order_price_recalculation/i18n/pt.po
  sale_order_price_recalculation/i18n/pt_BR.po
  sale_order_price_recalculation/i18n/ro.po
  sale_order_price_recalculation/i18n/sale_order_price_recalculation.pot
  sale_order_price_recalculation/i18n/sl.po
  sale_order_price_recalculation/i18n/tr.po
  sale_order_price_recalculation/i18n/tr_TR.po
  sale_order_price_recalculation/i18n/vi_VN.po
  sale_order_price_recalculation/i18n/zh_CN.po
  sale_order_price_recalculation/models/__init__.py
  sale_order_price_recalculation/models/sale_order.py
  sale_order_price_recalculation/readme/CONTRIBUTORS.rst
  sale_order_price_recalculation/readme/DESCRIPTION.rst
  sale_order_price_recalculation/readme/INSTALL.rst
  sale_order_price_recalculation/readme/ROADMAP.rst
  sale_order_price_recalculation/readme/USAGE.rst
  sale_order_price_recalculation/static/description/icon.png
  sale_order_price_recalculation/static/description/index.html
  sale_order_price_recalculation/static/description/sale_order_price_recalculation.png
  sale_order_price_recalculation/tests/__init__.py
  sale_order_price_recalculation/tests/test_sale_order_price_recalculation.py
  sale_order_price_recalculation/views/sale_order_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_order_price_recalculation/odoo/addons/sale_order_price_recalculation
  setup/sale_order_price_recalculation/setup.py
Labels: 12.0

#285 Syncing from upstream OCA/sale-workflow (11.0)
  sale_order_price_recalculation/models/sale_order.py
Labels: 11.0

#286 Syncing from upstream OCA/sale-workflow (12.0)
  sale_order_price_recalculation/models/sale_order.py
Labels: 12.0

#287 Syncing from upstream OCA/sale-workflow (11.0)
  sale_elaboration/i18n/es.po
Labels: 11.0

#284 [t114535] Fixed discounts don't break discounts set by price lists.
  sale_fixed_discount/models/sale_order.py
Labels: 12.0.project_mi_465

#289 Syncing from upstream OCA/sale-workflow (11.0)
  product_supplierinfo_for_customer_sale/models/product_product.py
Labels: 11.0
