Repository brain-tec/sale-workflow, pull requests merged in 2019-08, with the labels that each got.

#323 Syncing from upstream OCA/sale-workflow (10.0)
  product_special_type/__init__.py
Labels: 10.0

#324 Syncing from upstream OCA/sale-workflow (12.0)
  oca_dependencies.txt
  sale_order_digitized_signature/README.rst
  sale_order_digitized_signature/__init__.py
  sale_order_digitized_signature/__manifest__.py
  sale_order_digitized_signature/i18n/es.po
  sale_order_digitized_signature/i18n/sale_order_digitized_signature.pot
  sale_order_digitized_signature/migrations/12.0.1.0.0/post-migration.py
  sale_order_digitized_signature/migrations/12.0.1.0.0/pre-migration.py
  sale_order_digitized_signature/models/__init__.py
  sale_order_digitized_signature/models/sale.py
  sale_order_digitized_signature/readme/CONTRIBUTORS.rst
  sale_order_digitized_signature/readme/DESCRIPTION.rst
  sale_order_digitized_signature/readme/INSTALL.rst
  sale_order_digitized_signature/readme/USAGE.rst
  sale_order_digitized_signature/report/report_saleorder.xml
  sale_order_digitized_signature/static/description/icon.png
  sale_order_digitized_signature/static/description/index.html
  sale_order_digitized_signature/views/sale_views.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_order_digitized_signature/odoo/addons/sale_order_digitized_signature
  setup/sale_order_digitized_signature/setup.py
Labels: 12.0

#325 Updating project branch from 12.0
  oca_dependencies.txt
  sale_order_digitized_signature/README.rst
  sale_order_digitized_signature/__init__.py
  sale_order_digitized_signature/__manifest__.py
  sale_order_digitized_signature/i18n/es.po
  sale_order_digitized_signature/i18n/sale_order_digitized_signature.pot
  sale_order_digitized_signature/migrations/12.0.1.0.0/post-migration.py
  sale_order_digitized_signature/migrations/12.0.1.0.0/pre-migration.py
  sale_order_digitized_signature/models/__init__.py
  sale_order_digitized_signature/models/sale.py
  sale_order_digitized_signature/readme/CONTRIBUTORS.rst
  sale_order_digitized_signature/readme/DESCRIPTION.rst
  sale_order_digitized_signature/readme/INSTALL.rst
  sale_order_digitized_signature/readme/USAGE.rst
  sale_order_digitized_signature/report/report_saleorder.xml
  sale_order_digitized_signature/static/description/icon.png
  sale_order_digitized_signature/static/description/index.html
  sale_order_digitized_signature/views/sale_views.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_order_digitized_signature/odoo/addons/sale_order_digitized_signature
  setup/sale_order_digitized_signature/setup.py
Labels: 12.0.project_mi_465

#326 Syncing from upstream OCA/sale-workflow (12.0)
  oca_dependencies.txt
  sale_brand/README.rst
  sale_brand/__init__.py
  sale_brand/__manifest__.py
  sale_brand/i18n/sale_brand.pot
  sale_brand/models/__init__.py
  sale_brand/models/sale_order.py
  sale_brand/readme/CONFIGURE.rst
  sale_brand/readme/CONTRIBUTORS.rst
  sale_brand/readme/CREDITS.rst
  sale_brand/readme/DESCRIPTION.rst
  sale_brand/readme/USAGE.rst
  sale_brand/static/description/icon.png
  sale_brand/static/description/index.html
  sale_brand/views/sale_views.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_brand/odoo/addons/sale_brand
  setup/sale_brand/setup.py
Labels: 12.0

#327 [MIG] Migrate sale_order_secondary_unit and sale_stock_secondary_unit submodules.
  sale_order_secondary_unit/README.rst
  sale_order_secondary_unit/__init__.py
  sale_order_secondary_unit/__manifest__.py
  sale_order_secondary_unit/i18n/de.po
  sale_order_secondary_unit/i18n/es.po
  sale_order_secondary_unit/i18n/sale_order_secondary_unit.pot
  sale_order_secondary_unit/migrations/11.0.1.0.2/post-migration.py
  sale_order_secondary_unit/models/__init__.py
  sale_order_secondary_unit/models/product_template.py
  sale_order_secondary_unit/models/sale_order.py
  sale_order_secondary_unit/readme/CONTRIBUTORS.rst
  sale_order_secondary_unit/readme/DESCRIPTION.rst
  sale_order_secondary_unit/readme/USAGE.rst
  sale_order_secondary_unit/report/sale_report_templates.xml
  sale_order_secondary_unit/static/description/icon.png
  sale_order_secondary_unit/static/description/index.html
  sale_order_secondary_unit/tests/__init__.py
  sale_order_secondary_unit/tests/test_sale_order_secondary_unit.py
  sale_order_secondary_unit/views/product_views.xml
  sale_order_secondary_unit/views/sale_order_views.xml
  sale_stock_secondary_unit/README.rst
  sale_stock_secondary_unit/__init__.py
  sale_stock_secondary_unit/__manifest__.py
  sale_stock_secondary_unit/i18n/de.po
  sale_stock_secondary_unit/i18n/sale_stock_secondary_unit.pot
  sale_stock_secondary_unit/models/__init__.py
  sale_stock_secondary_unit/models/procurement_rule.py
  sale_stock_secondary_unit/readme/CONTRIBUTORS.rst
  sale_stock_secondary_unit/readme/DESCRIPTION.rst
  sale_stock_secondary_unit/readme/USAGE.rst
  sale_stock_secondary_unit/static/description/icon.png
  sale_stock_secondary_unit/static/description/index.html
  sale_stock_secondary_unit/tests/__init__.py
  sale_stock_secondary_unit/tests/test_sale_stock_secondary_unit.py
Labels: #Migration, 12.0.project_gv_545

#328 Syncing from upstream OCA/sale-workflow (9.0)
  .travis.yml
  README.md
  sale_automatic_workflow/__openerp__.py
  sale_automatic_workflow/models/sale_workflow_process.py
  sale_automatic_workflow/views/sale_workflow_process_view.xml
  sale_cancel_reason/i18n/sale_cancel_reason.pot
  sale_order_type/i18n/sale_order_type.pot
Labels: 9.0

#329 Syncing from upstream OCA/sale-workflow (11.0)
  .travis.yml
  sale_order_type/i18n/sale_order_type.pot
Labels: 11.0

#330 Syncing from upstream OCA/sale-workflow (11.0)
  sale_order_product_recommendation/__manifest__.py
  sale_order_product_recommendation/wizards/sale_order_recommendation.py
Labels: 11.0

#331 Updating project branch from 12.0
  oca_dependencies.txt
  sale_brand/README.rst
  sale_brand/__init__.py
  sale_brand/__manifest__.py
  sale_brand/i18n/sale_brand.pot
  sale_brand/models/__init__.py
  sale_brand/models/sale_order.py
  sale_brand/readme/CONFIGURE.rst
  sale_brand/readme/CONTRIBUTORS.rst
  sale_brand/readme/CREDITS.rst
  sale_brand/readme/DESCRIPTION.rst
  sale_brand/readme/USAGE.rst
  sale_brand/static/description/icon.png
  sale_brand/static/description/index.html
  sale_brand/views/sale_views.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_brand/odoo/addons/sale_brand
  setup/sale_brand/setup.py
Labels: 12.0.project_mi_465

#333 Syncing from upstream OCA/sale-workflow (10.0)
  .travis.yml
Labels: 10.0

#334 Syncing from upstream OCA/sale-workflow (11.0)
  sale_exception/views/sale_view.xml
Labels: 11.0
