Repository brain-tec/sale-workflow, pull requests merged in 2020-11, with the labels that each got.

#607 Syncing from upstream OCA/sale-workflow (13.0)
  .pre-commit-config.yaml
  .pylintrc
  .pylintrc-mandatory
Labels: 13.0

#609 Syncing from upstream OCA/sale-workflow (12.0)
  sale_product_multi_add/i18n/es.po
Labels: 12.0

#610 Syncing from upstream OCA/sale-workflow (13.0)
  sale_invoice_plan/__manifest__.py
  sale_order_product_recommendation/__manifest__.py
  sale_order_product_recommendation/wizards/sale_order_recommendation.py
Labels: 13.0

#611 Syncing from upstream OCA/sale-workflow (12.0)
  sale_order_price_recalculation/i18n/fr.po
Labels: 12.0

#612 Syncing from upstream OCA/sale-workflow (13.0)
  .pre-commit-config.yaml
  sale_order_line_date/i18n/nl_NL.po
Labels: 13.0

#614 Syncing from upstream OCA/sale-workflow (12.0)
  sale_automatic_workflow/i18n/pt_BR.po
  sale_automatic_workflow_payment_mode/i18n/pt_BR.po
Labels: 12.0

#615 Syncing from upstream OCA/sale-workflow (13.0)
  sale_automatic_workflow/i18n/ca.po
  sale_discount_display_amount/i18n/ca.po
  sale_force_invoiced/i18n/ca.po
  sale_order_product_availability_inline/i18n/ca.po
  sale_order_type/i18n/ca.po
  sale_product_category_menu/i18n/ca.po
  sale_product_multi_add/i18n/ca.po
  sale_stock_delivery_address/i18n/ca.po
Labels: 13.0

#616 Syncing from upstream OCA/sale-workflow (12.0)
  sale_automatic_workflow/i18n/pt_BR.po
Labels: 12.0

#618 Automatically formatting the code according to pre-commit
  .braintec/deploy.yaml
  sale_order_product_recommendation/wizards/sale_order_recommendation.py
Labels: 13.0.project_mi_465

#619 Removing unneeded ext folder
  ext/.gitignore
Labels: 13.0.project_mi_465

#620 Syncing from upstream OCA/sale-workflow (12.0)
  .travis.yml
  sale_invoice_plan/__manifest__.py
  sale_order_incoterm_place/i18n/ja.po
Labels: 12.0

#621 Syncing from upstream OCA/sale-workflow (13.0)
  sale_order_type/__manifest__.py
  sale_order_type/models/sale.py
  sale_stock_picking_note/README.rst
  sale_stock_picking_note/__init__.py
  sale_stock_picking_note/__manifest__.py
  sale_stock_picking_note/i18n/ca.po
  sale_stock_picking_note/i18n/es.po
  sale_stock_picking_note/i18n/sale_stock_picking_note.pot
  sale_stock_picking_note/models/__init__.py
  sale_stock_picking_note/models/sale_stock.py
  sale_stock_picking_note/readme/CONTRIBUTORS.rst
  sale_stock_picking_note/readme/DESCRIPTION.rst
  sale_stock_picking_note/readme/USAGE.rst
  sale_stock_picking_note/static/description/icon.png
  sale_stock_picking_note/static/description/index.html
  sale_stock_picking_note/tests/__init__.py
  sale_stock_picking_note/tests/test_sale_stock_picking_note.py
  sale_stock_picking_note/views/sale_order_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_stock_picking_note/odoo/addons/sale_stock_picking_note
  setup/sale_stock_picking_note/setup.py
Labels: 13.0

#622 Syncing from upstream OCA/sale-workflow (13.0)
  sale_product_set/__manifest__.py
  sale_product_set/models/product_set.py
  sale_stock_picking_note/i18n/ca.po
  sale_stock_picking_note/i18n/es.po
Labels: 13.0

#623 Syncing from upstream OCA/sale-workflow (12.0)
  sale_stock_return_request/i18n/fr.po
Labels: 12.0

#624 Syncing from upstream OCA/sale-workflow (13.0)
  sale_order_warn_message/README.rst
  sale_order_warn_message/__init__.py
  sale_order_warn_message/__manifest__.py
  sale_order_warn_message/i18n/sale_order_warn_message.pot
  sale_order_warn_message/models/__init__.py
  sale_order_warn_message/models/sale_order.py
  sale_order_warn_message/readme/CONTRIBUTORS.rst
  sale_order_warn_message/readme/DESCRIPTION.rst
  sale_order_warn_message/static/description/icon.png
  sale_order_warn_message/static/description/index.html
  sale_order_warn_message/tests/__init__.py
  sale_order_warn_message/tests/test_sale_order_warn_message.py
  sale_order_warn_message/views/sale_order.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_order_warn_message/odoo/addons/sale_order_warn_message
  setup/sale_order_warn_message/setup.py
Labels: 13.0

#625 Syncing from upstream OCA/sale-workflow (12.0)
  sale_commercial_partner/__manifest__.py
  sale_commercial_partner/models/sale.py
Labels: 12.0

#626 Syncing from upstream OCA/sale-workflow (13.0)
  sale_order_type/__manifest__.py
  sale_order_type/models/sale.py
  sale_order_warn_message/__manifest__.py
Labels: 13.0

#627 Syncing from upstream OCA/sale-workflow (13.0)
  sale_automatic_workflow/__manifest__.py
  sale_automatic_workflow/models/automatic_workflow_job.py
Labels: 13.0

#628 Syncing from upstream OCA/sale-workflow (12.0)
  sale_order_product_recommendation/__manifest__.py
  sale_order_product_recommendation/wizards/sale_order_recommendation_view.xml
Labels: 12.0

#629 Syncing from upstream OCA/sale-workflow (13.0)
  sale_order_product_recommendation/__manifest__.py
  sale_order_product_recommendation/wizards/sale_order_recommendation_view.xml
Labels: 13.0

#630 Syncing from upstream OCA/sale-workflow (12.0)
  sale_order_line_sequence/i18n/it.po
Labels: 12.0

#631 Syncing from upstream OCA/sale-workflow (13.0)
  sale_partner_incoterm/__manifest__.py
  sale_partner_incoterm/tests/test_sale_partner_incoterm.py
Labels: 13.0

#632 Syncing from upstream OCA/sale-workflow (13.0)
  sale_by_packaging/__manifest__.py
  sale_by_packaging/models/product_template.py
Labels: 13.0

#633 Syncing from upstream OCA/sale-workflow (13.0)
  sale_stock_delivery_address/README.rst
  sale_stock_delivery_address/__manifest__.py
  sale_stock_delivery_address/static/description/index.html
  sale_stock_delivery_address/views/sale_order_view.xml
Labels: 13.0

#634 Syncing from upstream OCA/sale-workflow (13.0)
  sales_team_security/i18n/it.po
Labels: 13.0

#635 Syncing from upstream OCA/sale-workflow (12.0)
  sale_order_product_recommendation/i18n/pt_BR.po
Labels: 12.0

#636 Syncing from upstream OCA/sale-workflow (10.0)
  sale_exception/i18n/ca.po
  sale_exception/i18n/de.po
  sale_exception/i18n/el_GR.po
  sale_exception/i18n/es.po
  sale_exception/i18n/es_ES.po
  sale_exception/i18n/es_VE.po
  sale_exception/i18n/fi.po
  sale_exception/i18n/fr.po
  sale_exception/i18n/hr.po
  sale_exception/i18n/hr_HR.po
  sale_exception/i18n/hu.po
  sale_exception/i18n/it.po
  sale_exception/i18n/nl.po
  sale_exception/i18n/nl_NL.po
  sale_exception/i18n/pt.po
  sale_exception/i18n/pt_BR.po
  sale_exception/i18n/ro.po
  sale_exception/i18n/sk.po
  sale_exception/i18n/sl.po
  sale_exception/i18n/tr.po
  sale_exception/i18n/tr_TR.po
  sale_exception/i18n/vi_VN.po
  sale_exception/i18n/zh_CN.po
  sale_force_invoiced/i18n/de.po
  sale_force_invoiced/i18n/pt.po
Labels: 10.0

#637 Syncing from upstream OCA/sale-workflow (11.0)
  sale_isolated_quotation/i18n/hr.po
  sale_isolated_quotation/i18n/pt.po
  sale_order_product_recommendation_secondary_unit/i18n/es.po
Labels: 11.0

#639 Syncing from upstream OCA/sale-workflow (13.0)
  sale_discount_display_amount/i18n/de.po
  sale_discount_display_amount/i18n/fr.po
  sale_discount_display_amount/i18n/zh_CN.po
  sale_invoice_plan/i18n/fr.po
  sale_invoice_plan/i18n/nl_NL.po
  sale_invoice_plan/i18n/zh_CN.po
  sale_order_archive/i18n/de.po
  sale_order_archive/i18n/zh_CN.po
  sale_order_general_discount/i18n/de.po
  sale_order_general_discount/i18n/it.po
  sale_order_general_discount/i18n/zh_CN.po
  sale_stock_picking_note/i18n/ca.po
Labels: 13.0

#641 Syncing from upstream OCA/sale-workflow (12.0)
  sale_mrp_link/i18n/es.po
Labels: 12.0

#642 Syncing from upstream OCA/sale-workflow (10.0)
  README.md
  sale_cancel_reason/__manifest__.py
  sale_cancel_reason/security/ir.model.access.csv
Labels: 10.0

#643 Syncing from upstream OCA/sale-workflow (11.0)
  sale_stock_delivery_address/__manifest__.py
  sale_stock_delivery_address/models/sale_order_line.py
Labels: 11.0

#644 Syncing from upstream OCA/sale-workflow (12.0)
  product_form_sale_link/i18n/fr.po
  sale_force_invoiced/i18n/fr.po
  sale_order_type/i18n/fr.po
Labels: 12.0

#646 Syncing from upstream OCA/sale-workflow (13.0)
  sale_order_type/__manifest__.py
  sale_order_type/models/sale.py
Labels: 13.0

#647 Syncing from upstream OCA/sale-workflow (13.0)
  sale_isolated_quotation/README.rst
  sale_isolated_quotation/__init__.py
  sale_isolated_quotation/__manifest__.py
  sale_isolated_quotation/data/ir_sequence_data.xml
  sale_isolated_quotation/hooks.py
  sale_isolated_quotation/i18n/ca.po
  sale_isolated_quotation/i18n/de.po
  sale_isolated_quotation/i18n/el_GR.po
  sale_isolated_quotation/i18n/es.po
  sale_isolated_quotation/i18n/es_ES.po
  sale_isolated_quotation/i18n/es_VE.po
  sale_isolated_quotation/i18n/fi.po
  sale_isolated_quotation/i18n/fr.po
  sale_isolated_quotation/i18n/hr.po
  sale_isolated_quotation/i18n/hr_HR.po
  sale_isolated_quotation/i18n/hu.po
  sale_isolated_quotation/i18n/it.po
  sale_isolated_quotation/i18n/nl.po
  sale_isolated_quotation/i18n/nl_NL.po
  sale_isolated_quotation/i18n/pt.po
  sale_isolated_quotation/i18n/pt_BR.po
  sale_isolated_quotation/i18n/ro.po
  sale_isolated_quotation/i18n/sale_isolated_quotation.pot
  sale_isolated_quotation/i18n/sk.po
  sale_isolated_quotation/i18n/sl.po
  sale_isolated_quotation/i18n/tr.po
  sale_isolated_quotation/i18n/tr_TR.po
  sale_isolated_quotation/i18n/vi_VN.po
  sale_isolated_quotation/i18n/zh_CN.po
  sale_isolated_quotation/models/__init__.py
  sale_isolated_quotation/models/sale.py
  sale_isolated_quotation/readme/CONTRIBUTORS.rst
  sale_isolated_quotation/readme/DESCRIPTION.rst
  sale_isolated_quotation/readme/ROADMAP.rst
  sale_isolated_quotation/readme/USAGE.rst
  sale_isolated_quotation/static/description/icon.png
  sale_isolated_quotation/static/description/index.html
  sale_isolated_quotation/tests/__init__.py
  sale_isolated_quotation/tests/test_sale_isolated_quotation.py
  sale_isolated_quotation/views/sale_views.xml
  sale_order_type/__manifest__.py
  sale_order_type/models/account_move.py
  sale_order_type/models/sale.py
  sale_order_type/tests/test_sale_order_type.py
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_isolated_quotation/odoo/addons/sale_isolated_quotation
  setup/sale_isolated_quotation/setup.py
Labels: 13.0

#648 Update 20201201: Updating project branch with BT/13.0
  sale_isolated_quotation/README.rst
  sale_isolated_quotation/__init__.py
  sale_isolated_quotation/__manifest__.py
  sale_isolated_quotation/data/ir_sequence_data.xml
  sale_isolated_quotation/hooks.py
  sale_isolated_quotation/i18n/ca.po
  sale_isolated_quotation/i18n/de.po
  sale_isolated_quotation/i18n/el_GR.po
  sale_isolated_quotation/i18n/es.po
  sale_isolated_quotation/i18n/es_ES.po
  sale_isolated_quotation/i18n/es_VE.po
  sale_isolated_quotation/i18n/fi.po
  sale_isolated_quotation/i18n/fr.po
  sale_isolated_quotation/i18n/hr.po
  sale_isolated_quotation/i18n/hr_HR.po
  sale_isolated_quotation/i18n/hu.po
  sale_isolated_quotation/i18n/it.po
  sale_isolated_quotation/i18n/nl.po
  sale_isolated_quotation/i18n/nl_NL.po
  sale_isolated_quotation/i18n/pt.po
  sale_isolated_quotation/i18n/pt_BR.po
  sale_isolated_quotation/i18n/ro.po
  sale_isolated_quotation/i18n/sale_isolated_quotation.pot
  sale_isolated_quotation/i18n/sk.po
  sale_isolated_quotation/i18n/sl.po
  sale_isolated_quotation/i18n/tr.po
  sale_isolated_quotation/i18n/tr_TR.po
  sale_isolated_quotation/i18n/vi_VN.po
  sale_isolated_quotation/i18n/zh_CN.po
  sale_isolated_quotation/models/__init__.py
  sale_isolated_quotation/models/sale.py
  sale_isolated_quotation/readme/CONTRIBUTORS.rst
  sale_isolated_quotation/readme/DESCRIPTION.rst
  sale_isolated_quotation/readme/ROADMAP.rst
  sale_isolated_quotation/readme/USAGE.rst
  sale_isolated_quotation/static/description/icon.png
  sale_isolated_quotation/static/description/index.html
  sale_isolated_quotation/tests/__init__.py
  sale_isolated_quotation/tests/test_sale_isolated_quotation.py
  sale_isolated_quotation/views/sale_views.xml
  sale_order_type/__manifest__.py
  sale_order_type/models/account_move.py
  sale_order_type/models/sale.py
  sale_order_type/tests/test_sale_order_type.py
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_isolated_quotation/odoo/addons/sale_isolated_quotation
  setup/sale_isolated_quotation/setup.py
Labels: 13.0.project_mi_465

#649 [t113973] Update 20201201: Set commitortag for odoo and enterprise
  .braintec/deploy.yaml
Labels: 13.0.project_mi_465

#650 Syncing from upstream OCA/sale-workflow (13.0)
  sale_order_type/__manifest__.py
  sale_order_type/models/account_move.py
Labels: 13.0
