Repository brain-tec/sale-workflow, pull requests merged in 2020-10, with the labels that each got.

#583 Syncing from upstream OCA/sale-workflow (12.0)
  sale_mrp_link/i18n/fr.po
Labels: 12.0

#584 Syncing from upstream OCA/sale-workflow (13.0)
  sale_invoice_plan/README.rst
  sale_invoice_plan/__init__.py
  sale_invoice_plan/__manifest__.py
  sale_invoice_plan/i18n/fr.po
  sale_invoice_plan/i18n/nl_NL.po
  sale_invoice_plan/i18n/sale_invoice_plan.pot
  sale_invoice_plan/i18n/zh_CN.po
  sale_invoice_plan/models/__init__.py
  sale_invoice_plan/models/sale.py
  sale_invoice_plan/readme/CONTRIBUTORS.rst
  sale_invoice_plan/readme/DESCRIPTION.rst
  sale_invoice_plan/readme/HISTORY.rst
  sale_invoice_plan/readme/INSTALL.rst
  sale_invoice_plan/readme/USAGE.rst
  sale_invoice_plan/security/ir.model.access.csv
  sale_invoice_plan/static/description/icon.png
  sale_invoice_plan/static/description/index.html
  sale_invoice_plan/tests/__init__.py
  sale_invoice_plan/tests/test_sale_invoice_plan.py
  sale_invoice_plan/views/sale_view.xml
  sale_invoice_plan/wizard/__init__.py
  sale_invoice_plan/wizard/sale_create_invoice_plan.py
  sale_invoice_plan/wizard/sale_create_invoice_plan_view.xml
  sale_invoice_plan/wizard/sale_make_invoice_advance.py
  sale_invoice_plan/wizard/sale_make_planned_invoice.py
  sale_invoice_plan/wizard/sale_make_planned_invoice_view.xml
  sale_order_product_availability_inline/i18n/es.po
  sale_product_category_menu/README.rst
  sale_product_category_menu/__init__.py
  sale_product_category_menu/__manifest__.py
  sale_product_category_menu/i18n/sale_product_category_menu.pot
  sale_product_category_menu/readme/CONTRIBUTORS.rst
  sale_product_category_menu/readme/DESCRIPTION.rst
  sale_product_category_menu/static/description/icon.png
  sale_product_category_menu/static/description/index.html
  sale_product_category_menu/views/sale_views.xml
  sale_quotation_number/i18n/ca.po
  sale_quotation_number/i18n/de.po
  sale_quotation_number/i18n/es.po
  sale_quotation_number/i18n/es_ES.po
  sale_quotation_number/i18n/fi.po
  sale_quotation_number/i18n/fr.po
  sale_quotation_number/i18n/hr.po
  sale_quotation_number/i18n/hu.po
  sale_quotation_number/i18n/it.po
  sale_quotation_number/i18n/nl.po
  sale_quotation_number/i18n/nl_NL.po
  sale_quotation_number/i18n/pt_BR.po
  sale_quotation_number/i18n/ro.po
  sale_quotation_number/i18n/sk.po
  sale_quotation_number/i18n/sl.po
  sale_quotation_number/i18n/tr.po
  sale_quotation_number/i18n/tr_TR.po
  sale_quotation_number/i18n/zh_CN.po
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_invoice_plan/odoo/addons/sale_invoice_plan
  setup/sale_invoice_plan/setup.py
  setup/sale_product_category_menu/odoo/addons/sale_product_category_menu
  setup/sale_product_category_menu/setup.py
Labels: 13.0

#585 Syncing from upstream OCA/sale-workflow (12.0)
  sale_rental/i18n/pt_BR.po
Labels: 12.0

#586 Syncing from upstream OCA/sale-workflow (12.0)
  product_form_sale_link/i18n/fr.po
Labels: 12.0

#588 Syncing from upstream OCA/sale-workflow (13.0)
  sale_order_product_availability_inline/__manifest__.py
  sale_order_product_availability_inline/models/product_product.py
  sale_order_product_availability_inline/models/sale.py
  sale_order_product_availability_inline/views/sale_views.xml
Labels: 13.0

#589 Syncing from upstream OCA/sale-workflow (11.0)
  sale_automatic_workflow/i18n/es.po
Labels: 11.0

#593 Syncing from upstream OCA/sale-workflow (11.0)
  sale_blanket_order/README.rst
  sale_blanket_order/__manifest__.py
  sale_blanket_order/i18n/de.po
  sale_blanket_order/i18n/sale_blanket_order.pot
  sale_blanket_order/readme/CONTRIBUTORS.rst
  sale_blanket_order/readme/USAGE.rst
  sale_blanket_order/static/description/index.html
  sale_blanket_order/tests/test_blanket_orders.py
  sale_blanket_order/wizard/create_sale_orders.py
Labels: 11.0

#595 Syncing from upstream OCA/sale-workflow (13.0)
  sale_discount_display_amount/__manifest__.py
  sale_discount_display_amount/hooks.py
  sale_sourced_by_line/i18n/ca.po
  sale_sourced_by_line/i18n/de.po
  sale_sourced_by_line/i18n/el_GR.po
  sale_sourced_by_line/i18n/es.po
  sale_sourced_by_line/i18n/es_ES.po
  sale_sourced_by_line/i18n/es_VE.po
  sale_sourced_by_line/i18n/fi.po
  sale_sourced_by_line/i18n/fr.po
  sale_sourced_by_line/i18n/hr.po
  sale_sourced_by_line/i18n/hr_HR.po
  sale_sourced_by_line/i18n/hu.po
  sale_sourced_by_line/i18n/it.po
  sale_sourced_by_line/i18n/nl.po
  sale_sourced_by_line/i18n/nl_NL.po
  sale_sourced_by_line/i18n/pt.po
  sale_sourced_by_line/i18n/pt_BR.po
  sale_sourced_by_line/i18n/ro.po
  sale_sourced_by_line/i18n/sk.po
  sale_sourced_by_line/i18n/sl.po
  sale_sourced_by_line/i18n/tr.po
  sale_sourced_by_line/i18n/tr_TR.po
  sale_sourced_by_line/i18n/vi_VN.po
  sale_sourced_by_line/i18n/zh_CN.po
Labels: 13.0

#596 Syncing from upstream OCA/sale-workflow (12.0)
  sale_global_discount/__manifest__.py
  sale_global_discount/models/sale_order.py
Labels: 12.0

#598 Syncing from upstream OCA/sale-workflow (10.0)
  README.md
  sale_procurement_amendment/README.rst
  sale_procurement_amendment/__init__.py
  sale_procurement_amendment/__manifest__.py
  sale_procurement_amendment/i18n/sale_procurement_amendment.pot
  sale_procurement_amendment/models/__init__.py
  sale_procurement_amendment/models/sale_order_line.py
  sale_procurement_amendment/models/stock_move.py
  sale_procurement_amendment/models/stock_picking.py
  sale_procurement_amendment/readme/CONTRIBUTORS.rst
  sale_procurement_amendment/readme/DESCRIPTION.rst
  sale_procurement_amendment/readme/HISTORY.rst
  sale_procurement_amendment/readme/INSTALL.rst
  sale_procurement_amendment/readme/USAGE.rst
  sale_procurement_amendment/static/description/icon.png
  sale_procurement_amendment/static/description/index.html
  sale_procurement_amendment/tests/__init__.py
  sale_procurement_amendment/tests/test_sale_procurement_amendment.py
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_procurement_amendment/odoo/__init__.py
  setup/sale_procurement_amendment/odoo/addons/__init__.py
  setup/sale_procurement_amendment/odoo/addons/sale_procurement_amendment
  setup/sale_procurement_amendment/setup.py
Labels: 10.0

#599 Syncing from upstream OCA/sale-workflow (12.0)
  sale_invoice_policy/i18n/fr.po
Labels: 12.0

#600 Syncing from upstream OCA/sale-workflow (12.0)
  sale_order_tag/i18n/it.po
Labels: 12.0

#601 [t113973] Preparing sale-workflow for brain-tec's Docker.
  .braintec/deploy.yaml
  ext/.gitignore
Labels: 13.0.project_mi_465

#602 Syncing from upstream OCA/sale-workflow (13.0)
  .pre-commit-config.yaml
  sale_by_packaging/i18n/es.po
  sale_invoice_plan/i18n/es.po
  sale_order_carrier_auto_assign/i18n/es.po
  sale_order_general_discount/i18n/es.po
  sale_order_product_availability_inline/i18n/es.po
  sale_product_category_menu/i18n/es.po
  sale_product_set_packaging_qty/i18n/es.po
  sale_quotation_number/i18n/es.po
  sale_sourced_by_line/i18n/es.po
  sale_validity/i18n/es.po
  sales_team_security/i18n/es.po
Labels: 13.0

#603 Syncing from upstream OCA/sale-workflow (14.0)
  README.md
  sale_order_archive/README.rst
  sale_order_archive/__init__.py
  sale_order_archive/__manifest__.py
  sale_order_archive/i18n/de.po
  sale_order_archive/i18n/es.po
  sale_order_archive/i18n/sale_order_archive.pot
  sale_order_archive/i18n/zh_CN.po
  sale_order_archive/models/__init__.py
  sale_order_archive/models/sale_order.py
  sale_order_archive/readme/CONTRIBUTORS.rst
  sale_order_archive/readme/DESCRIPTION.rst
  sale_order_archive/readme/INSTALL.rst
  sale_order_archive/readme/USAGE.rst
  sale_order_archive/static/description/icon.png
  sale_order_archive/static/description/index.html
  sale_order_archive/views/sale_order.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_order_archive/odoo/addons/sale_order_archive
  setup/sale_order_archive/setup.py
Labels: 14.0

#604 Syncing from upstream OCA/sale-workflow (13.0)
  sale_by_packaging/README.rst
  sale_by_packaging/__manifest__.py
  sale_by_packaging/i18n/es.po
  sale_by_packaging/i18n/sale_by_packaging.pot
  sale_by_packaging/models/product_packaging.py
  sale_by_packaging/models/product_product.py
  sale_by_packaging/models/sale_order_line.py
  sale_by_packaging/readme/CONFIGURE.rst
  sale_by_packaging/readme/CONTRIBUTORS.rst
  sale_by_packaging/readme/DESCRIPTION.rst
  sale_by_packaging/static/description/index.html
  sale_by_packaging/tests/test_sale_only_by_packaging.py
  sale_by_packaging/views/product_packaging.xml
  sale_fixed_discount/__manifest__.py
  sale_fixed_discount/reports/report_sale_order.xml
  sale_sourced_by_line/README.rst
  sale_sourced_by_line/__manifest__.py
  sale_sourced_by_line/tests/test_sale_sourced_by_line.py
Labels: 13.0

#605 Syncing from upstream OCA/sale-workflow (12.0)
  sale_order_incoterm_place/README.rst
  sale_order_incoterm_place/__init__.py
  sale_order_incoterm_place/__manifest__.py
  sale_order_incoterm_place/i18n/ja.po
  sale_order_incoterm_place/i18n/sale_order_incoterm_place.pot
  sale_order_incoterm_place/models/__init__.py
  sale_order_incoterm_place/models/sale_order.py
  sale_order_incoterm_place/readme/CONTRIBUTORS.rst
  sale_order_incoterm_place/readme/DESCRIPTION.rst
  sale_order_incoterm_place/report/sale_order_report_templates.xml
  sale_order_incoterm_place/static/description/icon.png
  sale_order_incoterm_place/static/description/index.html
  sale_order_incoterm_place/views/sale_order_views.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_order_incoterm_place/odoo/addons/sale_order_incoterm_place
  setup/sale_order_incoterm_place/setup.py
Labels: 12.0

#606 Syncing from upstream OCA/sale-workflow (13.0)
  sale_order_line_date/__manifest__.py
  sale_order_line_date/views/sale_order_view.xml
  sale_stock_delivery_address/__manifest__.py
  sale_stock_delivery_address/models/procurement_group.py
Labels: 13.0
