Repository brain-tec/sale-workflow, pull requests merged in 2020-09, with the labels that each got.

#556 Syncing from upstream OCA/sale-workflow (12.0)
  sale_commitment_lead_time/i18n/ca.po
  sale_elaboration/i18n/ca.po
  sale_fixed_discount/i18n/ca.po
  sale_order_type/i18n/ca.po
  sale_procurement_group_by_line/i18n/ca.po
  sale_stock_delivery_address/i18n/ca.po
  sale_stock_picking_note/i18n/ca.po
  sale_stock_return_request/i18n/ca.po
  sale_tier_validation/i18n/ca.po
Labels: 12.0

#557 Syncing from upstream OCA/sale-workflow (12.0)
  sale_invoice_plan/i18n/it.po
  sale_invoice_policy/i18n/pt.po
Labels: 12.0

#558 [bt#11722] Reservation process of a delivery fails due to sale_order_lot_selection
  sale_order_lot_selection/__manifest__.py
  sale_order_lot_selection/models/stock.py
Labels: 13.0.project_mi_465

#559 [bt#11722] Reservation process of a delivery fails due to sale_order_lot_selection
  sale_order_lot_selection/models/stock.py
Labels: 13.0.project_mi_465

#560 Syncing from upstream OCA/sale-workflow (12.0)
  portal_sale_personal_data_only/__manifest__.py
  sale_automatic_workflow_payment_mode/views/sale_workflow_process_view.xml
  sale_cancel_reason/__init__.py
  sale_cancel_reason/__manifest__.py
  sale_cancel_reason/model/__init__.py
  sale_cancel_reason/model/sale.py
  sale_cancel_reason/tests/__init__.py
  sale_cancel_reason/tests/test_sale_cancel_reason.py
  sale_cancel_reason/wizard/__init__.py
  sale_cancel_reason/wizard/cancel_reason.py
  sale_exception/models/sale_order_line.py
  sale_invoice_policy/__manifest__.py
  sale_invoice_policy/i18n/pt.po
  sale_isolated_quotation/readme/ROADMAP.rst
  sale_order_transmit_method/readme/DESCRIPTION.rst
  sale_partner_incoterm/readme/CONTRIBUTORS.rst
  sale_partner_incoterm/readme/DESCRIPTION.rst
  sale_quotation_number/README.rst
  sale_quotation_number/__init__.py
  sale_quotation_number/__manifest__.py
  sale_quotation_number/data/data.xml
  sale_quotation_number/i18n/ca.po
  sale_quotation_number/i18n/de.po
  sale_quotation_number/i18n/es.po
  sale_quotation_number/i18n/es_ES.po
  sale_quotation_number/i18n/fi.po
  sale_quotation_number/i18n/fr.po
  sale_quotation_number/i18n/hr.po
  sale_quotation_number/i18n/hu.po
  sale_quotation_number/i18n/it.po
  sale_quotation_number/i18n/nl.po
  sale_quotation_number/i18n/nl_NL.po
  sale_quotation_number/i18n/pt_BR.po
  sale_quotation_number/i18n/ro.po
  sale_quotation_number/i18n/sale_quotation_number.pot
  sale_quotation_number/i18n/sk.po
  sale_quotation_number/i18n/sl.po
  sale_quotation_number/i18n/tr.po
  sale_quotation_number/i18n/tr_TR.po
  sale_quotation_number/i18n/zh_CN.po
  sale_quotation_number/models/__init__.py
  sale_quotation_number/models/res_company.py
  sale_quotation_number/models/sale_order.py
  sale_quotation_number/readme/CONFIGURE.rst
  sale_quotation_number/readme/CONTRIBUTORS.rst
  sale_quotation_number/readme/CREDITS.rst
  sale_quotation_number/readme/DESCRIPTION.rst
  sale_quotation_number/readme/ROADMAP.rst
  sale_quotation_number/readme/USAGE.rst
  sale_quotation_number/static/description/icon.png
  sale_quotation_number/static/description/index.html
  sale_quotation_number/tests/__init__.py
  sale_quotation_number/tests/test_sale_order.py
  sale_quotation_number/views/sales_config.xml
  sales_team_security/readme/CONTRIBUTORS.rst
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_quotation_number/odoo/addons/sale_quotation_number
  setup/sale_quotation_number/setup.py
Labels: 12.0

#561 Syncing from upstream OCA/sale-workflow (12.0)
  sale_last_price_info/i18n/pt.po
Labels: 12.0

#562 Syncing from upstream OCA/sale-workflow (12.0)
  sale_last_price_info/i18n/pt.po
  sale_order_type/i18n/pt.po
  sale_triple_discount/i18n/it.po
Labels: 12.0

#563 Syncing from upstream OCA/sale-workflow (13.0)
  sale_quotation_number/README.rst
  sale_quotation_number/__init__.py
  sale_quotation_number/__manifest__.py
  sale_quotation_number/data/data.xml
  sale_quotation_number/i18n/ca.po
  sale_quotation_number/i18n/de.po
  sale_quotation_number/i18n/es.po
  sale_quotation_number/i18n/es_ES.po
  sale_quotation_number/i18n/fi.po
  sale_quotation_number/i18n/fr.po
  sale_quotation_number/i18n/hr.po
  sale_quotation_number/i18n/hu.po
  sale_quotation_number/i18n/it.po
  sale_quotation_number/i18n/nl.po
  sale_quotation_number/i18n/nl_NL.po
  sale_quotation_number/i18n/pt_BR.po
  sale_quotation_number/i18n/ro.po
  sale_quotation_number/i18n/sale_quotation_number.pot
  sale_quotation_number/i18n/sk.po
  sale_quotation_number/i18n/sl.po
  sale_quotation_number/i18n/tr.po
  sale_quotation_number/i18n/tr_TR.po
  sale_quotation_number/i18n/zh_CN.po
  sale_quotation_number/models/__init__.py
  sale_quotation_number/models/res_company.py
  sale_quotation_number/models/sale_order.py
  sale_quotation_number/readme/CONFIGURE.rst
  sale_quotation_number/readme/CONTRIBUTORS.rst
  sale_quotation_number/readme/CREDITS.rst
  sale_quotation_number/readme/DESCRIPTION.rst
  sale_quotation_number/readme/ROADMAP.rst
  sale_quotation_number/readme/USAGE.rst
  sale_quotation_number/static/description/icon.png
  sale_quotation_number/static/description/index.html
  sale_quotation_number/tests/__init__.py
  sale_quotation_number/tests/test_sale_order.py
  sale_quotation_number/views/sales_config.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_quotation_number/odoo/addons/sale_quotation_number
  setup/sale_quotation_number/setup.py
Labels: 13.0

#564 Syncing from upstream OCA/sale-workflow (10.0)
  README.md
  sale_procurement_group_by_line/__manifest__.py
  sale_procurement_group_by_line/model/sale.py
  sale_procurement_group_by_line/tests/test_sale_procurement_group_by_line.py
Labels: 10.0

#565 Syncing from upstream OCA/sale-workflow (12.0)
  sale_invoice_policy/i18n/fr.po
  sale_product_multi_add/i18n/fr.po
Labels: 12.0

#566 Syncing from upstream OCA/sale-workflow (13.0)
  sale_quotation_number/README.rst
  sale_quotation_number/readme/CONTRIBUTORS.rst
  sale_quotation_number/readme/DESCRIPTION.rst
  sale_quotation_number/readme/ROADMAP.rst
  sale_quotation_number/readme/USAGE.rst
  sale_quotation_number/static/description/index.html
Labels: 13.0

#567 Syncing from upstream OCA/sale-workflow (13.0)
  sale_order_product_recommendation/__manifest__.py
  sale_order_product_recommendation/tests/test_recommendation.py
  sale_order_product_recommendation/wizards/sale_order_recommendation.py
Labels: 13.0

#568 Syncing from upstream OCA/sale-workflow (11.0)
  sale_exception/__manifest__.py
  sale_exception/models/sale.py
Labels: 11.0

#570 Syncing from upstream OCA/sale-workflow (12.0)
  sale_order_price_recalculation/__manifest__.py
  sale_order_price_recalculation/views/sale_order_view.xml
  sale_order_type/__manifest__.py
  sale_order_type/migrations/12.0.1.1.1/post-migration.py
  sale_product_category_menu/README.rst
  sale_product_category_menu/__init__.py
  sale_product_category_menu/__manifest__.py
  sale_product_category_menu/i18n/sale_product_category_menu.pot
  sale_product_category_menu/readme/CONTRIBUTORS.rst
  sale_product_category_menu/readme/DESCRIPTION.rst
  sale_product_category_menu/static/description/icon.png
  sale_product_category_menu/static/description/index.html
  sale_product_category_menu/views/sale_views.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_product_category_menu/odoo/addons/sale_product_category_menu
  setup/sale_product_category_menu/setup.py
Labels: 12.0

#571 Syncing from upstream OCA/sale-workflow (12.0)
  sale_global_discount/i18n/pt.po
  sale_order_line_price_history/i18n/pt.po
Labels: 12.0

#572 Syncing from upstream OCA/sale-workflow (13.0)
  sale_order_type/__manifest__.py
  sale_order_type/models/account_move.py
  sale_order_type/tests/test_sale_order_type.py
  sale_order_type/views/account_move_views.xml
Labels: 13.0

#574 Syncing from upstream OCA/sale-workflow (12.0)
  product_supplierinfo_for_customer_sale/i18n/pt.po
  sale_global_discount/i18n/pt.po
Labels: 12.0

#575 Syncing from upstream OCA/sale-workflow (13.0)
  sale_order_product_recommendation/__manifest__.py
  sale_order_product_recommendation/wizards/sale_order_recommendation.py
Labels: 13.0

#576 Syncing from upstream OCA/sale-workflow (13.0)
  sale_product_set_packaging_qty/__manifest__.py
  sale_product_set_packaging_qty/models/product_set.py
Labels: 13.0

#577 Syncing from upstream OCA/sale-workflow (13.0)
  oca_dependencies.txt
  sale_order_product_availability_inline/README.rst
  sale_order_product_availability_inline/__init__.py
  sale_order_product_availability_inline/__manifest__.py
  sale_order_product_availability_inline/i18n/es.po
  sale_order_product_availability_inline/i18n/sale_order_product_availability_inline.pot
  sale_order_product_availability_inline/models/__init__.py
  sale_order_product_availability_inline/models/product_product.py
  sale_order_product_availability_inline/models/sale.py
  sale_order_product_availability_inline/readme/CONTRIBUTORS.rst
  sale_order_product_availability_inline/readme/DESCRIPTION.rst
  sale_order_product_availability_inline/readme/USAGE.rst
  sale_order_product_availability_inline/static/description/icon.png
  sale_order_product_availability_inline/static/description/index.html
  sale_order_product_availability_inline/tests/__init__.py
  sale_order_product_availability_inline/tests/test_sale_order_product_availability_inline.py
  sale_order_product_availability_inline/views/sale_views.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_order_product_availability_inline/odoo/addons/sale_order_product_availability_inline
  setup/sale_order_product_availability_inline/setup.py
Labels: 13.0

#579 Syncing from upstream OCA/sale-workflow (12.0)
  sale_require_po_doc/README.rst
  sale_require_po_doc/__init__.py
  sale_require_po_doc/__manifest__.py
  sale_require_po_doc/i18n/sale_require_po_doc.pot
  sale_require_po_doc/models/__init__.py
  sale_require_po_doc/models/res_partner.py
  sale_require_po_doc/models/sale_order.py
  sale_require_po_doc/readme/CONTRIBUTORS.rst
  sale_require_po_doc/readme/CREDITS.rst
  sale_require_po_doc/readme/DESCRIPTION.rst
  sale_require_po_doc/static/description/icon.png
  sale_require_po_doc/static/description/index.html
  sale_require_po_doc/views/res_partner_view.xml
  sale_require_po_doc/views/sale_order_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_require_po_doc/odoo/addons/sale_require_po_doc
  setup/sale_require_po_doc/setup.py
Labels: 12.0

#580 Syncing from upstream OCA/sale-workflow (13.0)
  sales_team_security/README.rst
  sales_team_security/__init__.py
  sales_team_security/__manifest__.py
  sales_team_security/hooks.py
  sales_team_security/i18n/es.po
  sales_team_security/i18n/sales_team_security.pot
  sales_team_security/models/__init__.py
  sales_team_security/models/ir_rule.py
  sales_team_security/models/res_partner.py
  sales_team_security/readme/CONFIGURE.rst
  sales_team_security/readme/CONTRIBUTORS.rst
  sales_team_security/readme/DESCRIPTION.rst
  sales_team_security/readme/INSTALL.rst
  sales_team_security/readme/ROADMAP.rst
  sales_team_security/security/sales_team_security.xml
  sales_team_security/static/description/icon.png
  sales_team_security/static/description/index.html
  sales_team_security/tests/__init__.py
  sales_team_security/tests/test_sales_team_security.py
  sales_team_security/views/res_partner_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sales_team_security/odoo/addons/sales_team_security
  setup/sales_team_security/setup.py
Labels: 13.0

#581 Syncing from upstream OCA/sale-workflow (13.0)
  sale_fixed_discount/README.rst
  sale_fixed_discount/readme/CONTRIBUTORS.rst
  sale_fixed_discount/static/description/index.html
  sale_order_line_date/__manifest__.py
Labels: 13.0
