Repository brain-tec/sale-workflow, pull requests merged in 2021-12, with the labels that each got.

#911 Syncing from upstream OCA/sale-workflow (12.0)
  README.md
  sales_team_security/__manifest__.py
  sales_team_security/migrations/12.0.4.0.0/pre-migration.py
  sales_team_security/security/sales_team_security.xml
Labels: 12.0

#912 Syncing from upstream OCA/sale-workflow (13.0)
  README.md
  sales_team_security/__manifest__.py
  sales_team_security/migrations/13.0.3.0.0/pre-migration.py
  sales_team_security/security/sales_team_security.xml
Labels: 13.0

#914 Syncing from upstream OCA/sale-workflow (13.0)
  README.md
  sale_order_type/i18n/fr.po
  sale_partner_selectable_option/README.rst
  sale_partner_selectable_option/__manifest__.py
  sale_partner_selectable_option/i18n/es.po
  sale_partner_selectable_option/i18n/sale_partner_selectable_option.pot
  sale_partner_selectable_option/migrations/13.0.2.0.0/pre-migration.py
  sale_partner_selectable_option/models/res_partner.py
  sale_partner_selectable_option/readme/DESCRIPTION.rst
  sale_partner_selectable_option/readme/USAGE.rst
  sale_partner_selectable_option/static/description/index.html
  sale_partner_selectable_option/tests/test_sale_partner_selectable_option.py
  sale_partner_selectable_option/views/res_partner_view.xml
  sale_partner_selectable_option/views/sale_order_view.xml
Labels: 13.0

#916 Syncing from upstream OCA/sale-workflow (12.0)
  README.md
  sale_order_line_serial_unique/README.rst
  sale_order_line_serial_unique/__init__.py
  sale_order_line_serial_unique/__manifest__.py
  sale_order_line_serial_unique/i18n/sale_order_line_serial_unique.pot
  sale_order_line_serial_unique/models/__init__.py
  sale_order_line_serial_unique/models/sale_order_line.py
  sale_order_line_serial_unique/readme/CONTRIBUTORS.rst
  sale_order_line_serial_unique/readme/DESCRIPTION.rst
  sale_order_line_serial_unique/static/description/icon.png
  sale_order_line_serial_unique/static/description/index.html
  sale_order_line_serial_unique/tests/__init__.py
  sale_order_line_serial_unique/tests/test_serial_unique.py
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_order_line_serial_unique/odoo/addons/sale_order_line_serial_unique
  setup/sale_order_line_serial_unique/setup.py
Labels: 12.0

#917 Syncing from upstream OCA/sale-workflow (15.0)
  README.md
  sale_order_line_date/README.rst
  sale_order_line_date/__init__.py
  sale_order_line_date/__manifest__.py
  sale_order_line_date/i18n/ca.po
  sale_order_line_date/i18n/de.po
  sale_order_line_date/i18n/el_GR.po
  sale_order_line_date/i18n/es.po
  sale_order_line_date/i18n/es_ES.po
  sale_order_line_date/i18n/es_VE.po
  sale_order_line_date/i18n/fi.po
  sale_order_line_date/i18n/fr.po
  sale_order_line_date/i18n/hr.po
  sale_order_line_date/i18n/hr_HR.po
  sale_order_line_date/i18n/hu.po
  sale_order_line_date/i18n/it.po
  sale_order_line_date/i18n/nl.po
  sale_order_line_date/i18n/nl_NL.po
  sale_order_line_date/i18n/pt.po
  sale_order_line_date/i18n/pt_BR.po
  sale_order_line_date/i18n/ro.po
  sale_order_line_date/i18n/sale_order_line_date.pot
  sale_order_line_date/i18n/sk.po
  sale_order_line_date/i18n/sl.po
  sale_order_line_date/i18n/tr.po
  sale_order_line_date/i18n/tr_TR.po
  sale_order_line_date/i18n/vi_VN.po
  sale_order_line_date/i18n/zh_CN.po
  sale_order_line_date/models/__init__.py
  sale_order_line_date/models/sale_order.py
  sale_order_line_date/models/sale_order_line.py
  sale_order_line_date/readme/CONTRIBUTORS.rst
  sale_order_line_date/readme/DESCRIPTION.rst
  sale_order_line_date/readme/USAGE.rst
  sale_order_line_date/reports/sale_order_report.xml
  sale_order_line_date/static/description/icon.png
  sale_order_line_date/static/description/index.html
  sale_order_line_date/tests/__init__.py
  sale_order_line_date/tests/test_sale_order_line_date.py
  sale_order_line_date/views/sale_order_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_order_line_date/odoo/addons/sale_order_line_date
  setup/sale_order_line_date/setup.py
Labels: 15.0

#918 Syncing from upstream OCA/sale-workflow (12.0-ocabot-merge-pr-1324-by-dreispt-bump-patch)
  sale_require_po_doc/i18n/sale_require_po_doc.pot
Labels: 12.0-ocabot-merge-pr-1324-by-dreispt-bump-patch

#919 Syncing from upstream OCA/sale-workflow (13.0)
  sales_team_security/i18n/es.po
Labels: 13.0

#921 Merging 13.0 into 13.0.project_MI_465
  README.md
  sale_order_type/i18n/fr.po
  sale_partner_selectable_option/README.rst
  sale_partner_selectable_option/__manifest__.py
  sale_partner_selectable_option/i18n/es.po
  sale_partner_selectable_option/i18n/sale_partner_selectable_option.pot
  sale_partner_selectable_option/migrations/13.0.2.0.0/pre-migration.py
  sale_partner_selectable_option/models/res_partner.py
  sale_partner_selectable_option/readme/DESCRIPTION.rst
  sale_partner_selectable_option/readme/USAGE.rst
  sale_partner_selectable_option/static/description/index.html
  sale_partner_selectable_option/tests/test_sale_partner_selectable_option.py
  sale_partner_selectable_option/views/res_partner_view.xml
  sale_partner_selectable_option/views/sale_order_view.xml
  sales_team_security/__manifest__.py
  sales_team_security/i18n/es.po
  sales_team_security/migrations/13.0.3.0.0/pre-migration.py
  sales_team_security/security/sales_team_security.xml
Labels: 13.0.project_mi_465

#922 Syncing from upstream OCA/sale-workflow (12.0)
  sale_delivery_state/i18n/ja.po
Labels: 12.0

#923 Syncing from upstream OCA/sale-workflow (11.0)
  sale_timesheet_lock_invoiced/README.rst
  sale_timesheet_lock_invoiced/__init__.py
  sale_timesheet_lock_invoiced/__manifest__.py
  sale_timesheet_lock_invoiced/i18n/fr.po
  sale_timesheet_lock_invoiced/i18n/sale_timesheet_lock_invoiced.pot
  sale_timesheet_lock_invoiced/models/__init__.py
  sale_timesheet_lock_invoiced/models/account_analytic_line.py
  sale_timesheet_lock_invoiced/static/description/icon.png
  sale_timesheet_lock_invoiced/tests/__init__.py
  sale_timesheet_lock_invoiced/tests/test_sale_timesheet_lock_invoiced.py
  sale_timesheet_project_link/README.rst
  sale_timesheet_project_link/__init__.py
  sale_timesheet_project_link/__manifest__.py
  sale_timesheet_project_link/i18n/fr.po
  sale_timesheet_project_link/i18n/sale_timesheet_project_link.pot
  sale_timesheet_project_link/models/__init__.py
  sale_timesheet_project_link/models/sale_order.py
  sale_timesheet_project_link/static/description/icon.png
  sale_timesheet_project_link/tests/__init__.py
  sale_timesheet_project_link/tests/test_sale_timesheet_project_link.py
  sale_timesheet_project_link/views/sale_order.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_timesheet_lock_invoiced/odoo/addons/sale_timesheet_lock_invoiced
  setup/sale_timesheet_lock_invoiced/setup.cfg
  setup/sale_timesheet_lock_invoiced/setup.py
  setup/sale_timesheet_project_link/odoo/addons/sale_timesheet_project_link
  setup/sale_timesheet_project_link/setup.cfg
  setup/sale_timesheet_project_link/setup.py
Labels: 11.0

#924 Syncing from upstream OCA/sale-workflow (12.0)
  sale_delivery_state/i18n/it.po
  sale_manual_delivery/i18n/it.po
Labels: 12.0

#925 Syncing from upstream OCA/sale-workflow (13.0)
  README.md
  sale_partner_selectable_option/__manifest__.py
  sale_partner_selectable_option/i18n/es.po
  sale_partner_selectable_option/i18n/sale_partner_selectable_option.pot
  sale_partner_selectable_option/models/__init__.py
  sale_partner_selectable_option/models/sale_order.py
  sale_partner_selectable_option/tests/test_sale_partner_selectable_option.py
  sale_partner_selectable_option/views/sale_order_view.xml
  sale_stock_cancel_restriction/README.rst
  sale_stock_cancel_restriction/__init__.py
  sale_stock_cancel_restriction/__manifest__.py
  sale_stock_cancel_restriction/i18n/sale_stock_cancel_restriction.pot
  sale_stock_cancel_restriction/models/__init__.py
  sale_stock_cancel_restriction/models/sale_order.py
  sale_stock_cancel_restriction/readme/CONTRIBUTORS.rst
  sale_stock_cancel_restriction/readme/DESCRIPTION.rst
  sale_stock_cancel_restriction/readme/USAGE.rst
  sale_stock_cancel_restriction/static/description/icon.png
  sale_stock_cancel_restriction/static/description/index.html
  sale_stock_cancel_restriction/tests/__init__.py
  sale_stock_cancel_restriction/tests/test_sale_stock_cancel_restriction.py
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_stock_cancel_restriction/odoo/addons/sale_stock_cancel_restriction
  setup/sale_stock_cancel_restriction/setup.py
Labels: 13.0

#926 Syncing from upstream OCA/sale-workflow (14.0)
  README.md
  sale_delivery_date/i18n/de.po
  sale_delivery_date/i18n/fr_CH.po
  sale_delivery_date/i18n/it.po
  sales_team_security/README.rst
  sales_team_security/__manifest__.py
  sales_team_security/hooks.py
  sales_team_security/i18n/es.po
  sales_team_security/i18n/it.po
  sales_team_security/i18n/sales_team_security.pot
  sales_team_security/models/res_partner.py
  sales_team_security/readme/CONTRIBUTORS.rst
  sales_team_security/readme/DESCRIPTION.rst
  sales_team_security/readme/INSTALL.rst
  sales_team_security/static/description/index.html
  sales_team_security/tests/common.py
  sales_team_security/tests/test_sales_team_security.py
  sales_team_security_crm/__manifest__.py
  sales_team_security_crm/migrations/14.0.2.0.0/pre-migration.py
  sales_team_security_crm/security/security.xml
  sales_team_security_crm/tests/__init__.py
  sales_team_security_crm/tests/test_sales_team_security_crm.py
  sales_team_security_sale/__manifest__.py
  sales_team_security_sale/migrations/14.0.2.0.0/pre-migration.py
  sales_team_security_sale/security/security.xml
  sales_team_security_sale/tests/__init__.py
  sales_team_security_sale/tests/test_sales_team_security_sale.py
Labels: 14.0

#927 Syncing from upstream OCA/sale-workflow (15.0)
  README.md
  sale_force_invoiced/README.rst
  sale_force_invoiced/__init__.py
  sale_force_invoiced/__manifest__.py
  sale_force_invoiced/i18n/ca.po
  sale_force_invoiced/i18n/de.po
  sale_force_invoiced/i18n/el_GR.po
  sale_force_invoiced/i18n/es.po
  sale_force_invoiced/i18n/es_ES.po
  sale_force_invoiced/i18n/es_VE.po
  sale_force_invoiced/i18n/fi.po
  sale_force_invoiced/i18n/fr.po
  sale_force_invoiced/i18n/hr.po
  sale_force_invoiced/i18n/hr_HR.po
  sale_force_invoiced/i18n/hu.po
  sale_force_invoiced/i18n/it.po
  sale_force_invoiced/i18n/nl.po
  sale_force_invoiced/i18n/nl_NL.po
  sale_force_invoiced/i18n/pt.po
  sale_force_invoiced/i18n/pt_BR.po
  sale_force_invoiced/i18n/ro.po
  sale_force_invoiced/i18n/sale_force_invoiced.pot
  sale_force_invoiced/i18n/sk.po
  sale_force_invoiced/i18n/sl.po
  sale_force_invoiced/i18n/tr.po
  sale_force_invoiced/i18n/tr_TR.po
  sale_force_invoiced/i18n/vi_VN.po
  sale_force_invoiced/i18n/zh_CN.po
  sale_force_invoiced/model/__init__.py
  sale_force_invoiced/model/sale_order.py
  sale_force_invoiced/readme/CONTRIBUTORS.rst
  sale_force_invoiced/readme/DESCRIPTION.rst
  sale_force_invoiced/readme/USAGE.rst
  sale_force_invoiced/static/description/icon.png
  sale_force_invoiced/static/description/index.html
  sale_force_invoiced/tests/__init__.py
  sale_force_invoiced/tests/test_sale_force_invoiced.py
  sale_force_invoiced/view/sale_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_force_invoiced/odoo/addons/sale_force_invoiced
  setup/sale_force_invoiced/setup.py
Labels: 15.0

#928 Syncing from upstream OCA/sale-workflow (12.0)
  README.md
  sale_order_rename/README.rst
  sale_order_rename/__init__.py
  sale_order_rename/__manifest__.py
  sale_order_rename/i18n/sale_order_rename.pot
  sale_order_rename/models/__init__.py
  sale_order_rename/models/sale_order.py
  sale_order_rename/readme/CONTRIBUTORS.rst
  sale_order_rename/readme/DESCRIPTION.rst
  sale_order_rename/static/description/icon.png
  sale_order_rename/static/description/index.html
  sale_order_rename/tests/__init__.py
  sale_order_rename/tests/test_sale_order_rename.py
  sale_order_rename/views/sale_order.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_order_rename/odoo/addons/sale_order_rename
  setup/sale_order_rename/setup.py
Labels: 12.0

#929 Syncing from upstream OCA/sale-workflow (13.0)
  README.md
  sale_order_product_recommendation/README.rst
  sale_order_product_recommendation/__manifest__.py
  sale_order_product_recommendation/i18n/es.po
  sale_order_product_recommendation/i18n/sale_order_product_recommendation.pot
  sale_order_product_recommendation/models/res_config_settings.py
  sale_order_product_recommendation/readme/CONFIGURE.rst
  sale_order_product_recommendation/static/description/index.html
  sale_order_product_recommendation/views/res_config_settings_views.xml
Labels: 13.0

#930 Syncing from upstream OCA/sale-workflow (12.0)
  README.md
  sale_order_type/__manifest__.py
  sale_order_type/i18n/sale_order_type.pot
  sale_order_type/models/sale_order.py
  sale_order_type/models/sale_order_type.py
  sale_order_type/views/sale_order_type_view.xml
Labels: 12.0

#931 Syncing from upstream OCA/sale-workflow (13.0)
  README.md
  sale_order_product_assortment/__manifest__.py
  sale_order_product_assortment/views/sale_order_view.xml
Labels: 13.0
