Repository brain-tec/sale-workflow, pull requests merged in 2021-05, with the labels that each got.

#730 Syncing from upstream OCA/sale-workflow (12.0)
  sale_force_invoiced/i18n/it.po
Labels: 12.0

#731 Syncing from upstream OCA/sale-workflow (12.0)
  README.md
  requirements.txt
  sale_order_min_qty/__init__.py
  sale_order_min_qty/models/__init__.py
  sale_order_min_qty/models/product.py
  sale_order_min_qty/models/sale.py
  sale_order_min_qty/readme/DESCRIPTION.rst
  sale_order_min_qty/tests/test_sale.py
  sale_order_min_qty/views/product_views.xml
  sale_restricted_qty/README.rst
  sale_restricted_qty/__init__.py
  sale_restricted_qty/__manifest__.py
  sale_restricted_qty/hooks.py
  sale_restricted_qty/i18n/sale_order_min_qty.pot
  sale_restricted_qty/i18n/sale_restricted_qty.pot
  sale_restricted_qty/models/__init__.py
  sale_restricted_qty/models/product_category.py
  sale_restricted_qty/models/product_product.py
  sale_restricted_qty/models/product_restricted_qty_mixin.py
  sale_restricted_qty/models/product_template.py
  sale_restricted_qty/models/sale.py
  sale_restricted_qty/readme/CONTRIBUTORS.rst
  sale_restricted_qty/readme/DESCRIPTION.rst
  sale_restricted_qty/readme/USAGE.rst
  sale_restricted_qty/static/description/icon.png
  sale_restricted_qty/static/description/index.html
  sale_restricted_qty/tests/__init__.py
  sale_restricted_qty/tests/test_sale.py
  sale_restricted_qty/views/product_category_views.xml
  sale_restricted_qty/views/product_product_views.xml
  sale_restricted_qty/views/product_template_views.xml
  sale_restricted_qty/views/sale_views.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_order_min_qty/odoo/addons/sale_order_min_qty
  setup/sale_restricted_qty/odoo/addons/sale_restricted_qty
  setup/sale_restricted_qty/setup.py
Labels: 12.0

#732 Syncing from upstream OCA/sale-workflow (14.0)
  README.md
  sale_shipping_info_helper/README.rst
  sale_shipping_info_helper/__init__.py
  sale_shipping_info_helper/__manifest__.py
  sale_shipping_info_helper/i18n/ca.po
  sale_shipping_info_helper/i18n/de.po
  sale_shipping_info_helper/i18n/el_GR.po
  sale_shipping_info_helper/i18n/es.po
  sale_shipping_info_helper/i18n/es_ES.po
  sale_shipping_info_helper/i18n/es_VE.po
  sale_shipping_info_helper/i18n/fi.po
  sale_shipping_info_helper/i18n/fr.po
  sale_shipping_info_helper/i18n/hr.po
  sale_shipping_info_helper/i18n/hr_HR.po
  sale_shipping_info_helper/i18n/hu.po
  sale_shipping_info_helper/i18n/it.po
  sale_shipping_info_helper/i18n/nl.po
  sale_shipping_info_helper/i18n/nl_NL.po
  sale_shipping_info_helper/i18n/pt.po
  sale_shipping_info_helper/i18n/pt_BR.po
  sale_shipping_info_helper/i18n/ro.po
  sale_shipping_info_helper/i18n/sale_shipping_info_helper.pot
  sale_shipping_info_helper/i18n/sk.po
  sale_shipping_info_helper/i18n/sl.po
  sale_shipping_info_helper/i18n/tr.po
  sale_shipping_info_helper/i18n/tr_TR.po
  sale_shipping_info_helper/i18n/vi_VN.po
  sale_shipping_info_helper/i18n/zh_CN.po
  sale_shipping_info_helper/models/__init__.py
  sale_shipping_info_helper/models/sale_order.py
  sale_shipping_info_helper/readme/CONTRIBUTORS.rst
  sale_shipping_info_helper/readme/DESCRIPTION.rst
  sale_shipping_info_helper/static/description/icon.png
  sale_shipping_info_helper/static/description/index.html
  sale_shipping_info_helper/tests/__init__.py
  sale_shipping_info_helper/tests/test_sale_shipping_info_helper.py
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_shipping_info_helper/odoo/addons/sale_shipping_info_helper
  setup/sale_shipping_info_helper/setup.py
Labels: 14.0

#733 Syncing from upstream OCA/sale-workflow (12.0)
  README.md
  sale_start_end_dates/__manifest__.py
  sale_start_end_dates/i18n/sale_start_end_dates.pot
  sale_start_end_dates/models/sale_order.py
Labels: 12.0

#735 Syncing from upstream OCA/sale-workflow (13.0)
  README.md
  sale_automatic_workflow/__manifest__.py
  sale_automatic_workflow/tests/test_automatic_workflow.py
Labels: 13.0

#736 Syncing from upstream OCA/sale-workflow (14.0)
  README.md
  sale_pricelist_from_commitment_date/README.rst
  sale_pricelist_from_commitment_date/__init__.py
  sale_pricelist_from_commitment_date/__manifest__.py
  sale_pricelist_from_commitment_date/i18n/sale_pricelist_from_commitment_date.pot
  sale_pricelist_from_commitment_date/models/__init__.py
  sale_pricelist_from_commitment_date/models/product_pricelist.py
  sale_pricelist_from_commitment_date/models/product_product.py
  sale_pricelist_from_commitment_date/models/sale_order.py
  sale_pricelist_from_commitment_date/models/sale_order_line.py
  sale_pricelist_from_commitment_date/readme/CONTRIBUTORS.rst
  sale_pricelist_from_commitment_date/readme/DESCRIPTION.rst
  sale_pricelist_from_commitment_date/static/description/icon.png
  sale_pricelist_from_commitment_date/static/description/index.html
  sale_pricelist_from_commitment_date/tests/__init__.py
  sale_pricelist_from_commitment_date/tests/test_pricelist_from_commitment_date.py
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_pricelist_from_commitment_date/odoo/addons/sale_pricelist_from_commitment_date
  setup/sale_pricelist_from_commitment_date/setup.py
Labels: 14.0

#738 Syncing from upstream OCA/sale-workflow (12.0)
  README.md
  pricelist_by_category_qty/README.rst
  pricelist_by_category_qty/__init__.py
  pricelist_by_category_qty/__manifest__.py
  pricelist_by_category_qty/i18n/fr.po
  pricelist_by_category_qty/i18n/pricelist_by_category_qty.pot
  pricelist_by_category_qty/models/__init__.py
  pricelist_by_category_qty/models/sale.py
  pricelist_by_category_qty/readme/CONTRIBUTORS.rst
  pricelist_by_category_qty/readme/DESCRIPTION.rst
  pricelist_by_category_qty/readme/ROADMAP.rst
  pricelist_by_category_qty/static/description/icon.png
  pricelist_by_category_qty/static/description/index.html
  pricelist_by_category_qty/views/sale_view.xml
  sale_invoice_plan/README.rst
  sale_invoice_plan/__manifest__.py
  sale_invoice_plan/i18n/fr.po
  sale_invoice_plan/i18n/it.po
  sale_invoice_plan/i18n/nl_NL.po
  sale_invoice_plan/i18n/sale_invoice_plan.pot
  sale_invoice_plan/i18n/zh_CN.po
  sale_invoice_plan/models/sale.py
  sale_invoice_plan/readme/HISTORY.rst
  sale_invoice_plan/static/description/index.html
  sale_invoice_plan/views/sale_view.xml
  sale_order_general_discount/README.rst
  sale_order_general_discount/__manifest__.py
  sale_order_general_discount/models/res_partner.py
  sale_order_general_discount/readme/CONTRIBUTORS.rst
  sale_order_general_discount/static/description/index.html
  sale_start_end_dates/i18n/ca.po
  sale_start_end_dates/i18n/de.po
  sale_start_end_dates/i18n/el_GR.po
  sale_start_end_dates/i18n/es.po
  sale_start_end_dates/i18n/es_ES.po
  sale_start_end_dates/i18n/es_VE.po
  sale_start_end_dates/i18n/fi.po
  sale_start_end_dates/i18n/fr.po
  sale_start_end_dates/i18n/hr.po
  sale_start_end_dates/i18n/hr_HR.po
  sale_start_end_dates/i18n/hu.po
  sale_start_end_dates/i18n/it.po
  sale_start_end_dates/i18n/nl.po
  sale_start_end_dates/i18n/nl_NL.po
  sale_start_end_dates/i18n/pt.po
  sale_start_end_dates/i18n/pt_BR.po
  sale_start_end_dates/i18n/ro.po
  sale_start_end_dates/i18n/sk.po
  sale_start_end_dates/i18n/sl.po
  sale_start_end_dates/i18n/tr.po
  sale_start_end_dates/i18n/tr_TR.po
  sale_start_end_dates/i18n/vi_VN.po
  sale_start_end_dates/i18n/zh_CN.po
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/pricelist_by_category_qty/odoo/addons/pricelist_by_category_qty
  setup/pricelist_by_category_qty/setup.py
Labels: 12.0

#741 Syncing from upstream OCA/sale-workflow (13.0)
  README.md
  sale_exception/__manifest__.py
  sale_exception/models/sale.py
Labels: 13.0

#742 Syncing from upstream OCA/sale-workflow (14.0)
  README.md
  sale_commitment_date_mandatory/README.rst
  sale_commitment_date_mandatory/__init__.py
  sale_commitment_date_mandatory/__manifest__.py
  sale_commitment_date_mandatory/i18n/sale_commitment_date_mandatory.pot
  sale_commitment_date_mandatory/models/__init__.py
  sale_commitment_date_mandatory/models/sale_order.py
  sale_commitment_date_mandatory/readme/CONTRIBUTORS.rst
  sale_commitment_date_mandatory/readme/DESCRIPTION.rst
  sale_commitment_date_mandatory/static/description/icon.png
  sale_commitment_date_mandatory/static/description/index.html
  sale_commitment_date_mandatory/views/sale_views.xml
  sale_order_line_description/README.rst
  sale_order_line_description/__init__.py
  sale_order_line_description/__manifest__.py
  sale_order_line_description/i18n/ca.po
  sale_order_line_description/i18n/de.po
  sale_order_line_description/i18n/en.po
  sale_order_line_description/i18n/es.po
  sale_order_line_description/i18n/es_VE.po
  sale_order_line_description/i18n/fr.po
  sale_order_line_description/i18n/hr.po
  sale_order_line_description/i18n/it.po
  sale_order_line_description/i18n/nl_NL.po
  sale_order_line_description/i18n/pt_BR.po
  sale_order_line_description/i18n/ro.po
  sale_order_line_description/i18n/sale_order_line_description.pot
  sale_order_line_description/i18n/sl.po
  sale_order_line_description/i18n/tr.po
  sale_order_line_description/i18n/tr_TR.po
  sale_order_line_description/i18n/zh_CN.po
  sale_order_line_description/models/__init__.py
  sale_order_line_description/models/res_config_settings.py
  sale_order_line_description/models/sale_order_line.py
  sale_order_line_description/readme/CONFIGURE.rst
  sale_order_line_description/readme/CONTRIBUTORS.rst
  sale_order_line_description/readme/DESCRIPTION.rst
  sale_order_line_description/readme/USAGE.rst
  sale_order_line_description/security/sale_security.xml
  sale_order_line_description/static/description/icon.png
  sale_order_line_description/static/description/index.html
  sale_order_line_description/tests/__init__.py
  sale_order_line_description/tests/test_sale.py
  sale_order_line_description/views/res_config_settings_views.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_commitment_date_mandatory/odoo/addons/sale_commitment_date_mandatory
  setup/sale_commitment_date_mandatory/setup.py
  setup/sale_order_line_description/odoo/addons/sale_order_line_description
  setup/sale_order_line_description/setup.py
Labels: 14.0

#743 Syncing from upstream OCA/sale-workflow (13.0)
  README.md
  sale_order_product_recommendation/README.rst
  sale_order_product_recommendation/__manifest__.py
  sale_order_product_recommendation/i18n/es.po
  sale_order_product_recommendation/i18n/sale_order_product_recommendation.pot
  sale_order_product_recommendation/models/res_config_settings.py
  sale_order_product_recommendation/readme/CONFIGURE.rst
  sale_order_product_recommendation/readme/CONTRIBUTORS.rst
  sale_order_product_recommendation/static/description/index.html
  sale_order_product_recommendation/tests/test_recommendation.py
  sale_order_product_recommendation/tests/test_recommendation_common.py
  sale_order_product_recommendation/views/res_config_settings_views.xml
  sale_order_product_recommendation/wizards/sale_order_recommendation.py
  sale_order_product_recommendation/wizards/sale_order_recommendation_view.xml
Labels: 13.0

#744 Syncing from upstream OCA/sale-workflow (12.0)
  README.md
  oca_dependencies.txt
  sale_substate/README.rst
  sale_substate/__init__.py
  sale_substate/__manifest__.py
  sale_substate/data/sale_substate_data.xml
  sale_substate/data/sale_substate_demo.xml
  sale_substate/data/sale_substate_mail_template_data.xml
  sale_substate/i18n/sale_substate.pot
  sale_substate/models/__init__.py
  sale_substate/models/sale_order.py
  sale_substate/readme/CONTRIBUTORS.rst
  sale_substate/readme/DESCRIPTION.rst
  sale_substate/readme/USAGE.rst
  sale_substate/static/description/icon.png
  sale_substate/static/description/index.html
  sale_substate/tests/__init__.py
  sale_substate/tests/test_sale_substate.py
  sale_substate/views/sale_views.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_substate/odoo/addons/sale_substate
  setup/sale_substate/setup.py
Labels: 12.0

#745 Syncing from upstream OCA/sale-workflow (14.0)
  README.md
  sale_order_note_template/README.rst
  sale_order_note_template/__init__.py
  sale_order_note_template/__manifest__.py
  sale_order_note_template/i18n/sale_order_note_template.pot
  sale_order_note_template/models/__init__.py
  sale_order_note_template/models/sale_order.py
  sale_order_note_template/models/sale_terms_template.py
  sale_order_note_template/readme/CONTRIBUTOR.rst
  sale_order_note_template/readme/DESCRIPTION.rst
  sale_order_note_template/readme/ROADMAP.rst
  sale_order_note_template/security/ir.model.access.csv
  sale_order_note_template/static/description/icon.png
  sale_order_note_template/static/description/index.html
  sale_order_note_template/tests/__init__.py
  sale_order_note_template/tests/test_sale_order.py
  sale_order_note_template/tests/test_sale_terms_template.py
  sale_order_note_template/views/sale_terms_template.xml
  sale_order_note_template/views/sale_views.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_order_note_template/odoo/addons/sale_order_note_template
  setup/sale_order_note_template/setup.py
Labels: 14.0

#746 Syncing from upstream OCA/sale-workflow (14.0)
  .copier-answers.yml
  .flake8
  .isort.cfg
  .pre-commit-config.yaml
  sale_commercial_partner/i18n/fr.po
  sale_force_invoiced/i18n/fr.po
  sale_last_price_info/i18n/fr.po
  sale_partner_incoterm/i18n/fr.po
  sale_product_category_menu/i18n/fr.po
  sale_product_set/i18n/fr.po
  sale_shipping_info_helper/i18n/fr.po
Labels: 14.0

#747 Syncing from upstream OCA/sale-workflow (14.0)
  README.md
  sale_validity/__manifest__.py
  sale_validity/models/sale_order.py
Labels: 14.0

#748 Syncing from upstream OCA/sale-workflow (13.0)
  README.md
  sale_order_product_recommendation/__manifest__.py
  sale_order_product_recommendation/i18n/es.po
  sale_order_product_recommendation/i18n/sale_order_product_recommendation.pot
  sale_order_product_recommendation/views/res_config_settings_views.xml
  sale_order_product_recommendation/wizards/sale_order_recommendation.py
Labels: 13.0

#749 Syncing from upstream OCA/sale-workflow (14.0)
  README.md
  sale_advance_payment/README.rst
  sale_advance_payment/__init__.py
  sale_advance_payment/__manifest__.py
  sale_advance_payment/i18n/sale_advance_payment.pot
  sale_advance_payment/models/__init__.py
  sale_advance_payment/models/payment.py
  sale_advance_payment/models/sale.py
  sale_advance_payment/readme/CONTRIBUTORS.rst
  sale_advance_payment/readme/DESCRIPTION.rst
  sale_advance_payment/readme/ROADMAP.rst
  sale_advance_payment/readme/USAGE.rst
  sale_advance_payment/security/ir.model.access.csv
  sale_advance_payment/static/description/icon.png
  sale_advance_payment/static/description/index.html
  sale_advance_payment/tests/__init__.py
  sale_advance_payment/tests/test_sale_advance_payment.py
  sale_advance_payment/views/sale_view.xml
  sale_advance_payment/wizard/__init__.py
  sale_advance_payment/wizard/sale_advance_payment_wzd.py
  sale_advance_payment/wizard/sale_advance_payment_wzd_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_advance_payment/odoo/addons/sale_advance_payment
  setup/sale_advance_payment/setup.py
Labels: 14.0

#750 Syncing from upstream OCA/sale-workflow (12.0)
  sale_blanket_order/i18n/fr_FR.po
Labels: 12.0

#751 Syncing from upstream OCA/sale-workflow (12.0)
  sale_order_line_date/i18n/it.po
Labels: 12.0

#754 Syncing from upstream OCA/sale-workflow (13.0)
  README.md
  sale_order_qty_change_no_recompute/__manifest__.py
  sale_order_qty_change_no_recompute/tests/test_sale_order_qty_change.py
Labels: 13.0

#755 Syncing from upstream OCA/sale-workflow (14.0)
  README.md
  sale_order_qty_change_no_recompute/README.rst
  sale_order_qty_change_no_recompute/__init__.py
  sale_order_qty_change_no_recompute/__manifest__.py
  sale_order_qty_change_no_recompute/i18n/sale_order_qty_change_no_recompute.pot
  sale_order_qty_change_no_recompute/models/__init__.py
  sale_order_qty_change_no_recompute/models/sale_order.py
  sale_order_qty_change_no_recompute/readme/CONTRIBUTORS.rst
  sale_order_qty_change_no_recompute/readme/DESCRIPTION.rst
  sale_order_qty_change_no_recompute/readme/USAGE.rst
  sale_order_qty_change_no_recompute/static/description/icon.png
  sale_order_qty_change_no_recompute/static/description/index.html
  sale_order_qty_change_no_recompute/tests/__init__.py
  sale_order_qty_change_no_recompute/tests/test_sale_order_qty_change.py
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_order_qty_change_no_recompute/odoo/addons/sale_order_qty_change_no_recompute
  setup/sale_order_qty_change_no_recompute/setup.py
Labels: 14.0

#756 Syncing from upstream OCA/sale-workflow (12.0)
  sale_order_archive/i18n/pt.po
Labels: 12.0

#757 Update 20210524 - sale-workflow - OCA 13.0
  README.md
  sale_order_line_price_history/README.rst
  sale_order_line_price_history/__init__.py
  sale_order_line_price_history/__manifest__.py
  sale_order_line_price_history/i18n/de.po
  sale_order_line_price_history/i18n/es.po
  sale_order_line_price_history/i18n/pt.po
  sale_order_line_price_history/i18n/sale_order_line_price_history.pot
  sale_order_line_price_history/i18n/zh_CN.po
  sale_order_line_price_history/models/__init__.py
  sale_order_line_price_history/models/sale_order_line.py
  sale_order_line_price_history/readme/CONTRIBUTORS.rst
  sale_order_line_price_history/readme/ROADMAP.rst
  sale_order_line_price_history/static/description/icon.png
  sale_order_line_price_history/static/description/index.html
  sale_order_line_price_history/static/src/js/sale_line_price_history_widget.js
  sale_order_line_price_history/static/src/xml/sale_line_price_history_widget.xml
  sale_order_line_price_history/views/assets.xml
  sale_order_line_price_history/views/sale_views.xml
  sale_order_line_price_history/wizards/sale_order_line_price_history.py
  sale_order_line_price_history/wizards/sale_order_line_price_history.xml
  sale_order_product_recommendation/README.rst
  sale_order_product_recommendation/__manifest__.py
  sale_order_product_recommendation/i18n/es.po
  sale_order_product_recommendation/i18n/sale_order_product_recommendation.pot
  sale_order_product_recommendation/models/res_config_settings.py
  sale_order_product_recommendation/readme/CONFIGURE.rst
  sale_order_product_recommendation/readme/CONTRIBUTORS.rst
  sale_order_product_recommendation/static/description/index.html
  sale_order_product_recommendation/tests/test_recommendation.py
  sale_order_product_recommendation/tests/test_recommendation_common.py
  sale_order_product_recommendation/views/res_config_settings_views.xml
  sale_order_product_recommendation/wizards/sale_order_recommendation.py
  sale_order_product_recommendation/wizards/sale_order_recommendation_view.xml
  sale_order_qty_change_no_recompute/README.rst
  sale_order_qty_change_no_recompute/__init__.py
  sale_order_qty_change_no_recompute/__manifest__.py
  sale_order_qty_change_no_recompute/i18n/sale_order_qty_change_no_recompute.pot
  sale_order_qty_change_no_recompute/models/__init__.py
  sale_order_qty_change_no_recompute/models/sale_order.py
  sale_order_qty_change_no_recompute/readme/CONTRIBUTORS.rst
  sale_order_qty_change_no_recompute/readme/DESCRIPTION.rst
  sale_order_qty_change_no_recompute/readme/USAGE.rst
  sale_order_qty_change_no_recompute/static/description/icon.png
  sale_order_qty_change_no_recompute/static/description/index.html
  sale_order_qty_change_no_recompute/tests/__init__.py
  sale_order_qty_change_no_recompute/tests/test_sale_order_qty_change.py
  sale_order_warn_message/__manifest__.py
  sale_order_warn_message/models/sale_order.py
  sale_order_warn_message/tests/test_sale_order_warn_message.py
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_order_qty_change_no_recompute/odoo/addons/sale_order_qty_change_no_recompute
  setup/sale_order_qty_change_no_recompute/setup.py
Labels: 13.0.project_mi_465

#758 Syncing from upstream OCA/sale-workflow (13.0)
  README.md
  sale_product_set/__manifest__.py
  sale_product_set/wizard/product_set_add.py
Labels: 13.0

#759 Syncing from upstream OCA/sale-workflow (14.0)
  README.md
  sale_exception/i18n/es.po
  sale_invoice_blocking/README.rst
  sale_invoice_blocking/__init__.py
  sale_invoice_blocking/__manifest__.py
  sale_invoice_blocking/i18n/fr.po
  sale_invoice_blocking/i18n/sale_invoice_blocking.pot
  sale_invoice_blocking/models/__init__.py
  sale_invoice_blocking/models/invoice_blocking_reason.py
  sale_invoice_blocking/models/sale_order.py
  sale_invoice_blocking/readme/CONFIGURE.rst
  sale_invoice_blocking/readme/CONTRIBUTORS.rst
  sale_invoice_blocking/readme/DESCRIPTION.rst
  sale_invoice_blocking/readme/USAGE.rst
  sale_invoice_blocking/security/ir.model.access.csv
  sale_invoice_blocking/static/description/icon.png
  sale_invoice_blocking/static/description/index.html
  sale_invoice_blocking/views/menus.xml
  sale_invoice_blocking/views/sale_invoice_blocking_reason_view.xml
  sale_invoice_blocking/views/sale_order.xml
  sale_mrp_bom/README.rst
  sale_mrp_bom/__init__.py
  sale_mrp_bom/__manifest__.py
  sale_mrp_bom/i18n/sale_mrp_bom.pot
  sale_mrp_bom/models/__init__.py
  sale_mrp_bom/models/sale_order_line.py
  sale_mrp_bom/models/stock_move.py
  sale_mrp_bom/readme/CONFIGURE.rst
  sale_mrp_bom/readme/CONTRIBUTORS.rst
  sale_mrp_bom/readme/CREDITS.rst
  sale_mrp_bom/readme/DESCRIPTION.rst
  sale_mrp_bom/readme/INSTALL.rst
  sale_mrp_bom/readme/ROADMAP.rst
  sale_mrp_bom/readme/USAGE.rst
  sale_mrp_bom/security/security.xml
  sale_mrp_bom/static/description/icon.png
  sale_mrp_bom/static/description/index.html
  sale_mrp_bom/static/description/manufacturing_order_1.png
  sale_mrp_bom/static/description/sale_order_1.png
  sale_mrp_bom/tests/__init__.py
  sale_mrp_bom/tests/test_sale_mrp_bom.py
  sale_mrp_bom/views/sale_order.xml
  sale_mrp_bom/views/sale_order_line.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_invoice_blocking/odoo/addons/sale_invoice_blocking
  setup/sale_invoice_blocking/setup.py
  setup/sale_mrp_bom/odoo/addons/sale_mrp_bom
  setup/sale_mrp_bom/setup.py
Labels: 14.0

#760 Syncing from upstream OCA/sale-workflow (13.0)
  README.md
  sale_manual_delivery/__manifest__.py
  sale_manual_delivery/views/sale_order.xml
Labels: 13.0

#761 Syncing from upstream OCA/sale-workflow (14.0)
  README.md
  sale_product_seasonality/README.rst
  sale_product_seasonality/__init__.py
  sale_product_seasonality/__manifest__.py
  sale_product_seasonality/i18n/fr.po
  sale_product_seasonality/i18n/sale_product_seasonality.pot
  sale_product_seasonality/models/__init__.py
  sale_product_seasonality/models/sale_order.py
  sale_product_seasonality/models/sale_order_line.py
  sale_product_seasonality/readme/CONFIGURE.rst
  sale_product_seasonality/readme/CONTRIBUTORS.rst
  sale_product_seasonality/readme/DESCRIPTION.rst
  sale_product_seasonality/readme/ROADMAP.rst
  sale_product_seasonality/static/description/icon.png
  sale_product_seasonality/static/description/index.html
  sale_product_seasonality/tests/__init__.py
  sale_product_seasonality/tests/common.py
  sale_product_seasonality/tests/test_sale_order.py
  sale_product_seasonality/utils.py
  sale_product_seasonality/views/menu.xml
  sale_product_seasonality/views/sale_order.xml
  sale_product_set_packaging_qty/README.rst
  sale_product_set_packaging_qty/__init__.py
  sale_product_set_packaging_qty/__manifest__.py
  sale_product_set_packaging_qty/i18n/es.po
  sale_product_set_packaging_qty/i18n/sale_product_set_packaging_qty.pot
  sale_product_set_packaging_qty/models/__init__.py
  sale_product_set_packaging_qty/models/product_set.py
  sale_product_set_packaging_qty/readme/CONTRIBUTORS.rst
  sale_product_set_packaging_qty/readme/CREDITS.rst
  sale_product_set_packaging_qty/readme/DESCRIPTION.rst
  sale_product_set_packaging_qty/static/description/icon.png
  sale_product_set_packaging_qty/static/description/index.html
  sale_product_set_packaging_qty/tests/__init__.py
  sale_product_set_packaging_qty/tests/test_product_set_packaging.py
  sale_product_set_packaging_qty/views/product_set.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_product_seasonality/odoo/addons/sale_product_seasonality
  setup/sale_product_seasonality/setup.py
  setup/sale_product_set_packaging_qty/odoo/addons/sale_product_set_packaging_qty
  setup/sale_product_set_packaging_qty/setup.py
Labels: 14.0

#762 Syncing from upstream OCA/sale-workflow (12.0)
  sale_order_line_sequence/i18n/it.po
Labels: 12.0
