Repository brain-tec/sale-workflow, pull requests merged in 2021-02, with the labels that each got.

#680 Travis bugfixes for pre-commit
  sale_order_lot_selection/models/sale_order.py
  sale_order_lot_selection/models/stock.py
Labels: 13.0.project_mi_465

#682 Syncing from upstream OCA/sale-workflow (14.0)
  sale_order_archive/i18n/pt_BR.po
  sale_product_set/i18n/pt_BR.po
  sale_quotation_number/i18n/pt_BR.po
  sale_validity/i18n/pt_BR.po
Labels: 14.0

#683 Syncing from upstream OCA/sale-workflow (12.0)
  partner_prospect/i18n/pt.po
  sale_product_category_menu/i18n/pt.po
Labels: 12.0

#685 Syncing from upstream OCA/sale-workflow (10.0)
  product_price_category/i18n/it.po
  sale_force_invoiced/i18n/fr.po
Labels: 10.0

#688 Syncing from upstream OCA/sale-workflow (13.0)
  README.md
  sale_order_product_recommendation/README.rst
  sale_order_product_recommendation/__manifest__.py
  sale_order_product_recommendation/readme/CONTRIBUTORS.rst
  sale_order_product_recommendation/static/description/index.html
  sale_order_product_recommendation/tests/test_recommendation.py
  sale_order_product_recommendation/wizards/sale_order_recommendation.py
Labels: 13.0

#689 Syncing from upstream OCA/sale-workflow (14.0)
  sale_commercial_partner/i18n/ca.po
  sale_discount_display_amount/i18n/ca.po
  sale_order_lot_generator/i18n/ca.po
  sale_order_lot_generator/i18n/es.po
  sale_product_set/i18n/ca.po
  sale_product_set/i18n/es.po
Labels: 14.0

#690 Syncing from upstream OCA/sale-workflow (12.0)
  sale_blanket_order/i18n/it.po
Labels: 12.0
