Repository brain-tec/sale-workflow, pull requests merged in 2021-06, with the labels that each got.

#764 Syncing from upstream OCA/sale-workflow (13.0)
  sale_invoice_policy/i18n/es_MX.po
Labels: 13.0

#765 Syncing from upstream OCA/sale-workflow (12.0)
  README.md
  sale_order_action_invoice_create_hook/__manifest__.py
  sale_order_action_invoice_create_hook/i18n/sale_order_action_invoice_create_hook.pot
  sale_order_action_invoice_create_hook/model/sale_order.py
Labels: 12.0

#766 Updating from latest OCA 13.0
  README.md
  sale_invoice_policy/i18n/es_MX.po
  sale_manual_delivery/__manifest__.py
  sale_manual_delivery/views/sale_order.xml
  sale_product_set/__manifest__.py
  sale_product_set/wizard/product_set_add.py
Labels: 13.0.project_mi_465

#767 Merging from latest OCA 12.0
  README.md
  sale_order_action_invoice_create_hook/__manifest__.py
  sale_order_action_invoice_create_hook/i18n/sale_order_action_invoice_create_hook.pot
  sale_order_action_invoice_create_hook/model/sale_order.py
Labels: 12.0.project_mi_465

#768 Syncing from upstream OCA/sale-workflow (12.0)
  sale_order_action_invoice_create_hook/i18n/ca.po
  sale_order_action_invoice_create_hook/i18n/ca_ES.po
  sale_order_action_invoice_create_hook/i18n/de.po
  sale_order_action_invoice_create_hook/i18n/el_GR.po
  sale_order_action_invoice_create_hook/i18n/es.po
  sale_order_action_invoice_create_hook/i18n/es_VE.po
  sale_order_action_invoice_create_hook/i18n/fi.po
  sale_order_action_invoice_create_hook/i18n/fr.po
  sale_order_action_invoice_create_hook/i18n/hr.po
  sale_order_action_invoice_create_hook/i18n/hu.po
  sale_order_action_invoice_create_hook/i18n/it.po
  sale_order_action_invoice_create_hook/i18n/nl.po
  sale_order_action_invoice_create_hook/i18n/pt_BR.po
  sale_order_action_invoice_create_hook/i18n/ro.po
  sale_order_action_invoice_create_hook/i18n/sl.po
  sale_order_action_invoice_create_hook/i18n/sl_SI.po
  sale_order_action_invoice_create_hook/i18n/tr.po
  sale_order_action_invoice_create_hook/i18n/vi_VN.po
  sale_order_action_invoice_create_hook/i18n/zh_CN.po
  sale_order_type/i18n/it.po
Labels: 12.0

#769 Syncing from upstream OCA/sale-workflow (12.0)
  sale_order_tag/i18n/fr.po
Labels: 12.0

#770 Syncing from upstream OCA/sale-workflow (14.0)
  README.md
  sale_product_seasonality/__manifest__.py
  sale_product_seasonality/views/sale_order.xml
Labels: 14.0

#771 Syncing from upstream OCA/sale-workflow (12.0)
  README.md
  sale_promotion_rule/README.rst
  sale_promotion_rule/__init__.py
  sale_promotion_rule/__manifest__.py
  sale_promotion_rule/demo/product.xml
  sale_promotion_rule/i18n/ca.po
  sale_promotion_rule/i18n/fr.po
  sale_promotion_rule/i18n/sale_promotion_rule.pot
  sale_promotion_rule/models/__init__.py
  sale_promotion_rule/models/sale_order.py
  sale_promotion_rule/models/sale_order_line.py
  sale_promotion_rule/models/sale_promotion_rule.py
  sale_promotion_rule/readme/CONTRIBUTORS.rst
  sale_promotion_rule/readme/DESCRIPTION.rst
  sale_promotion_rule/readme/ROADMAP.rst
  sale_promotion_rule/security/ir.model.access.csv
  sale_promotion_rule/static/description/icon.png
  sale_promotion_rule/static/description/index.html
  sale_promotion_rule/static/description/promotion_rule.png
  sale_promotion_rule/tests/__init__.py
  sale_promotion_rule/tests/test_promotion.py
  sale_promotion_rule/views/sale_order.xml
  sale_promotion_rule/views/sale_promotion_rule.xml
  sale_promotion_rule/wizards/__init__.py
  sale_promotion_rule/wizards/sale_order_add_coupon.py
  sale_promotion_rule/wizards/sale_order_add_coupon.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_promotion_rule/odoo/addons/sale_promotion_rule
  setup/sale_promotion_rule/setup.py
Labels: 12.0

#772 Syncing from upstream OCA/sale-workflow (13.0)
  sale_order_product_recommendation/wizards/sale_order_recommendation.py
Labels: 13.0

#774 Backmerge from 12.0 into 12.0.project_MI_465
  README.md
  sale_order_action_invoice_create_hook/i18n/ca.po
  sale_order_action_invoice_create_hook/i18n/ca_ES.po
  sale_order_action_invoice_create_hook/i18n/de.po
  sale_order_action_invoice_create_hook/i18n/el_GR.po
  sale_order_action_invoice_create_hook/i18n/es.po
  sale_order_action_invoice_create_hook/i18n/es_VE.po
  sale_order_action_invoice_create_hook/i18n/fi.po
  sale_order_action_invoice_create_hook/i18n/fr.po
  sale_order_action_invoice_create_hook/i18n/hr.po
  sale_order_action_invoice_create_hook/i18n/hu.po
  sale_order_action_invoice_create_hook/i18n/it.po
  sale_order_action_invoice_create_hook/i18n/nl.po
  sale_order_action_invoice_create_hook/i18n/pt_BR.po
  sale_order_action_invoice_create_hook/i18n/ro.po
  sale_order_action_invoice_create_hook/i18n/sl.po
  sale_order_action_invoice_create_hook/i18n/sl_SI.po
  sale_order_action_invoice_create_hook/i18n/tr.po
  sale_order_action_invoice_create_hook/i18n/vi_VN.po
  sale_order_action_invoice_create_hook/i18n/zh_CN.po
  sale_order_tag/i18n/fr.po
  sale_order_type/i18n/it.po
  sale_promotion_rule/README.rst
  sale_promotion_rule/__init__.py
  sale_promotion_rule/__manifest__.py
  sale_promotion_rule/demo/product.xml
  sale_promotion_rule/i18n/ca.po
  sale_promotion_rule/i18n/fr.po
  sale_promotion_rule/i18n/sale_promotion_rule.pot
  sale_promotion_rule/models/__init__.py
  sale_promotion_rule/models/sale_order.py
  sale_promotion_rule/models/sale_order_line.py
  sale_promotion_rule/models/sale_promotion_rule.py
  sale_promotion_rule/readme/CONTRIBUTORS.rst
  sale_promotion_rule/readme/DESCRIPTION.rst
  sale_promotion_rule/readme/ROADMAP.rst
  sale_promotion_rule/security/ir.model.access.csv
  sale_promotion_rule/static/description/icon.png
  sale_promotion_rule/static/description/index.html
  sale_promotion_rule/static/description/promotion_rule.png
  sale_promotion_rule/tests/__init__.py
  sale_promotion_rule/tests/test_promotion.py
  sale_promotion_rule/views/sale_order.xml
  sale_promotion_rule/views/sale_promotion_rule.xml
  sale_promotion_rule/wizards/__init__.py
  sale_promotion_rule/wizards/sale_order_add_coupon.py
  sale_promotion_rule/wizards/sale_order_add_coupon.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_promotion_rule/odoo/addons/sale_promotion_rule
  setup/sale_promotion_rule/setup.py
Labels: 12.0.project_mi_465

#773 Backmerge from 13.0 into 13.0.project_MI_465
  sale_order_product_recommendation/wizards/sale_order_recommendation.py
Labels: 13.0.project_mi_465

#775 Syncing from upstream OCA/sale-workflow (12.0)
  partner_contact_sale_info_propagation/i18n/fr.po
Labels: 12.0

#776 Syncing from upstream OCA/sale-workflow (13.0)
  README.md
  sale_order_disable_user_autosubscribe/README.rst
  sale_order_disable_user_autosubscribe/__init__.py
  sale_order_disable_user_autosubscribe/__manifest__.py
  sale_order_disable_user_autosubscribe/i18n/sale_order_disable_user_autosubscribe.pot
  sale_order_disable_user_autosubscribe/models/__init__.py
  sale_order_disable_user_autosubscribe/models/sale_order.py
  sale_order_disable_user_autosubscribe/readme/CONTRIBUTORS.rst
  sale_order_disable_user_autosubscribe/readme/DESCRIPTION.rst
  sale_order_disable_user_autosubscribe/readme/ROADMAP.rst
  sale_order_disable_user_autosubscribe/static/description/icon.png
  sale_order_disable_user_autosubscribe/static/description/index.html
  sale_procurement_group_by_line/__manifest__.py
  sale_procurement_group_by_line/model/sale.py
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_order_disable_user_autosubscribe/odoo/addons/sale_order_disable_user_autosubscribe
  setup/sale_order_disable_user_autosubscribe/setup.py
Labels: 13.0
