Repository brain-tec/sale-workflow, pull requests merged in 2021-09, with the labels that each got.

#829 Syncing from upstream OCA/sale-workflow (14.0)
  README.md
  sale_transaction_form_link/README.rst
  sale_transaction_form_link/__init__.py
  sale_transaction_form_link/__manifest__.py
  sale_transaction_form_link/demo/payment_transaction.xml
  sale_transaction_form_link/i18n/sale_transaction_form_link.pot
  sale_transaction_form_link/models/__init__.py
  sale_transaction_form_link/models/sale_order.py
  sale_transaction_form_link/readme/CONTRIBUTORS.rst
  sale_transaction_form_link/readme/DESCRIPTION.rst
  sale_transaction_form_link/readme/USAGE.rst
  sale_transaction_form_link/static/description/icon.png
  sale_transaction_form_link/static/description/index.html
  sale_transaction_form_link/views/sale_order.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_transaction_form_link/odoo/addons/sale_transaction_form_link
  setup/sale_transaction_form_link/setup.py
Labels: 14.0

#830 Syncing from upstream OCA/sale-workflow (12.0)
  README.md
  sale_order_line_date/__manifest__.py
Labels: 12.0

#831 Syncing from upstream OCA/sale-workflow (13.0)
  README.md
  sale_order_line_input/__manifest__.py
Labels: 13.0

#834 Syncing from upstream OCA/sale-workflow (13.0)
  sale_automatic_workflow/migrations/13.0.1.2.0/post-migration.py
Labels: 13.0

#835 Syncing from upstream OCA/sale-workflow (13.0)
  README.md
  sale_order_qty_change_no_recompute/__manifest__.py
  sale_order_qty_change_no_recompute/models/sale_order.py
  sale_order_qty_change_no_recompute/tests/test_sale_order_qty_change.py
Labels: 13.0

#836 Syncing from upstream OCA/sale-workflow (14.0)
  README.md
  sale_order_qty_change_no_recompute/__manifest__.py
  sale_order_qty_change_no_recompute/models/sale_order.py
  sale_order_qty_change_no_recompute/tests/test_sale_order_qty_change.py
Labels: 14.0

#837 Merging 12.0 into 12.0.project_MI_465
  README.md
  sale_order_line_date/__manifest__.py
Labels: 12.0.project_mi_465

#839 Syncing from upstream OCA/sale-workflow (12.0)
  sale_order_line_sequence/i18n/fr.po
  sale_quotation_number/i18n/fr.po
Labels: 12.0

#840 Syncing from upstream OCA/sale-workflow (14.0)
  README.md
  sale_order_general_discount/__manifest__.py
Labels: 14.0

#843 Syncing from upstream OCA/sale-workflow (13.0)
  README.md
  sale_automatic_workflow_delivery_state/__manifest__.py
  sale_delivery_state/__manifest__.py
Labels: 13.0

#844 Syncing from upstream OCA/sale-workflow (13.0)
  README.md
  sale_cutoff_time_delivery/__manifest__.py
  sale_cutoff_time_delivery/models/sale_order.py
  sale_partner_delivery_window/__manifest__.py
  sale_partner_delivery_window/models/sale_order_line.py
  sale_stock_picking_note/i18n/es.po
Labels: 13.0

#845 Syncing from upstream OCA/sale-workflow (14.0)
  sale_advance_payment/i18n/fr.po
Labels: 14.0

#846 Syncing from upstream OCA/sale-workflow (12.0)
  sale_automatic_workflow/i18n/tr.po
  sale_exception/i18n/tr.po
  sale_order_revision/i18n/tr.po
Labels: 12.0

#848 Syncing from upstream OCA/sale-workflow (12.0)
  sale_automatic_workflow/i18n/pt_PT.po
  sale_stock_picking_note/i18n/it.po
Labels: 12.0

#849 Syncing from upstream OCA/sale-workflow (14.0)
  .travis.yml
  README.md
  sale_partner_version/README.rst
  sale_partner_version/__init__.py
  sale_partner_version/__manifest__.py
  sale_partner_version/i18n/sale_partner_version.pot
  sale_partner_version/models/__init__.py
  sale_partner_version/models/sale.py
  sale_partner_version/readme/CONTRIBUTORS.rst
  sale_partner_version/readme/DESCRIPTION.rst
  sale_partner_version/static/description/icon.png
  sale_partner_version/static/description/index.html
  sale_partner_version/tests/__init__.py
  sale_partner_version/tests/test_sale_partner_version.py
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_partner_version/odoo/addons/sale_partner_version
  setup/sale_partner_version/setup.py
Labels: 14.0

#851 Syncing from upstream OCA/sale-workflow (14.0)
  README.md
  sale_automatic_workflow/__manifest__.py
  sale_automatic_workflow/models/automatic_workflow_job.py
Labels: 14.0
