Repository brain-tec/sale-workflow, pull requests merged in 2021-10, with the labels that each got.

#852 Syncing from upstream OCA/sale-workflow (12.0)
  sale_cancel_reason/i18n/tr.po
Labels: 12.0

#853 Syncing from upstream OCA/sale-workflow (13.0)
  README.md
  partner_contact_sale_info_propagation/README.rst
  partner_contact_sale_info_propagation/__init__.py
  partner_contact_sale_info_propagation/__manifest__.py
  partner_contact_sale_info_propagation/i18n/ca.po
  partner_contact_sale_info_propagation/i18n/de.po
  partner_contact_sale_info_propagation/i18n/es.po
  partner_contact_sale_info_propagation/i18n/fr.po
  partner_contact_sale_info_propagation/i18n/partner_contact_sale_info_propagation.pot
  partner_contact_sale_info_propagation/models/__init__.py
  partner_contact_sale_info_propagation/models/res_partner.py
  partner_contact_sale_info_propagation/readme/CONTRIBUTORS.rst
  partner_contact_sale_info_propagation/readme/DESCRIPTION.rst
  partner_contact_sale_info_propagation/readme/USAGE.rst
  partner_contact_sale_info_propagation/static/description/icon.png
  partner_contact_sale_info_propagation/static/description/index.html
  partner_contact_sale_info_propagation/tests/__init__.py
  partner_contact_sale_info_propagation/tests/test_partner_contact_sale_info_propagation.py
  partner_contact_sale_info_propagation/views/res_partner_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/partner_contact_sale_info_propagation/odoo/addons/partner_contact_sale_info_propagation
  setup/partner_contact_sale_info_propagation/setup.py
Labels: 13.0

#854 Syncing from upstream OCA/sale-workflow (14.0)
  README.md
  sale_automatic_workflow/__manifest__.py
  sale_automatic_workflow/models/sale_order.py
Labels: 14.0

#856 Merging 12.0 into 12.0.project_MI_465
  sale_automatic_workflow/i18n/pt_PT.po
  sale_automatic_workflow/i18n/tr.po
  sale_cancel_reason/i18n/tr.po
  sale_exception/i18n/tr.po
  sale_order_line_sequence/i18n/fr.po
  sale_order_revision/i18n/tr.po
  sale_quotation_number/i18n/fr.po
  sale_stock_picking_note/i18n/it.po
Labels: 12.0.project_mi_465

#857 Syncing from upstream OCA/sale-workflow (12.0)
  sale_restricted_qty/i18n/it.po
Labels: 12.0

#858 Syncing from upstream OCA/sale-workflow (12.0)
  README.md
  oca_dependencies.txt
  sale_resource_booking/README.rst
  sale_resource_booking/__init__.py
  sale_resource_booking/__manifest__.py
  sale_resource_booking/i18n/es.po
  sale_resource_booking/i18n/sale_resource_booking.pot
  sale_resource_booking/models/__init__.py
  sale_resource_booking/models/product_template.py
  sale_resource_booking/models/resource_booking.py
  sale_resource_booking/models/resource_booking_type.py
  sale_resource_booking/models/sale_order.py
  sale_resource_booking/models/sale_order_line.py
  sale_resource_booking/readme/CONFIGURE.rst
  sale_resource_booking/readme/CONTRIBUTORS.rst
  sale_resource_booking/readme/DESCRIPTION.rst
  sale_resource_booking/readme/INSTALL.rst
  sale_resource_booking/readme/USAGE.rst
  sale_resource_booking/static/description/icon.png
  sale_resource_booking/static/description/index.html
  sale_resource_booking/tests/__init__.py
  sale_resource_booking/tests/test_sale_resource_booking.py
  sale_resource_booking/views/product_template_views.xml
  sale_resource_booking/views/resource_booking_type_views.xml
  sale_resource_booking/views/resource_booking_views.xml
  sale_resource_booking/views/sale_order_views.xml
  sale_resource_booking/wizards/__init__.py
  sale_resource_booking/wizards/resource_booking_sale.py
  sale_resource_booking/wizards/resource_booking_sale_views.xml
  sale_resource_booking/wizards/sale_order_booking_confirm.py
  sale_resource_booking/wizards/sale_order_booking_confirm_views.xml
  sale_restricted_qty/i18n/it.po
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_resource_booking/odoo/addons/sale_resource_booking
  setup/sale_resource_booking/setup.py
Labels: 12.0

#867 Syncing from upstream OCA/sale-workflow (12.0)
  README.md
  sale_product_classification/README.rst
  sale_product_classification/__init__.py
  sale_product_classification/__manifest__.py
  sale_product_classification/data/ir_cron.xml
  sale_product_classification/i18n/es.po
  sale_product_classification/i18n/sale_product_classification.pot
  sale_product_classification/models/__init__.py
  sale_product_classification/models/product_product.py
  sale_product_classification/models/product_template.py
  sale_product_classification/models/res_company.py
  sale_product_classification/models/res_config_settings.py
  sale_product_classification/readme/CONFIGURE.rst
  sale_product_classification/readme/CONTRIBUTORS.rst
  sale_product_classification/readme/DESCRIPTION.rst
  sale_product_classification/readme/ROADMAP.rst
  sale_product_classification/readme/USAGE.rst
  sale_product_classification/static/description/icon.png
  sale_product_classification/static/description/index.html
  sale_product_classification/tests/__init__.py
  sale_product_classification/tests/test_sale_product_classification.py
  sale_product_classification/tests/test_sale_product_classification_common.py
  sale_product_classification/views/product_template_views.xml
  sale_product_classification/views/res_config_settings_views.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_product_classification/odoo/addons/sale_product_classification
  setup/sale_product_classification/setup.py
Labels: 12.0

#870 Syncing from upstream OCA/sale-workflow (9.0)
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
Labels: 9.0

#871 Syncing from upstream OCA/sale-workflow (10.0)
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
Labels: 10.0

#872 Syncing from upstream OCA/sale-workflow (11.0)
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
Labels: 11.0

#873 Syncing from upstream OCA/sale-workflow (12.0)
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
Labels: 12.0

#874 Syncing from upstream OCA/sale-workflow (13.0)
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
Labels: 13.0

#875 Syncing from upstream OCA/sale-workflow (14.0)
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
Labels: 14.0

#878 Syncing from upstream OCA/sale-workflow (14.0)
  README.md
  sale_product_set_sale_by_packaging/README.rst
  sale_product_set_sale_by_packaging/__init__.py
  sale_product_set_sale_by_packaging/__manifest__.py
  sale_product_set_sale_by_packaging/data/ir_cron.xml
  sale_product_set_sale_by_packaging/i18n/sale_product_set_sale_by_packaging.pot
  sale_product_set_sale_by_packaging/models/__init__.py
  sale_product_set_sale_by_packaging/models/product_product.py
  sale_product_set_sale_by_packaging/models/product_set_line.py
  sale_product_set_sale_by_packaging/models/product_template.py
  sale_product_set_sale_by_packaging/readme/CONTRIBUTORS.rst
  sale_product_set_sale_by_packaging/readme/CREDITS.rst
  sale_product_set_sale_by_packaging/readme/DESCRIPTION.rst
  sale_product_set_sale_by_packaging/static/description/icon.png
  sale_product_set_sale_by_packaging/static/description/index.html
  sale_product_set_sale_by_packaging/tests/__init__.py
  sale_product_set_sale_by_packaging/tests/test_product_set_packaging.py
  sale_product_set_sale_by_packaging/views/product_set_line.xml
  sale_product_set_sale_by_packaging/views/product_template.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_product_set_sale_by_packaging/odoo/addons/sale_product_set_sale_by_packaging
  setup/sale_product_set_sale_by_packaging/setup.py
Labels: 14.0

#883 Syncing from upstream OCA/sale-workflow (13.0)
  README.md
  sale_by_packaging/__manifest__.py
  sale_by_packaging/models/sale_order_line.py
  sale_by_packaging/tests/__init__.py
  sale_by_packaging/tests/common.py
  sale_by_packaging/tests/test_packaging_type_can_be_sold.py
  sale_by_packaging/tests/test_sale_line_onchanges.py
  sale_by_packaging/tests/test_sale_only_by_packaging.py
  sale_cutoff_time_delivery/__manifest__.py
  sale_cutoff_time_delivery/models/sale_order.py
  sale_order_line_chained_move/README.rst
  sale_order_line_chained_move/__init__.py
  sale_order_line_chained_move/__manifest__.py
  sale_order_line_chained_move/demo/sale_order.xml
  sale_order_line_chained_move/hooks.py
  sale_order_line_chained_move/i18n/sale_order_line_chained_move.pot
  sale_order_line_chained_move/models/__init__.py
  sale_order_line_chained_move/models/sale_order_line.py
  sale_order_line_chained_move/models/stock_move.py
  sale_order_line_chained_move/models/stock_rule.py
  sale_order_line_chained_move/readme/CONTRIBUTORS.rst
  sale_order_line_chained_move/readme/DESCRIPTION.rst
  sale_order_line_chained_move/static/description/icon.png
  sale_order_line_chained_move/static/description/index.html
  sale_order_line_chained_move/tests/__init__.py
  sale_order_line_chained_move/tests/test_chained_move.py
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_order_line_chained_move/odoo/addons/sale_order_line_chained_move
  setup/sale_order_line_chained_move/setup.py
Labels: 13.0

#885 Syncing from upstream OCA/sale-workflow (15.0)
  README.md
  sale_commercial_partner/README.rst
  sale_commercial_partner/__init__.py
  sale_commercial_partner/__manifest__.py
  sale_commercial_partner/i18n/ca.po
  sale_commercial_partner/i18n/ca_ES.po
  sale_commercial_partner/i18n/de.po
  sale_commercial_partner/i18n/el_GR.po
  sale_commercial_partner/i18n/es.po
  sale_commercial_partner/i18n/es_VE.po
  sale_commercial_partner/i18n/fi.po
  sale_commercial_partner/i18n/fr.po
  sale_commercial_partner/i18n/fr_FR.po
  sale_commercial_partner/i18n/hr.po
  sale_commercial_partner/i18n/hu.po
  sale_commercial_partner/i18n/it.po
  sale_commercial_partner/i18n/nl.po
  sale_commercial_partner/i18n/pt_BR.po
  sale_commercial_partner/i18n/ro.po
  sale_commercial_partner/i18n/sale_commercial_partner.pot
  sale_commercial_partner/i18n/sl_SI.po
  sale_commercial_partner/i18n/tr.po
  sale_commercial_partner/i18n/vi_VN.po
  sale_commercial_partner/i18n/zh_CN.po
  sale_commercial_partner/models/__init__.py
  sale_commercial_partner/models/sale.py
  sale_commercial_partner/readme/CONTRIBUTORS.rst
  sale_commercial_partner/readme/DESCRIPTION.rst
  sale_commercial_partner/readme/USAGE.rst
  sale_commercial_partner/static/description/icon.png
  sale_commercial_partner/static/description/index.html
  sale_commercial_partner/views/sale_views.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_commercial_partner/odoo/addons/sale_commercial_partner
  setup/sale_commercial_partner/setup.py
Labels: 15.0
