Repository brain-tec/sale-workflow, pull requests merged in 2022-10, with the labels that each got.

#1175 Syncing from upstream OCA/sale-workflow (12.0)
  README.md
  sale_mrp_bom/__manifest__.py
  sale_mrp_bom/views/sale_order.xml
Labels: 12.0

#1176 Syncing from upstream OCA/sale-workflow (13.0)
  README.md
  sale_invoice_no_mail/README.rst
  sale_invoice_no_mail/__init__.py
  sale_invoice_no_mail/__manifest__.py
  sale_invoice_no_mail/i18n/sale_invoice_no_mail.pot
  sale_invoice_no_mail/readme/CONTRIBUTORS.rst
  sale_invoice_no_mail/readme/DESCRIPTION.rst
  sale_invoice_no_mail/readme/USAGE.rst
  sale_invoice_no_mail/static/description/icon.png
  sale_invoice_no_mail/static/description/index.html
  sale_invoice_no_mail/tests/__init__.py
  sale_invoice_no_mail/tests/test_sale_invoice_no_mail.py
  sale_invoice_no_mail/wizard/__init__.py
  sale_invoice_no_mail/wizard/sale_make_invoice_advance.py
  sale_manual_delivery/__manifest__.py
  sale_manual_delivery/wizard/manual_delivery.py
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_invoice_no_mail/odoo/addons/sale_invoice_no_mail
  setup/sale_invoice_no_mail/setup.py
Labels: 13.0

#1178 Syncing from upstream OCA/sale-workflow (15.0)
  README.md
  sale_invoice_no_mail/README.rst
  sale_invoice_no_mail/__init__.py
  sale_invoice_no_mail/__manifest__.py
  sale_invoice_no_mail/i18n/sale_invoice_no_mail.pot
  sale_invoice_no_mail/readme/CONTRIBUTORS.rst
  sale_invoice_no_mail/readme/DESCRIPTION.rst
  sale_invoice_no_mail/readme/USAGE.rst
  sale_invoice_no_mail/static/description/icon.png
  sale_invoice_no_mail/static/description/index.html
  sale_invoice_no_mail/tests/__init__.py
  sale_invoice_no_mail/tests/test_sale_invoice_no_mail.py
  sale_invoice_no_mail/wizard/__init__.py
  sale_invoice_no_mail/wizard/sale_make_invoice_advance.py
  sale_tier_validation/__manifest__.py
  sale_tier_validation/data/mail_data.xml
  sale_tier_validation/i18n/es.po
  sale_tier_validation/i18n/sale_tier_validation.pot
  sale_tier_validation/i18n/sv.po
  sale_tier_validation/i18n/zh_CN.po
  sale_tier_validation/models/sale_order.py
  sale_tier_validation/tests/test_tier_validation.py
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_invoice_no_mail/odoo/addons/sale_invoice_no_mail
  setup/sale_invoice_no_mail/setup.py
Labels: 15.0

#1179 Syncing from upstream OCA/sale-workflow (13.0)
  sale_invoice_plan/i18n/ca.po
  sale_invoice_plan/i18n/ca_ES.po
Labels: 13.0

#1180 Syncing from upstream OCA/sale-workflow (14.0)
  README.md
  sale_order_line_packaging_qty/__manifest__.py
  sale_order_line_packaging_qty/models/sale_order_line.py
  sale_order_line_packaging_qty/tests/test_sale_order_line_packaging_qty.py
Labels: 14.0

#1182 Syncing from upstream OCA/sale-workflow (12.0)
  sale_product_set/i18n/ca.po
Labels: 12.0

#1183 Syncing from upstream OCA/sale-workflow (13.0)
  .github/workflows/test.yml
  README.md
  sale_stock_sourcing_address/README.rst
  sale_stock_sourcing_address/__init__.py
  sale_stock_sourcing_address/__manifest__.py
  sale_stock_sourcing_address/i18n/ca.po
  sale_stock_sourcing_address/i18n/es.po
  sale_stock_sourcing_address/i18n/sale_stock_sourcing_address.pot
  sale_stock_sourcing_address/models/__init__.py
  sale_stock_sourcing_address/models/account_invoice_line.py
  sale_stock_sourcing_address/models/sale_order_line.py
  sale_stock_sourcing_address/readme/CONFIGURE.rst
  sale_stock_sourcing_address/readme/CONTRIBUTORS.rst
  sale_stock_sourcing_address/readme/DESCRIPTION.rst
  sale_stock_sourcing_address/security/security.xml
  sale_stock_sourcing_address/static/description/icon.png
  sale_stock_sourcing_address/static/description/index.html
  sale_stock_sourcing_address/tests/__init__.py
  sale_stock_sourcing_address/tests/test_sale_stock_sourcing_address.py
  sale_stock_sourcing_address/views/account_invoice_view.xml
  sale_stock_sourcing_address/views/sale_order_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_stock_sourcing_address/odoo/addons/sale_stock_sourcing_address
  setup/sale_stock_sourcing_address/setup.py
Labels: 13.0

#1184 Syncing from upstream OCA/sale-workflow (12.0)
  sale_invoice_plan/i18n/pt_BR.po
Labels: 12.0

#1185 Syncing from upstream OCA/sale-workflow (14.0)
  README.md
  sale_automatic_workflow_payment_mode/__manifest__.py
  sale_automatic_workflow_payment_mode/models/automatic_workflow_job.py
Labels: 14.0

#1186 Syncing from upstream OCA/sale-workflow (12.0)
  README.md
  sale_advance_payment/README.rst
  sale_advance_payment/__init__.py
  sale_advance_payment/__manifest__.py
  sale_advance_payment/i18n/es.po
  sale_advance_payment/i18n/fr.po
  sale_advance_payment/i18n/it.po
  sale_advance_payment/i18n/sale_advance_payment.pot
  sale_advance_payment/models/__init__.py
  sale_advance_payment/models/payment.py
  sale_advance_payment/models/sale.py
  sale_advance_payment/readme/CONTRIBUTORS.rst
  sale_advance_payment/readme/DESCRIPTION.rst
  sale_advance_payment/readme/ROADMAP.rst
  sale_advance_payment/readme/USAGE.rst
  sale_advance_payment/security/ir.model.access.csv
  sale_advance_payment/static/description/icon.png
  sale_advance_payment/static/description/index.html
  sale_advance_payment/tests/__init__.py
  sale_advance_payment/tests/test_sale_advance_payment.py
  sale_advance_payment/views/sale_view.xml
  sale_advance_payment/wizard/__init__.py
  sale_advance_payment/wizard/sale_advance_payment_wzd.py
  sale_advance_payment/wizard/sale_advance_payment_wzd_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_advance_payment/odoo/addons/sale_advance_payment
  setup/sale_advance_payment/setup.py
Labels: 12.0

#1187 Syncing from upstream OCA/sale-workflow (14.0)
  README.md
  sale_automatic_workflow/__manifest__.py
  sale_automatic_workflow/models/account_move.py
  sale_automatic_workflow/models/sale_order.py
  sale_automatic_workflow/models/stock_picking.py
  sale_automatic_workflow/tests/test_automatic_workflow.py
  sale_start_end_dates/i18n/es.po
Labels: 14.0

#1188 Syncing from upstream OCA/sale-workflow (13.0)
  README.md
  sales_team_security/__manifest__.py
  sales_team_security/models/res_partner.py
Labels: 13.0

#1190 Syncing from upstream OCA/sale-workflow (13.0)
  README.md
  sale_order_secondary_unit/__manifest__.py
  sale_order_secondary_unit/report/sale_report_templates.xml
Labels: 13.0

#1191 Syncing from upstream OCA/sale-workflow (14.0)
  README.md
  sale_order_secondary_unit/README.rst
  sale_order_secondary_unit/__init__.py
  sale_order_secondary_unit/__manifest__.py
  sale_order_secondary_unit/i18n/de.po
  sale_order_secondary_unit/i18n/es.po
  sale_order_secondary_unit/i18n/sale_order_secondary_unit.pot
  sale_order_secondary_unit/i18n/zh_CN.po
  sale_order_secondary_unit/models/__init__.py
  sale_order_secondary_unit/models/product_template.py
  sale_order_secondary_unit/models/sale_order.py
  sale_order_secondary_unit/readme/CONTRIBUTORS.rst
  sale_order_secondary_unit/readme/DESCRIPTION.rst
  sale_order_secondary_unit/readme/USAGE.rst
  sale_order_secondary_unit/report/sale_report_templates.xml
  sale_order_secondary_unit/static/description/icon.png
  sale_order_secondary_unit/static/description/index.html
  sale_order_secondary_unit/tests/__init__.py
  sale_order_secondary_unit/tests/test_sale_order_secondary_unit.py
  sale_order_secondary_unit/views/product_views.xml
  sale_order_secondary_unit/views/sale_order_views.xml
  sale_start_end_dates/i18n/es.po
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_order_secondary_unit/odoo/addons/sale_order_secondary_unit
  setup/sale_order_secondary_unit/setup.py
Labels: 14.0

#1192 Syncing from upstream OCA/sale-workflow (15.0)
  README.md
  sale_order_archive/README.rst
  sale_order_archive/__init__.py
  sale_order_archive/__manifest__.py
  sale_order_archive/i18n/ca.po
  sale_order_archive/i18n/de.po
  sale_order_archive/i18n/es.po
  sale_order_archive/i18n/nl.po
  sale_order_archive/i18n/pt_BR.po
  sale_order_archive/i18n/sale_order_archive.pot
  sale_order_archive/i18n/zh_CN.po
  sale_order_archive/models/__init__.py
  sale_order_archive/models/sale_order.py
  sale_order_archive/readme/CONTRIBUTORS.rst
  sale_order_archive/readme/DESCRIPTION.rst
  sale_order_archive/readme/INSTALL.rst
  sale_order_archive/readme/USAGE.rst
  sale_order_archive/static/description/icon.png
  sale_order_archive/static/description/index.html
  sale_order_archive/tests/__init__.py
  sale_order_archive/tests/test_sale_order_archive.py
  sale_order_archive/views/sale_order.xml
  sale_order_invoicing_finished_task/__manifest__.py
  sale_order_invoicing_finished_task/tests/test_sale_order_invoicing_finished_task.py
  sale_order_product_availability_inline/__manifest__.py
  sale_order_product_availability_inline/tests/test_sale_order_product_availability_inline.py
  sale_order_product_recommendation/__manifest__.py
  sale_order_product_recommendation/tests/test_recommendation_common.py
  sale_order_secondary_unit/__manifest__.py
  sale_order_secondary_unit/report/sale_report_templates.xml
  sale_partner_selectable_option/__manifest__.py
  sale_partner_selectable_option/tests/test_sale_partner_selectable_option.py
  sale_payment_sheet/__manifest__.py
  sale_payment_sheet/tests/test_sale_payment_sheet.py
  sale_stock_cancel_restriction/__manifest__.py
  sale_stock_cancel_restriction/tests/test_sale_stock_cancel_restriction.py
  sales_team_security/__manifest__.py
  sales_team_security/tests/common.py
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_order_archive/odoo/addons/sale_order_archive
  setup/sale_order_archive/setup.py
Labels: 15.0

#1193 Syncing from upstream OCA/sale-workflow (15.0)
  README.md
  sale_elaboration/README.rst
  sale_elaboration/__init__.py
  sale_elaboration/__manifest__.py
  sale_elaboration/i18n/de.po
  sale_elaboration/i18n/es.po
  sale_elaboration/i18n/sale_elaboration.pot
  sale_elaboration/models/__init__.py
  sale_elaboration/models/product.py
  sale_elaboration/models/product_elaboration.py
  sale_elaboration/models/res_config_settings.py
  sale_elaboration/models/sale_order.py
  sale_elaboration/models/stock_picking.py
  sale_elaboration/readme/CONFIGURE.rst
  sale_elaboration/readme/CONTRIBUTORS.rst
  sale_elaboration/readme/DESCRIPTION.rst
  sale_elaboration/readme/USAGE.rst
  sale_elaboration/reports/report_deliveryslip.xml
  sale_elaboration/security/ir.model.access.csv
  sale_elaboration/security/security.xml
  sale_elaboration/static/description/icon.png
  sale_elaboration/static/description/index.html
  sale_elaboration/tests/__init__.py
  sale_elaboration/tests/test_sale_elaboration.py
  sale_elaboration/views/product_views.xml
  sale_elaboration/views/res_config_settings_views.xml
  sale_elaboration/views/sale_elaboration_report_views.xml
  sale_elaboration/views/sale_elaboration_views.xml
  sale_elaboration/views/sale_order_views.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_elaboration/odoo/addons/sale_elaboration
  setup/sale_elaboration/setup.py
Labels: 15.0

#1194 [MIG]sale_triple_discount: Migration to 15.0
  sale_triple_discount/README.rst
  sale_triple_discount/__init__.py
  sale_triple_discount/__manifest__.py
  sale_triple_discount/i18n/ca.po
  sale_triple_discount/i18n/de.po
  sale_triple_discount/i18n/es.po
  sale_triple_discount/i18n/es_VE.po
  sale_triple_discount/i18n/fr.po
  sale_triple_discount/i18n/hr.po
  sale_triple_discount/i18n/it.po
  sale_triple_discount/i18n/nl_NL.po
  sale_triple_discount/i18n/pt_BR.po
  sale_triple_discount/i18n/ro.po
  sale_triple_discount/i18n/sale_triple_discount.pot
  sale_triple_discount/i18n/sl.po
  sale_triple_discount/i18n/tr.po
  sale_triple_discount/i18n/tr_TR.po
  sale_triple_discount/models/__init__.py
  sale_triple_discount/models/sale_order.py
  sale_triple_discount/models/sale_order_line.py
  sale_triple_discount/readme/CONFIGURE.rst
  sale_triple_discount/readme/CONTRIBUTORS.rst
  sale_triple_discount/readme/DESCRIPTION.rst
  sale_triple_discount/readme/USAGE.rst
  sale_triple_discount/static/description/icon.png
  sale_triple_discount/static/description/index.html
  sale_triple_discount/tests/__init__.py
  sale_triple_discount/tests/test_sale_triple_discount.py
  sale_triple_discount/views/sale_order_report.xml
  sale_triple_discount/views/sale_order_view.xml
  setup/sale_triple_discount/odoo/addons/sale_triple_discount
  setup/sale_triple_discount/setup.py
Labels: 15.0.project_pr_606

#1195 Syncing from upstream OCA/sale-workflow (14.0)
  README.md
  product_supplierinfo_for_customer_elaboration/README.rst
  product_supplierinfo_for_customer_elaboration/__init__.py
  product_supplierinfo_for_customer_elaboration/__manifest__.py
  product_supplierinfo_for_customer_elaboration/i18n/es.po
  product_supplierinfo_for_customer_elaboration/i18n/product_supplierinfo_for_customer_elaboration.pot
  product_supplierinfo_for_customer_elaboration/models/__init__.py
  product_supplierinfo_for_customer_elaboration/models/product_customerinfo.py
  product_supplierinfo_for_customer_elaboration/models/sale_order_line.py
  product_supplierinfo_for_customer_elaboration/readme/CONFIGURE.rst
  product_supplierinfo_for_customer_elaboration/readme/CONTRIBUTORS.rst
  product_supplierinfo_for_customer_elaboration/readme/DESCRIPTION.rst
  product_supplierinfo_for_customer_elaboration/readme/USAGE.rst
  product_supplierinfo_for_customer_elaboration/security/ir.model.access.csv
  product_supplierinfo_for_customer_elaboration/static/description/icon.png
  product_supplierinfo_for_customer_elaboration/static/description/index.html
  product_supplierinfo_for_customer_elaboration/tests/__init__.py
  product_supplierinfo_for_customer_elaboration/tests/test_customerinfo_elaboration.py
  product_supplierinfo_for_customer_elaboration/views/product_views.xml
  sale_triple_discount/i18n/fr.po
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/product_supplierinfo_for_customer_elaboration/odoo/addons/product_supplierinfo_for_customer_elaboration
  setup/product_supplierinfo_for_customer_elaboration/setup.py
Labels: 14.0

#1196 Syncing from upstream OCA/sale-workflow (15.0)
  README.md
  sale_triple_discount/README.rst
  sale_triple_discount/__init__.py
  sale_triple_discount/__manifest__.py
  sale_triple_discount/i18n/ca.po
  sale_triple_discount/i18n/de.po
  sale_triple_discount/i18n/es.po
  sale_triple_discount/i18n/es_VE.po
  sale_triple_discount/i18n/fr.po
  sale_triple_discount/i18n/hr.po
  sale_triple_discount/i18n/it.po
  sale_triple_discount/i18n/nl_NL.po
  sale_triple_discount/i18n/pt_BR.po
  sale_triple_discount/i18n/ro.po
  sale_triple_discount/i18n/sale_triple_discount.pot
  sale_triple_discount/i18n/sl.po
  sale_triple_discount/i18n/tr.po
  sale_triple_discount/i18n/tr_TR.po
  sale_triple_discount/models/__init__.py
  sale_triple_discount/models/sale_order.py
  sale_triple_discount/models/sale_order_line.py
  sale_triple_discount/readme/CONFIGURE.rst
  sale_triple_discount/readme/CONTRIBUTORS.rst
  sale_triple_discount/readme/DESCRIPTION.rst
  sale_triple_discount/readme/USAGE.rst
  sale_triple_discount/static/description/icon.png
  sale_triple_discount/static/description/index.html
  sale_triple_discount/tests/__init__.py
  sale_triple_discount/tests/test_sale_triple_discount.py
  sale_triple_discount/views/sale_order_report.xml
  sale_triple_discount/views/sale_order_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_triple_discount/odoo/addons/sale_triple_discount
  setup/sale_triple_discount/setup.py
Labels: 15.0

#1198 Syncing from upstream OCA/sale-workflow (14.0)
  README.md
  sale_order_tag/README.rst
  sale_order_tag/__init__.py
  sale_order_tag/__manifest__.py
  sale_order_tag/data/sale_order_tag_data.xml
  sale_order_tag/i18n/ca.po
  sale_order_tag/i18n/es.po
  sale_order_tag/i18n/it.po
  sale_order_tag/i18n/sale_order_tag.pot
  sale_order_tag/i18n/tr.po
  sale_order_tag/models/__init__.py
  sale_order_tag/models/sale_order.py
  sale_order_tag/models/sale_order_tag.py
  sale_order_tag/readme/CONTRIBUTORS.rst
  sale_order_tag/readme/DESCRIPTION.rst
  sale_order_tag/readme/USAGE.rst
  sale_order_tag/security/ir.model.access.csv
  sale_order_tag/security/sale_order_tag_security.xml
  sale_order_tag/static/description/icon.png
  sale_order_tag/static/description/index.html
  sale_order_tag/views/sale_order.xml
  sale_order_tag/views/sale_order_tag.xml
  sale_product_seasonality/__manifest__.py
  sale_product_seasonality/models/sale_order.py
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_order_tag/odoo/addons/sale_order_tag
  setup/sale_order_tag/setup.py
Labels: 14.0
