Repository brain-tec/sale-workflow, pull requests merged in 2022-06, with the labels that each got.

#1058 Syncing from upstream OCA/sale-workflow (13.0)
  sale_order_price_recalculation/i18n/es.po
Labels: 13.0

#1060 Syncing from upstream OCA/sale-workflow (13.0)
  README.md
  sale_order_price_recalculation/__manifest__.py
  sale_order_price_recalculation/i18n/ca.po
  sale_order_price_recalculation/i18n/de.po
  sale_order_price_recalculation/i18n/el_GR.po
  sale_order_price_recalculation/i18n/es.po
  sale_order_price_recalculation/i18n/es_ES.po
  sale_order_price_recalculation/i18n/es_VE.po
  sale_order_price_recalculation/i18n/fi.po
  sale_order_price_recalculation/i18n/fr.po
  sale_order_price_recalculation/i18n/hr.po
  sale_order_price_recalculation/i18n/hr_HR.po
  sale_order_price_recalculation/i18n/hu.po
  sale_order_price_recalculation/i18n/it.po
  sale_order_price_recalculation/i18n/nl.po
  sale_order_price_recalculation/i18n/nl_NL.po
  sale_order_price_recalculation/i18n/pt.po
  sale_order_price_recalculation/i18n/pt_BR.po
  sale_order_price_recalculation/i18n/ro.po
  sale_order_price_recalculation/i18n/sale_order_price_recalculation.pot
  sale_order_price_recalculation/i18n/sl.po
  sale_order_price_recalculation/i18n/tr.po
  sale_order_price_recalculation/i18n/tr_TR.po
  sale_order_price_recalculation/i18n/vi_VN.po
  sale_order_price_recalculation/i18n/zh_CN.po
  sale_order_price_recalculation/views/sale_order_view.xml
Labels: 13.0

#1061 Syncing from upstream OCA/sale-workflow (14.0)
  README.md
  sale_automatic_workflow/i18n/it.po
  sale_automatic_workflow_job/i18n/it.po
  sale_automatic_workflow_payment_mode/i18n/it.po
  sale_product_set/__manifest__.py
  sale_product_set/tests/test_product_set.py
  sale_product_set/wizard/product_set_add.py
Labels: 14.0

#1063 Syncing from upstream OCA/sale-workflow (15.0)
  README.md
  sale_discount_display_amount/README.rst
  sale_discount_display_amount/__init__.py
  sale_discount_display_amount/__manifest__.py
  sale_discount_display_amount/hooks.py
  sale_discount_display_amount/i18n/ca.po
  sale_discount_display_amount/i18n/de.po
  sale_discount_display_amount/i18n/es.po
  sale_discount_display_amount/i18n/es_ES.po
  sale_discount_display_amount/i18n/fr.po
  sale_discount_display_amount/i18n/it.po
  sale_discount_display_amount/i18n/nl.po
  sale_discount_display_amount/i18n/sale_discount_display_amount.pot
  sale_discount_display_amount/i18n/zh_CN.po
  sale_discount_display_amount/models/__init__.py
  sale_discount_display_amount/models/sale_order.py
  sale_discount_display_amount/models/sale_order_line.py
  sale_discount_display_amount/readme/CONFIGURE.rst
  sale_discount_display_amount/readme/CONTRIBUTORS.rst
  sale_discount_display_amount/readme/DESCRIPTION.rst
  sale_discount_display_amount/readme/USAGE.rst
  sale_discount_display_amount/static/description/icon.png
  sale_discount_display_amount/static/description/index.html
  sale_discount_display_amount/tests/__init__.py
  sale_discount_display_amount/tests/test_discount_display_amount.py
  sale_discount_display_amount/views/sale_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_discount_display_amount/odoo/addons/sale_discount_display_amount
  setup/sale_discount_display_amount/setup.py
Labels: 15.0

#1064 Syncing from upstream OCA/sale-workflow (13.0)
  README.md
  sale_order_product_recommendation/__manifest__.py
  sale_order_product_recommendation/wizards/sale_order_recommendation.py
Labels: 13.0

#1065 Syncing from upstream OCA/sale-workflow (15.0)
  sale_rental/i18n/fr_FR.po
Labels: 15.0

#1069 Bugfixing tests sale_advance_payment
  sale_advance_payment/tests/test_sale_advance_payment.py
Labels: 13.0.project_mi_465

#1066 Updating from latest OCA 13.0
  README.md
  sale_force_invoiced/README.rst
  sale_force_invoiced/__manifest__.py
  sale_force_invoiced/i18n/es.po
  sale_force_invoiced/model/sale_order.py
  sale_force_invoiced/readme/USAGE.rst
  sale_force_invoiced/static/description/index.html
  sale_order_price_recalculation/__manifest__.py
  sale_order_price_recalculation/i18n/ca.po
  sale_order_price_recalculation/i18n/de.po
  sale_order_price_recalculation/i18n/el_GR.po
  sale_order_price_recalculation/i18n/es.po
  sale_order_price_recalculation/i18n/es_ES.po
  sale_order_price_recalculation/i18n/es_VE.po
  sale_order_price_recalculation/i18n/fi.po
  sale_order_price_recalculation/i18n/fr.po
  sale_order_price_recalculation/i18n/hr.po
  sale_order_price_recalculation/i18n/hr_HR.po
  sale_order_price_recalculation/i18n/hu.po
  sale_order_price_recalculation/i18n/it.po
  sale_order_price_recalculation/i18n/nl.po
  sale_order_price_recalculation/i18n/nl_NL.po
  sale_order_price_recalculation/i18n/pt.po
  sale_order_price_recalculation/i18n/pt_BR.po
  sale_order_price_recalculation/i18n/ro.po
  sale_order_price_recalculation/i18n/sale_order_price_recalculation.pot
  sale_order_price_recalculation/i18n/sl.po
  sale_order_price_recalculation/i18n/tr.po
  sale_order_price_recalculation/i18n/tr_TR.po
  sale_order_price_recalculation/i18n/vi_VN.po
  sale_order_price_recalculation/i18n/zh_CN.po
  sale_order_price_recalculation/views/sale_order_view.xml
  sale_order_product_recommendation/__manifest__.py
  sale_order_product_recommendation/wizards/sale_order_recommendation.py
Labels: 13.0.project_mi_465

#1070 Syncing from upstream OCA/sale-workflow (15.0)
  README.md
  sale_order_qty_change_no_recompute/README.rst
  sale_order_qty_change_no_recompute/__init__.py
  sale_order_qty_change_no_recompute/__manifest__.py
  sale_order_qty_change_no_recompute/i18n/sale_order_qty_change_no_recompute.pot
  sale_order_qty_change_no_recompute/models/__init__.py
  sale_order_qty_change_no_recompute/models/sale_order.py
  sale_order_qty_change_no_recompute/readme/CONTRIBUTORS.rst
  sale_order_qty_change_no_recompute/readme/DESCRIPTION.rst
  sale_order_qty_change_no_recompute/readme/USAGE.rst
  sale_order_qty_change_no_recompute/static/description/icon.png
  sale_order_qty_change_no_recompute/static/description/index.html
  sale_order_qty_change_no_recompute/tests/__init__.py
  sale_order_qty_change_no_recompute/tests/test_sale_order_qty_change.py
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_order_qty_change_no_recompute/odoo/addons/sale_order_qty_change_no_recompute
  setup/sale_order_qty_change_no_recompute/setup.py
Labels: 15.0

#1071 Syncing from upstream OCA/sale-workflow (13.0)
  README.md
  sale_partner_selectable_option/__manifest__.py
  sale_partner_selectable_option/views/res_partner_view.xml
Labels: 13.0

#1072 Syncing from upstream OCA/sale-workflow (15.0)
  README.md
  sale_partner_selectable_option/README.rst
  sale_partner_selectable_option/__init__.py
  sale_partner_selectable_option/__manifest__.py
  sale_partner_selectable_option/i18n/es.po
  sale_partner_selectable_option/i18n/sale_partner_selectable_option.pot
  sale_partner_selectable_option/models/__init__.py
  sale_partner_selectable_option/models/res_partner.py
  sale_partner_selectable_option/models/sale_order.py
  sale_partner_selectable_option/readme/CONTRIBUTORS.rst
  sale_partner_selectable_option/readme/DESCRIPTION.rst
  sale_partner_selectable_option/readme/USAGE.rst
  sale_partner_selectable_option/static/description/icon.png
  sale_partner_selectable_option/static/description/index.html
  sale_partner_selectable_option/tests/__init__.py
  sale_partner_selectable_option/tests/test_sale_partner_selectable_option.py
  sale_partner_selectable_option/views/res_partner_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_partner_selectable_option/odoo/addons/sale_partner_selectable_option
  setup/sale_partner_selectable_option/setup.py
Labels: 15.0

#1074 Syncing from upstream OCA/sale-workflow (14.0)
  README.md
  sale_automatic_workflow/i18n/it.po
  sale_company_currency/README.rst
  sale_company_currency/__init__.py
  sale_company_currency/__manifest__.py
  sale_company_currency/i18n/ca.po
  sale_company_currency/i18n/de.po
  sale_company_currency/i18n/el_GR.po
  sale_company_currency/i18n/es.po
  sale_company_currency/i18n/es_ES.po
  sale_company_currency/i18n/es_VE.po
  sale_company_currency/i18n/fi.po
  sale_company_currency/i18n/fr.po
  sale_company_currency/i18n/hr.po
  sale_company_currency/i18n/hr_HR.po
  sale_company_currency/i18n/hu.po
  sale_company_currency/i18n/it.po
  sale_company_currency/i18n/nl.po
  sale_company_currency/i18n/nl_NL.po
  sale_company_currency/i18n/pt.po
  sale_company_currency/i18n/pt_BR.po
  sale_company_currency/i18n/ro.po
  sale_company_currency/i18n/sale_company_currency.pot
  sale_company_currency/i18n/sk.po
  sale_company_currency/i18n/sl.po
  sale_company_currency/i18n/tr.po
  sale_company_currency/i18n/tr_TR.po
  sale_company_currency/i18n/vi_VN.po
  sale_company_currency/i18n/zh_CN.po
  sale_company_currency/models/__init__.py
  sale_company_currency/models/sale_order.py
  sale_company_currency/readme/CONTRIBUTORS.rst
  sale_company_currency/readme/DESCRIPTION.rst
  sale_company_currency/static/description/icon.png
  sale_company_currency/static/description/index.html
  sale_company_currency/views/sale_order_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_company_currency/odoo/addons/sale_company_currency
  setup/sale_company_currency/setup.py
Labels: 14.0

#1076 Syncing from upstream OCA/sale-workflow (15.0)
  README.md
  sale_blanket_order/i18n/fr_FR.po
  sale_product_set_layout/README.rst
  sale_product_set_layout/__init__.py
  sale_product_set_layout/__manifest__.py
  sale_product_set_layout/demo/product_set.xml
  sale_product_set_layout/i18n/ca.po
  sale_product_set_layout/i18n/es.po
  sale_product_set_layout/i18n/fr.po
  sale_product_set_layout/i18n/hr.po
  sale_product_set_layout/i18n/pt.po
  sale_product_set_layout/i18n/sale_product_set_layout.pot
  sale_product_set_layout/i18n/sl.po
  sale_product_set_layout/models/__init__.py
  sale_product_set_layout/models/product_set_line.py
  sale_product_set_layout/readme/CONTRIBUTORS.rst
  sale_product_set_layout/readme/DESCRIPTION.rst
  sale_product_set_layout/static/description/icon.png
  sale_product_set_layout/static/description/icon.svg
  sale_product_set_layout/static/description/index.html
  sale_product_set_layout/tests/__init__.py
  sale_product_set_layout/tests/test_product_set_layout.py
  sale_product_set_layout/views/product_set.xml
  sale_product_set_layout/wizards/__init__.py
  sale_product_set_layout/wizards/product_set_add.py
  sale_product_set_layout/wizards/product_set_add.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_product_set_layout/odoo/addons/sale_product_set_layout
  setup/sale_product_set_layout/setup.py
Labels: 15.0

#1079 [FIX] changed search of currency so it finds at least one currency
  sale_advance_payment/tests/test_sale_advance_payment.py
Labels: 13.0.project_mi_465

#1080 [FIX] Precommit fix
  sale_advance_payment/tests/test_sale_advance_payment.py
Labels: 13.0.project_mi_465

#1081 Syncing from upstream OCA/sale-workflow (13.0)
  README.md
  product_supplierinfo_for_customer_sale/__manifest__.py
  product_supplierinfo_for_customer_sale/tests/test_product_supplierinfo_for_customer_sale.py
  sale_blanket_order/README.rst
  sale_blanket_order/__manifest__.py
  sale_blanket_order/models/sale_orders.py
  sale_blanket_order/readme/CONTRIBUTORS.rst
  sale_blanket_order/static/description/index.html
  sale_blanket_order/tests/test_blanket_orders.py
  sale_blanket_order/tests/test_sale_order.py
  sale_sourced_by_line/__init__.py
  sale_sourced_by_line/__manifest__.py
  sale_sourced_by_line/model/__init__.py
  sale_sourced_by_line/model/sale_order.py
  sale_sourced_by_line/model/sale_order_line.py
  sale_sourced_by_line/tests/__init__.py
  sale_sourced_by_line/tests/test_sale_is_delivered.py
  sale_sourced_by_line/tests/test_sale_sourced_by_line.py
  sale_stock_picking_blocking/README.rst
  sale_stock_picking_blocking/__manifest__.py
  sale_stock_picking_blocking/data/sale_stock_picking_blocking_data.xml
  sale_stock_picking_blocking/models/res_partner.py
  sale_stock_picking_blocking/models/sale_order.py
  sale_stock_picking_blocking/models/sale_stock_picking_blocking_reason.py
  sale_stock_picking_blocking/readme/CONTRIBUTORS.rst
  sale_stock_picking_blocking/security/sale_stock_picking_blocking_security.xml
  sale_stock_picking_blocking/static/description/index.html
  sale_stock_picking_blocking/tests/test_sale_stock_picking_blocking.py
  sale_stock_picking_blocking/views/res_partner_view.xml
  sale_stock_picking_blocking/views/sale_order_view.xml
  sale_stock_picking_blocking/views/sale_stock_picking_blocking_reason_view.xml
  sale_tier_validation/__manifest__.py
  sale_tier_validation/tests/test_tier_validation.py
Labels: 13.0

#1082 Syncing from upstream OCA/sale-workflow (15.0)
  sale_blanket_order/i18n/fr_FR.po
Labels: 15.0

#1083 Syncing from upstream OCA/sale-workflow (14.0)
  README.md
  sale_order_general_discount_triple/README.rst
  sale_order_general_discount_triple/__init__.py
  sale_order_general_discount_triple/__manifest__.py
  sale_order_general_discount_triple/i18n/sale_order_general_discount_triple.pot
  sale_order_general_discount_triple/models/__init__.py
  sale_order_general_discount_triple/models/res_config_settings.py
  sale_order_general_discount_triple/models/sale_order.py
  sale_order_general_discount_triple/models/sale_order_line.py
  sale_order_general_discount_triple/readme/CONTRIBUTORS.rst
  sale_order_general_discount_triple/readme/DESCRIPTION.rst
  sale_order_general_discount_triple/readme/HISTORY.rst
  sale_order_general_discount_triple/readme/USAGE.rst
  sale_order_general_discount_triple/static/description/icon.png
  sale_order_general_discount_triple/static/description/index.html
  sale_order_general_discount_triple/tests/__init__.py
  sale_order_general_discount_triple/tests/test_module.py
  sale_order_general_discount_triple/views/res_config_settings.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_order_general_discount_triple/odoo/addons/sale_order_general_discount_triple
  setup/sale_order_general_discount_triple/setup.py
Labels: 14.0

#1084 Syncing from upstream OCA/sale-workflow (14.0)
  sale_automatic_workflow/i18n/it.po
  sale_automatic_workflow_payment_mode/i18n/it.po
  sale_commercial_partner/i18n/it.po
  sale_company_currency/i18n/it.po
  sale_exception/i18n/it.po
  sale_force_invoiced/i18n/it.po
  sale_isolated_quotation/i18n/it.po
  sale_order_general_discount_triple/i18n/it.po
  sale_order_invoicing_finished_task/i18n/it.po
  sale_order_lot_selection/i18n/it.po
  sale_order_type/i18n/it.po
  sale_partner_incoterm/i18n/it.po
  sale_shipping_info_helper/i18n/it.po
  sale_validity/i18n/it.po
Labels: 14.0

#1085 Syncing from upstream OCA/sale-workflow (12.0)
  sale_disable_inventory_check/i18n/sl.po
  sale_quotation_number/i18n/sl.po
Labels: 12.0

#1086 Syncing from upstream OCA/sale-workflow (13.0)
  sale_advance_payment/i18n/es.po
Labels: 13.0

#1087 Syncing from upstream OCA/sale-workflow (13.0)
  sale_advance_payment/i18n/es.po
Labels: 13.0

#1088 Syncing from upstream OCA/sale-workflow (14.0)
  sale_advance_payment/i18n/es.po
  sale_exception/i18n/fr.po
  sale_stock_picking_blocking/i18n/fr.po
Labels: 14.0

#1089 Syncing from upstream OCA/sale-workflow (15.0)
  README.md
  sale_invoice_plan/__manifest__.py
  sale_invoice_plan/views/sale_view.xml
  sales_team_security/README.rst
  sales_team_security/__init__.py
  sales_team_security/__manifest__.py
  sales_team_security/hooks.py
  sales_team_security/i18n/es.po
  sales_team_security/i18n/it.po
  sales_team_security/i18n/sales_team_security.pot
  sales_team_security/models/__init__.py
  sales_team_security/models/ir_rule.py
  sales_team_security/models/res_partner.py
  sales_team_security/readme/CONFIGURE.rst
  sales_team_security/readme/CONTRIBUTORS.rst
  sales_team_security/readme/DESCRIPTION.rst
  sales_team_security/readme/INSTALL.rst
  sales_team_security/readme/ROADMAP.rst
  sales_team_security/security/sales_team_security.xml
  sales_team_security/static/description/icon.png
  sales_team_security/static/description/index.html
  sales_team_security/tests/__init__.py
  sales_team_security/tests/common.py
  sales_team_security/tests/test_sales_team_security.py
  sales_team_security/views/res_partner_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sales_team_security/odoo/addons/sales_team_security
  setup/sales_team_security/setup.py
Labels: 15.0

#1090 15.0 sale order lot selection bad rus
  oca_dependencies.txt
  sale_order_lot_selection/README.rst
  sale_order_lot_selection/__init__.py
  sale_order_lot_selection/__manifest__.py
  sale_order_lot_selection/demo/sale_demo.xml
  sale_order_lot_selection/i18n/ca.po
  sale_order_lot_selection/i18n/de.po
  sale_order_lot_selection/i18n/el_GR.po
  sale_order_lot_selection/i18n/en.po
  sale_order_lot_selection/i18n/es.po
  sale_order_lot_selection/i18n/es_ES.po
  sale_order_lot_selection/i18n/es_MX.po
  sale_order_lot_selection/i18n/es_VE.po
  sale_order_lot_selection/i18n/fi.po
  sale_order_lot_selection/i18n/fr.po
  sale_order_lot_selection/i18n/gl.po
  sale_order_lot_selection/i18n/hr.po
  sale_order_lot_selection/i18n/hr_HR.po
  sale_order_lot_selection/i18n/hu.po
  sale_order_lot_selection/i18n/it.po
  sale_order_lot_selection/i18n/nl.po
  sale_order_lot_selection/i18n/nl_NL.po
  sale_order_lot_selection/i18n/pt.po
  sale_order_lot_selection/i18n/pt_BR.po
  sale_order_lot_selection/i18n/pt_PT.po
  sale_order_lot_selection/i18n/ro.po
  sale_order_lot_selection/i18n/sale_order_lot_selection.pot
  sale_order_lot_selection/i18n/sk.po
  sale_order_lot_selection/i18n/sl.po
  sale_order_lot_selection/i18n/tr.po
  sale_order_lot_selection/i18n/tr_TR.po
  sale_order_lot_selection/i18n/vi_VN.po
  sale_order_lot_selection/i18n/zh_CN.po
  sale_order_lot_selection/models/__init__.py
  sale_order_lot_selection/models/sale_order_line.py
  sale_order_lot_selection/readme/CONTRIBUTORS.rst
  sale_order_lot_selection/readme/DESCRIPTION.rst
  sale_order_lot_selection/readme/ROADMAP.rst
  sale_order_lot_selection/readme/USAGE.rst
  sale_order_lot_selection/static/description/icon.png
  sale_order_lot_selection/static/description/index.html
  sale_order_lot_selection/tests/__init__.py
  sale_order_lot_selection/tests/test_sale_order_lot_selection.py
  sale_order_lot_selection/view/sale_view.xml
  setup/sale_order_lot_selection/odoo/addons/sale_order_lot_selection
  setup/sale_order_lot_selection/setup.py
  test-requirements.txt
Labels: 15.0.project_mi_465.t130203
