Repository brain-tec/sale-workflow, pull requests merged in 2022-07, with the labels that each got.

#1092 [t130203] MIDE DEV V15 Migration - Misc - Part 1 (OCA & BT)
  sale_partner_incoterm/README.rst
  sale_partner_incoterm/__init__.py
  sale_partner_incoterm/__manifest__.py
  sale_partner_incoterm/i18n/ca.po
  sale_partner_incoterm/i18n/de.po
  sale_partner_incoterm/i18n/es.po
  sale_partner_incoterm/i18n/fi.po
  sale_partner_incoterm/i18n/fr.po
  sale_partner_incoterm/i18n/it.po
  sale_partner_incoterm/i18n/nl.po
  sale_partner_incoterm/i18n/sale_partner_incoterm.pot
  sale_partner_incoterm/i18n/sl.po
  sale_partner_incoterm/i18n/tr.po
  sale_partner_incoterm/i18n/zh_CN.po
  sale_partner_incoterm/models/__init__.py
  sale_partner_incoterm/models/res_partner.py
  sale_partner_incoterm/models/sale_order.py
  sale_partner_incoterm/readme/CONTRIBUTORS.rst
  sale_partner_incoterm/readme/DESCRIPTION.rst
  sale_partner_incoterm/static/description/icon.png
  sale_partner_incoterm/static/description/index.html
  sale_partner_incoterm/tests/__init__.py
  sale_partner_incoterm/tests/test_sale_partner_incoterm.py
  sale_partner_incoterm/views/res_partner.xml
  setup/sale_partner_incoterm/odoo/addons/sale_partner_incoterm
  setup/sale_partner_incoterm/setup.py
Labels: odoo_migration, 15.0.project_mi_465

#1093 Syncing from upstream OCA/sale-workflow (13.0)
  .copier-answers.yml
  .github/workflows/test.yml
  README.md
  sale_advance_payment/i18n/es.po
  sale_order_line_sequence/README.rst
  sale_order_line_sequence/__init__.py
  sale_order_line_sequence/__manifest__.py
  sale_order_line_sequence/i18n/ca.po
  sale_order_line_sequence/i18n/de.po
  sale_order_line_sequence/i18n/el_GR.po
  sale_order_line_sequence/i18n/es.po
  sale_order_line_sequence/i18n/es_ES.po
  sale_order_line_sequence/i18n/es_VE.po
  sale_order_line_sequence/i18n/fi.po
  sale_order_line_sequence/i18n/fr.po
  sale_order_line_sequence/i18n/hr.po
  sale_order_line_sequence/i18n/hr_HR.po
  sale_order_line_sequence/i18n/hu.po
  sale_order_line_sequence/i18n/it.po
  sale_order_line_sequence/i18n/nl.po
  sale_order_line_sequence/i18n/nl_NL.po
  sale_order_line_sequence/i18n/pt.po
  sale_order_line_sequence/i18n/pt_BR.po
  sale_order_line_sequence/i18n/ro.po
  sale_order_line_sequence/i18n/sale_order_line_sequence.pot
  sale_order_line_sequence/i18n/sk.po
  sale_order_line_sequence/i18n/sl.po
  sale_order_line_sequence/i18n/tr.po
  sale_order_line_sequence/i18n/tr_TR.po
  sale_order_line_sequence/i18n/vi_VN.po
  sale_order_line_sequence/i18n/zh_CN.po
  sale_order_line_sequence/init_hooks.py
  sale_order_line_sequence/model/__init__.py
  sale_order_line_sequence/model/sale_order.py
  sale_order_line_sequence/readme/CONTRIBUTORS.rst
  sale_order_line_sequence/readme/CREDITS.rst
  sale_order_line_sequence/readme/DESCRIPTION.rst
  sale_order_line_sequence/static/description/icon.png
  sale_order_line_sequence/static/description/index.html
  sale_order_line_sequence/tests/__init__.py
  sale_order_line_sequence/tests/test_sale_order_line_sequence.py
  sale_order_line_sequence/views/report_saleorder.xml
  sale_order_line_sequence/views/sale_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_order_line_sequence/odoo/addons/sale_order_line_sequence
  setup/sale_order_line_sequence/setup.py
Labels: 13.0

#1094 Syncing from upstream OCA/sale-workflow (15.0)
  README.md
  sale_stock_cancel_restriction/README.rst
  sale_stock_cancel_restriction/__init__.py
  sale_stock_cancel_restriction/__manifest__.py
  sale_stock_cancel_restriction/i18n/es.po
  sale_stock_cancel_restriction/i18n/sale_stock_cancel_restriction.pot
  sale_stock_cancel_restriction/models/__init__.py
  sale_stock_cancel_restriction/models/sale_order.py
  sale_stock_cancel_restriction/readme/CONTRIBUTORS.rst
  sale_stock_cancel_restriction/readme/DESCRIPTION.rst
  sale_stock_cancel_restriction/readme/USAGE.rst
  sale_stock_cancel_restriction/static/description/icon.png
  sale_stock_cancel_restriction/static/description/index.html
  sale_stock_cancel_restriction/tests/__init__.py
  sale_stock_cancel_restriction/tests/test_sale_stock_cancel_restriction.py
  sale_stock_picking_blocking/__manifest__.py
  sale_stock_picking_blocking/data/sale_stock_picking_blocking_data.xml
  sale_stock_picking_blocking/security/sale_stock_picking_blocking_security.xml
  sale_stock_picking_blocking/views/res_partner_view.xml
  sale_stock_picking_blocking/views/sale_order_view.xml
  sale_stock_picking_blocking/views/sale_stock_picking_blocking_reason_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_stock_cancel_restriction/odoo/addons/sale_stock_cancel_restriction
  setup/sale_stock_cancel_restriction/setup.py
Labels: 15.0

#1095 Syncing from upstream OCA/sale-workflow (13.0)
  README.md
  product_supplierinfo_for_customer_sale/__manifest__.py
  product_supplierinfo_for_customer_sale/i18n/ca.po
  product_supplierinfo_for_customer_sale/i18n/de.po
  product_supplierinfo_for_customer_sale/i18n/es.po
  product_supplierinfo_for_customer_sale/i18n/it.po
  product_supplierinfo_for_customer_sale/i18n/product_supplierinfo_for_customer_sale.pot
  product_supplierinfo_for_customer_sale/i18n/pt.po
  product_supplierinfo_for_customer_sale/views/product_customerinfo_views.xml
Labels: 13.0

#1096 Syncing from upstream OCA/sale-workflow (15.0)
  README.md
  sale_blanket_order/i18n/fr_FR.po
  sale_order_type/i18n/fr.po
  sale_quotation_number/README.rst
  sale_quotation_number/__init__.py
  sale_quotation_number/__manifest__.py
  sale_quotation_number/data/ir_sequence_data.xml
  sale_quotation_number/i18n/ca.po
  sale_quotation_number/i18n/de.po
  sale_quotation_number/i18n/es.po
  sale_quotation_number/i18n/es_ES.po
  sale_quotation_number/i18n/fi.po
  sale_quotation_number/i18n/fr.po
  sale_quotation_number/i18n/hr.po
  sale_quotation_number/i18n/hu.po
  sale_quotation_number/i18n/it.po
  sale_quotation_number/i18n/nl.po
  sale_quotation_number/i18n/nl_NL.po
  sale_quotation_number/i18n/pt_BR.po
  sale_quotation_number/i18n/ro.po
  sale_quotation_number/i18n/sale_quotation_number.pot
  sale_quotation_number/i18n/sk.po
  sale_quotation_number/i18n/sl.po
  sale_quotation_number/i18n/tr.po
  sale_quotation_number/i18n/tr_TR.po
  sale_quotation_number/i18n/zh_CN.po
  sale_quotation_number/models/__init__.py
  sale_quotation_number/models/res_company.py
  sale_quotation_number/models/sale_order.py
  sale_quotation_number/readme/CONFIGURE.rst
  sale_quotation_number/readme/CONTRIBUTORS.rst
  sale_quotation_number/readme/CREDITS.rst
  sale_quotation_number/readme/DESCRIPTION.rst
  sale_quotation_number/static/description/icon.png
  sale_quotation_number/static/description/index.html
  sale_quotation_number/tests/__init__.py
  sale_quotation_number/tests/test_sale_order.py
  sale_quotation_number/views/sales_config.xml
  sale_rental/i18n/fr.po
  sale_stock_picking_blocking/i18n/fr.po
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_quotation_number/odoo/addons/sale_quotation_number
  setup/sale_quotation_number/setup.py
Labels: 15.0

#1098 Syncing from upstream OCA/sale-workflow (12.0)
  sale_last_price_info/i18n/it.po
Labels: 12.0

#1099 Syncing from upstream OCA/sale-workflow (15.0)
  README.md
  partner_contact_sale_info_propagation/README.rst
  partner_contact_sale_info_propagation/__init__.py
  partner_contact_sale_info_propagation/__manifest__.py
  partner_contact_sale_info_propagation/i18n/ca.po
  partner_contact_sale_info_propagation/i18n/de.po
  partner_contact_sale_info_propagation/i18n/es.po
  partner_contact_sale_info_propagation/i18n/fr.po
  partner_contact_sale_info_propagation/i18n/partner_contact_sale_info_propagation.pot
  partner_contact_sale_info_propagation/models/__init__.py
  partner_contact_sale_info_propagation/models/res_partner.py
  partner_contact_sale_info_propagation/readme/CONTRIBUTORS.rst
  partner_contact_sale_info_propagation/readme/DESCRIPTION.rst
  partner_contact_sale_info_propagation/readme/USAGE.rst
  partner_contact_sale_info_propagation/static/description/icon.png
  partner_contact_sale_info_propagation/static/description/index.html
  partner_contact_sale_info_propagation/tests/__init__.py
  partner_contact_sale_info_propagation/tests/test_partner_contact_sale_info_propagation.py
  partner_contact_sale_info_propagation/views/res_partner_view.xml
  sale_blanket_order/i18n/de.po
  sale_blanket_order/i18n/es.po
  sale_blanket_order/i18n/fr_FR.po
  sale_blanket_order/i18n/pt.po
  sale_blanket_order/i18n/sale_blanket_order.pot
  sales_team_security_crm/README.rst
  sales_team_security_crm/__init__.py
  sales_team_security_crm/__manifest__.py
  sales_team_security_crm/i18n/sales_team_security_crm.pot
  sales_team_security_crm/migrations/14.0.2.0.0/pre-migration.py
  sales_team_security_crm/readme/CONTRIBUTORS.rst
  sales_team_security_crm/readme/DESCRIPTION.rst
  sales_team_security_crm/security/security.xml
  sales_team_security_crm/static/description/icon.png
  sales_team_security_crm/static/description/index.html
  sales_team_security_crm/tests/__init__.py
  sales_team_security_crm/tests/test_sales_team_security_crm.py
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/partner_contact_sale_info_propagation/odoo/addons/partner_contact_sale_info_propagation
  setup/partner_contact_sale_info_propagation/setup.py
  setup/sales_team_security_crm/odoo/addons/sales_team_security_crm
  setup/sales_team_security_crm/setup.py
Labels: 15.0

#1101 [t130465]15.0 sale order lot selection
  oca_dependencies.txt
  sale_order_lot_selection/README.rst
  sale_order_lot_selection/__init__.py
  sale_order_lot_selection/__manifest__.py
  sale_order_lot_selection/demo/sale_demo.xml
  sale_order_lot_selection/i18n/ca.po
  sale_order_lot_selection/i18n/de.po
  sale_order_lot_selection/i18n/el_GR.po
  sale_order_lot_selection/i18n/en.po
  sale_order_lot_selection/i18n/es.po
  sale_order_lot_selection/i18n/es_ES.po
  sale_order_lot_selection/i18n/es_MX.po
  sale_order_lot_selection/i18n/es_VE.po
  sale_order_lot_selection/i18n/fi.po
  sale_order_lot_selection/i18n/fr.po
  sale_order_lot_selection/i18n/gl.po
  sale_order_lot_selection/i18n/hr.po
  sale_order_lot_selection/i18n/hr_HR.po
  sale_order_lot_selection/i18n/hu.po
  sale_order_lot_selection/i18n/it.po
  sale_order_lot_selection/i18n/nl.po
  sale_order_lot_selection/i18n/nl_NL.po
  sale_order_lot_selection/i18n/pt.po
  sale_order_lot_selection/i18n/pt_BR.po
  sale_order_lot_selection/i18n/pt_PT.po
  sale_order_lot_selection/i18n/ro.po
  sale_order_lot_selection/i18n/sale_order_lot_selection.pot
  sale_order_lot_selection/i18n/sk.po
  sale_order_lot_selection/i18n/sl.po
  sale_order_lot_selection/i18n/tr.po
  sale_order_lot_selection/i18n/tr_TR.po
  sale_order_lot_selection/i18n/vi_VN.po
  sale_order_lot_selection/i18n/zh_CN.po
  sale_order_lot_selection/models/__init__.py
  sale_order_lot_selection/models/sale_order_line.py
  sale_order_lot_selection/readme/CONTRIBUTORS.rst
  sale_order_lot_selection/readme/DESCRIPTION.rst
  sale_order_lot_selection/readme/ROADMAP.rst
  sale_order_lot_selection/readme/USAGE.rst
  sale_order_lot_selection/static/description/icon.png
  sale_order_lot_selection/static/description/index.html
  sale_order_lot_selection/tests/__init__.py
  sale_order_lot_selection/tests/test_sale_order_lot_selection.py
  sale_order_lot_selection/view/sale_view.xml
  setup/sale_order_lot_selection/odoo/addons/sale_order_lot_selection
  setup/sale_order_lot_selection/setup.py
  test-requirements.txt
Labels: 15.0.project_mi_465.t130465

#1102 [t130465] MIDE DEV V15 Migration - Misc - Part 2 (OCA & BT)
  oca_dependencies.txt
  sale_order_lot_selection/README.rst
  sale_order_lot_selection/__init__.py
  sale_order_lot_selection/__manifest__.py
  sale_order_lot_selection/demo/sale_demo.xml
  sale_order_lot_selection/i18n/ca.po
  sale_order_lot_selection/i18n/de.po
  sale_order_lot_selection/i18n/el_GR.po
  sale_order_lot_selection/i18n/en.po
  sale_order_lot_selection/i18n/es.po
  sale_order_lot_selection/i18n/es_ES.po
  sale_order_lot_selection/i18n/es_MX.po
  sale_order_lot_selection/i18n/es_VE.po
  sale_order_lot_selection/i18n/fi.po
  sale_order_lot_selection/i18n/fr.po
  sale_order_lot_selection/i18n/gl.po
  sale_order_lot_selection/i18n/hr.po
  sale_order_lot_selection/i18n/hr_HR.po
  sale_order_lot_selection/i18n/hu.po
  sale_order_lot_selection/i18n/it.po
  sale_order_lot_selection/i18n/nl.po
  sale_order_lot_selection/i18n/nl_NL.po
  sale_order_lot_selection/i18n/pt.po
  sale_order_lot_selection/i18n/pt_BR.po
  sale_order_lot_selection/i18n/pt_PT.po
  sale_order_lot_selection/i18n/ro.po
  sale_order_lot_selection/i18n/sale_order_lot_selection.pot
  sale_order_lot_selection/i18n/sk.po
  sale_order_lot_selection/i18n/sl.po
  sale_order_lot_selection/i18n/tr.po
  sale_order_lot_selection/i18n/tr_TR.po
  sale_order_lot_selection/i18n/vi_VN.po
  sale_order_lot_selection/i18n/zh_CN.po
  sale_order_lot_selection/models/__init__.py
  sale_order_lot_selection/models/sale_order_line.py
  sale_order_lot_selection/readme/CONTRIBUTORS.rst
  sale_order_lot_selection/readme/DESCRIPTION.rst
  sale_order_lot_selection/readme/ROADMAP.rst
  sale_order_lot_selection/readme/USAGE.rst
  sale_order_lot_selection/static/description/icon.png
  sale_order_lot_selection/static/description/index.html
  sale_order_lot_selection/tests/__init__.py
  sale_order_lot_selection/tests/test_sale_order_lot_selection.py
  sale_order_lot_selection/view/sale_view.xml
  setup/sale_order_lot_selection/odoo/addons/sale_order_lot_selection
  setup/sale_order_lot_selection/setup.py
  test-requirements.txt
Labels: odoo_migration, 15.0.project_mi_465

#1103 Syncing from upstream OCA/sale-workflow (13.0)
  README.md
  sale_tier_validation/__manifest__.py
  sale_tier_validation/data/mail_data.xml
  sale_tier_validation/i18n/es.po
  sale_tier_validation/i18n/sale_tier_validation.pot
  sale_tier_validation/models/sale_order.py
Labels: 13.0

#1104 Syncing from upstream OCA/sale-workflow (15.0)
  README.md
  sale_invoice_blocking/README.rst
  sale_invoice_blocking/__init__.py
  sale_invoice_blocking/__manifest__.py
  sale_invoice_blocking/i18n/ca.po
  sale_invoice_blocking/i18n/es.po
  sale_invoice_blocking/i18n/es_PA.po
  sale_invoice_blocking/i18n/fr.po
  sale_invoice_blocking/i18n/sale_invoice_blocking.pot
  sale_invoice_blocking/models/__init__.py
  sale_invoice_blocking/models/invoice_blocking_reason.py
  sale_invoice_blocking/models/sale_order.py
  sale_invoice_blocking/readme/CONFIGURE.rst
  sale_invoice_blocking/readme/CONTRIBUTORS.rst
  sale_invoice_blocking/readme/DESCRIPTION.rst
  sale_invoice_blocking/readme/USAGE.rst
  sale_invoice_blocking/security/ir.model.access.csv
  sale_invoice_blocking/static/description/icon.png
  sale_invoice_blocking/static/description/index.html
  sale_invoice_blocking/views/menus.xml
  sale_invoice_blocking/views/sale_invoice_blocking_reason_view.xml
  sale_invoice_blocking/views/sale_order.xml
  sale_order_product_availability_inline/README.rst
  sale_order_product_availability_inline/__init__.py
  sale_order_product_availability_inline/__manifest__.py
  sale_order_product_availability_inline/i18n/ca.po
  sale_order_product_availability_inline/i18n/es.po
  sale_order_product_availability_inline/i18n/sale_order_product_availability_inline.pot
  sale_order_product_availability_inline/models/__init__.py
  sale_order_product_availability_inline/models/product_product.py
  sale_order_product_availability_inline/models/sale.py
  sale_order_product_availability_inline/readme/CONTRIBUTORS.rst
  sale_order_product_availability_inline/readme/DESCRIPTION.rst
  sale_order_product_availability_inline/readme/USAGE.rst
  sale_order_product_availability_inline/static/description/icon.png
  sale_order_product_availability_inline/static/description/index.html
  sale_order_product_availability_inline/tests/__init__.py
  sale_order_product_availability_inline/tests/test_sale_order_product_availability_inline.py
  sale_order_product_availability_inline/views/sale_views.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_invoice_blocking/odoo/addons/sale_invoice_blocking
  setup/sale_invoice_blocking/setup.py
  setup/sale_order_product_availability_inline/odoo/addons/sale_order_product_availability_inline
  setup/sale_order_product_availability_inline/setup.py
Labels: 15.0

#1105 Syncing from upstream OCA/sale-workflow (13.0)
  sale_tier_validation/i18n/tr.po
  sale_tier_validation/i18n/zh_CN.po
Labels: 13.0

#1106 Syncing from upstream OCA/sale-workflow (15.0)
  README.md
  sale_order_line_price_history/README.rst
  sale_order_line_price_history/__init__.py
  sale_order_line_price_history/__manifest__.py
  sale_order_line_price_history/i18n/de.po
  sale_order_line_price_history/i18n/es.po
  sale_order_line_price_history/i18n/pt.po
  sale_order_line_price_history/i18n/sale_order_line_price_history.pot
  sale_order_line_price_history/i18n/zh_CN.po
  sale_order_line_price_history/models/__init__.py
  sale_order_line_price_history/models/sale_order_line.py
  sale_order_line_price_history/readme/CONTRIBUTORS.rst
  sale_order_line_price_history/readme/DESCRIPTION.rst
  sale_order_line_price_history/readme/ROADMAP.rst
  sale_order_line_price_history/readme/USAGE.rst
  sale_order_line_price_history/security/ir.model.access.csv
  sale_order_line_price_history/static/description/icon.png
  sale_order_line_price_history/static/description/index.html
  sale_order_line_price_history/static/src/js/sale_line_price_history_widget.js
  sale_order_line_price_history/static/src/xml/sale_line_price_history_widget.xml
  sale_order_line_price_history/tests/__init__.py
  sale_order_line_price_history/tests/test_sale_order_line_price_history.py
  sale_order_line_price_history/views/sale_views.xml
  sale_order_line_price_history/wizards/__init__.py
  sale_order_line_price_history/wizards/sale_order_line_price_history.py
  sale_order_line_price_history/wizards/sale_order_line_price_history.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_order_line_price_history/odoo/addons/sale_order_line_price_history
  setup/sale_order_line_price_history/setup.py
Labels: 15.0

#1109 Syncing from upstream OCA/sale-workflow (14.0)
  README.md
  sale_order_price_recalculation/README.rst
  sale_order_price_recalculation/__init__.py
  sale_order_price_recalculation/__manifest__.py
  sale_order_price_recalculation/i18n/ca.po
  sale_order_price_recalculation/i18n/de.po
  sale_order_price_recalculation/i18n/el_GR.po
  sale_order_price_recalculation/i18n/en.po
  sale_order_price_recalculation/i18n/es.po
  sale_order_price_recalculation/i18n/es_ES.po
  sale_order_price_recalculation/i18n/es_VE.po
  sale_order_price_recalculation/i18n/fi.po
  sale_order_price_recalculation/i18n/fr.po
  sale_order_price_recalculation/i18n/hr.po
  sale_order_price_recalculation/i18n/hr_HR.po
  sale_order_price_recalculation/i18n/hu.po
  sale_order_price_recalculation/i18n/it.po
  sale_order_price_recalculation/i18n/nl.po
  sale_order_price_recalculation/i18n/nl_NL.po
  sale_order_price_recalculation/i18n/pt.po
  sale_order_price_recalculation/i18n/pt_BR.po
  sale_order_price_recalculation/i18n/ro.po
  sale_order_price_recalculation/i18n/sale_order_price_recalculation.pot
  sale_order_price_recalculation/i18n/sl.po
  sale_order_price_recalculation/i18n/tr.po
  sale_order_price_recalculation/i18n/tr_TR.po
  sale_order_price_recalculation/i18n/vi_VN.po
  sale_order_price_recalculation/i18n/zh_CN.po
  sale_order_price_recalculation/models/__init__.py
  sale_order_price_recalculation/models/sale_order.py
  sale_order_price_recalculation/readme/CONTRIBUTORS.rst
  sale_order_price_recalculation/readme/DESCRIPTION.rst
  sale_order_price_recalculation/readme/INSTALL.rst
  sale_order_price_recalculation/readme/ROADMAP.rst
  sale_order_price_recalculation/readme/USAGE.rst
  sale_order_price_recalculation/static/description/icon.png
  sale_order_price_recalculation/static/description/index.html
  sale_order_price_recalculation/static/description/sale_order_price_recalculation.png
  sale_order_price_recalculation/tests/__init__.py
  sale_order_price_recalculation/tests/test_sale_order_price_recalculation.py
  sale_order_price_recalculation/views/sale_order_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_order_price_recalculation/odoo/addons/sale_order_price_recalculation
  setup/sale_order_price_recalculation/setup.py
Labels: 14.0

#1110 Syncing from upstream OCA/sale-workflow (15.0)
  README.md
  sale_order_product_assortment/README.rst
  sale_order_product_assortment/__init__.py
  sale_order_product_assortment/__manifest__.py
  sale_order_product_assortment/i18n/ca.po
  sale_order_product_assortment/i18n/es.po
  sale_order_product_assortment/i18n/it.po
  sale_order_product_assortment/i18n/sale_order_product_assortment.pot
  sale_order_product_assortment/models/__init__.py
  sale_order_product_assortment/models/sale_order.py
  sale_order_product_assortment/models/sale_order_line.py
  sale_order_product_assortment/readme/CONFIGURE.rst
  sale_order_product_assortment/readme/CONTRIBUTORS.rst
  sale_order_product_assortment/readme/DESCRIPTION.rst
  sale_order_product_assortment/readme/ROADMAP.rst
  sale_order_product_assortment/readme/USAGE.rst
  sale_order_product_assortment/static/description/icon.png
  sale_order_product_assortment/static/description/index.html
  sale_order_product_assortment/tests/__init__.py
  sale_order_product_assortment/tests/test_sale_order_product_assortment.py
  sale_order_product_assortment/views/sale_order_view.xml
  sales_team_security_sale/README.rst
  sales_team_security_sale/__init__.py
  sales_team_security_sale/__manifest__.py
  sales_team_security_sale/i18n/sales_team_security_sale.pot
  sales_team_security_sale/migrations/14.0.2.0.0/pre-migration.py
  sales_team_security_sale/readme/CONFIGURE.rst
  sales_team_security_sale/readme/CONTRIBUTORS.rst
  sales_team_security_sale/readme/DESCRIPTION.rst
  sales_team_security_sale/security/security.xml
  sales_team_security_sale/static/description/icon.png
  sales_team_security_sale/static/description/index.html
  sales_team_security_sale/tests/__init__.py
  sales_team_security_sale/tests/test_sales_team_security_sale.py
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_order_product_assortment/odoo/addons/sale_order_product_assortment
  setup/sale_order_product_assortment/setup.py
  setup/sales_team_security_sale/odoo/addons/sales_team_security_sale
  setup/sales_team_security_sale/setup.py
Labels: 15.0

#1111 Syncing from upstream OCA/sale-workflow (15.0)
  README.md
  sale_order_product_recommendation/README.rst
  sale_order_product_recommendation/__init__.py
  sale_order_product_recommendation/__manifest__.py
  sale_order_product_recommendation/i18n/es.po
  sale_order_product_recommendation/i18n/pt_BR.po
  sale_order_product_recommendation/i18n/sale_order_product_recommendation.pot
  sale_order_product_recommendation/models/__init__.py
  sale_order_product_recommendation/models/res_config_settings.py
  sale_order_product_recommendation/models/sale_order.py
  sale_order_product_recommendation/readme/CONFIGURE.rst
  sale_order_product_recommendation/readme/CONTRIBUTORS.rst
  sale_order_product_recommendation/readme/DESCRIPTION.rst
  sale_order_product_recommendation/readme/USAGE.rst
  sale_order_product_recommendation/security/ir.model.access.csv
  sale_order_product_recommendation/static/description/icon.png
  sale_order_product_recommendation/static/description/index.html
  sale_order_product_recommendation/tests/__init__.py
  sale_order_product_recommendation/tests/test_recommendation.py
  sale_order_product_recommendation/tests/test_recommendation_common.py
  sale_order_product_recommendation/views/res_config_settings_views.xml
  sale_order_product_recommendation/views/sale_order_view.xml
  sale_order_product_recommendation/wizards/__init__.py
  sale_order_product_recommendation/wizards/sale_order_recommendation.py
  sale_order_product_recommendation/wizards/sale_order_recommendation_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_order_product_recommendation/odoo/addons/sale_order_product_recommendation
  setup/sale_order_product_recommendation/setup.py
Labels: 15.0
