Repository brain-tec/sale-workflow, pull requests merged in 2022-09, with the labels that each got.

#1142 Syncing from upstream OCA/sale-workflow (12.0)
  sale_blanket_order/i18n/de.po
  sale_blanket_order/i18n/es.po
  sale_blanket_order/i18n/fr_FR.po
  sale_blanket_order/i18n/it.po
  sale_blanket_order/i18n/pt.po
  sale_rental/i18n/fr.po
Labels: 12.0

#1143 Syncing from upstream OCA/sale-workflow (13.0)
  README.md
  sale_automatic_workflow/tests/test_automatic_workflow.py
  sale_automatic_workflow/tests/test_multicompany.py
  sale_automatic_workflow_job/README.rst
  sale_automatic_workflow_job/__init__.py
  sale_automatic_workflow_job/__manifest__.py
  sale_automatic_workflow_job/data/queue_job_data.xml
  sale_automatic_workflow_job/i18n/sale_automatic_workflow_job.pot
  sale_automatic_workflow_job/models/__init__.py
  sale_automatic_workflow_job/models/automatic_workflow_job.py
  sale_automatic_workflow_job/models/queue_job.py
  sale_automatic_workflow_job/readme/CONTRIBUTORS.rst
  sale_automatic_workflow_job/readme/DESCRIPTION.rst
  sale_automatic_workflow_job/static/description/icon.png
  sale_automatic_workflow_job/static/description/index.html
  sale_automatic_workflow_job/tests/__init__.py
  sale_automatic_workflow_job/tests/test_auto_workflow_job.py
  sale_coupon_multi_currency/__manifest__.py
  sale_coupon_multi_currency/models/sale_coupon_program.py
  sale_coupon_multi_currency/tests/test_sale_coupon_multi_currency.py
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_automatic_workflow_job/odoo/addons/sale_automatic_workflow_job
  setup/sale_automatic_workflow_job/setup.py
Labels: 13.0

#1144 Syncing from upstream OCA/sale-workflow (14.0)
  sale_order_line_input/i18n/it.po
Labels: 14.0

#1145 Syncing from upstream OCA/sale-workflow (15.0)
  README.md
  sale_blanket_order/__manifest__.py
  sale_blanket_order/report/templates.xml
  sale_stock_invoice_plan/README.rst
  sale_stock_invoice_plan/__init__.py
  sale_stock_invoice_plan/__manifest__.py
  sale_stock_invoice_plan/i18n/sale_stock_invoice_plan.pot
  sale_stock_invoice_plan/readme/CONTRIBUTORS.rst
  sale_stock_invoice_plan/readme/DESCRIPTION.rst
  sale_stock_invoice_plan/readme/HISTORY.rst
  sale_stock_invoice_plan/readme/INSTALL.rst
  sale_stock_invoice_plan/readme/USAGE.rst
  sale_stock_invoice_plan/security/ir.model.access.csv
  sale_stock_invoice_plan/static/description/icon.png
  sale_stock_invoice_plan/static/description/index.html
  sale_stock_invoice_plan/tests/__init__.py
  sale_stock_invoice_plan/tests/test_sale_invoice_plan.py
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_stock_invoice_plan/odoo/addons/sale_stock_invoice_plan
  setup/sale_stock_invoice_plan/setup.py
Labels: 15.0

#1146 [MIG] mig sale partner incoterm
  sale_partner_incoterm/README.rst
  sale_partner_incoterm/__init__.py
  sale_partner_incoterm/__manifest__.py
  sale_partner_incoterm/i18n/ca.po
  sale_partner_incoterm/i18n/de.po
  sale_partner_incoterm/i18n/es.po
  sale_partner_incoterm/i18n/fi.po
  sale_partner_incoterm/i18n/fr.po
  sale_partner_incoterm/i18n/it.po
  sale_partner_incoterm/i18n/nl.po
  sale_partner_incoterm/i18n/sale_partner_incoterm.pot
  sale_partner_incoterm/i18n/sl.po
  sale_partner_incoterm/i18n/tr.po
  sale_partner_incoterm/i18n/zh_CN.po
  sale_partner_incoterm/models/__init__.py
  sale_partner_incoterm/models/res_partner.py
  sale_partner_incoterm/models/sale_order.py
  sale_partner_incoterm/readme/CONTRIBUTORS.rst
  sale_partner_incoterm/readme/DESCRIPTION.rst
  sale_partner_incoterm/static/description/icon.png
  sale_partner_incoterm/static/description/index.html
  sale_partner_incoterm/tests/__init__.py
  sale_partner_incoterm/tests/test_sale_partner_incoterm.py
  sale_partner_incoterm/views/res_partner.xml
Labels: 15.0.project_sa_650

#1147 Syncing from upstream OCA/sale-workflow (12.0)
  README.md
  sale_invoice_plan/__manifest__.py
  sale_invoice_plan/i18n/fr.po
  sale_invoice_plan/i18n/it.po
  sale_invoice_plan/i18n/nl_NL.po
  sale_invoice_plan/i18n/pt_BR.po
  sale_invoice_plan/i18n/sale_invoice_plan.pot
  sale_invoice_plan/i18n/zh_CN.po
  sale_invoice_plan/models/sale.py
Labels: 12.0

#1148 Syncing from upstream OCA/sale-workflow (13.0)
  README.md
  product_supplierinfo_for_customer_elaboration/README.rst
  product_supplierinfo_for_customer_elaboration/__init__.py
  product_supplierinfo_for_customer_elaboration/__manifest__.py
  product_supplierinfo_for_customer_elaboration/i18n/es.po
  product_supplierinfo_for_customer_elaboration/i18n/product_supplierinfo_for_customer_elaboration.pot
  product_supplierinfo_for_customer_elaboration/models/__init__.py
  product_supplierinfo_for_customer_elaboration/models/product_customerinfo.py
  product_supplierinfo_for_customer_elaboration/models/sale_order_line.py
  product_supplierinfo_for_customer_elaboration/readme/CONFIGURE.rst
  product_supplierinfo_for_customer_elaboration/readme/CONTRIBUTORS.rst
  product_supplierinfo_for_customer_elaboration/readme/DESCRIPTION.rst
  product_supplierinfo_for_customer_elaboration/readme/USAGE.rst
  product_supplierinfo_for_customer_elaboration/security/ir.model.access.csv
  product_supplierinfo_for_customer_elaboration/static/description/icon.png
  product_supplierinfo_for_customer_elaboration/static/description/index.html
  product_supplierinfo_for_customer_elaboration/tests/__init__.py
  product_supplierinfo_for_customer_elaboration/tests/test_customerinfo_elaboration.py
  product_supplierinfo_for_customer_elaboration/views/product_views.xml
  product_supplierinfo_for_customer_sale/__manifest__.py
  product_supplierinfo_for_customer_sale/security/ir.model.access.csv
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/product_supplierinfo_for_customer_elaboration/odoo/addons/product_supplierinfo_for_customer_elaboration
  setup/product_supplierinfo_for_customer_elaboration/setup.py
Labels: 13.0

#1150 Syncing from upstream OCA/sale-workflow (14.0)
  README.md
  product_supplierinfo_for_customer_sale/__manifest__.py
  product_supplierinfo_for_customer_sale/security/ir.model.access.csv
Labels: 14.0

#1151 Syncing from upstream OCA/sale-workflow (15.0)
  README.md
  sale_blanket_order/i18n/fr_FR.po
  sale_invoice_plan/__manifest__.py
  sale_invoice_plan/data/sale_data.xml
  sale_invoice_plan/i18n/es.po
  sale_invoice_plan/i18n/fr.po
  sale_invoice_plan/i18n/nl_NL.po
  sale_invoice_plan/i18n/sale_invoice_plan.pot
  sale_invoice_plan/i18n/zh_CN.po
  sale_invoice_plan/models/sale.py
  sale_invoice_plan/models/sale_invoice_plan.py
  sale_invoice_plan/tests/test_sale_invoice_plan.py
  sale_invoice_plan/views/sale_view.xml
  sale_invoice_plan/wizard/sale_make_planned_invoice.py
Labels: 15.0

#1152 Syncing from upstream OCA/sale-workflow (13.0)
  README.md
  sale_payment_sheet/__manifest__.py
  sale_payment_sheet/views/sale_payment_sheet_menu.xml
Labels: 13.0

#1153 Syncing from upstream OCA/sale-workflow (15.0)
  sale_blanket_order/i18n/fr.po
Labels: 15.0

#1154 Syncing from upstream OCA/sale-workflow (15.0)
  README.md
  sale_payment_sheet/__manifest__.py
  sale_payment_sheet/views/sale_payment_sheet_menu.xml
Labels: 15.0

#1155 Syncing from upstream OCA/sale-workflow (14.0)
  README.md
  sale_global_discount/README.rst
  sale_global_discount/__manifest__.py
  sale_global_discount/readme/CONFIGURE.rst
  sale_global_discount/readme/USAGE.rst
  sale_global_discount/static/description/index.html
  sale_triple_discount/i18n/fr.po
Labels: 14.0

#1156 Syncing from upstream OCA/sale-workflow (15.0)
  sale_blanket_order/i18n/fr.po
Labels: 15.0

#1157 Syncing from upstream OCA/sale-workflow (15.0)
  README.md
  sale_order_line_input/README.rst
  sale_order_line_input/__init__.py
  sale_order_line_input/__manifest__.py
  sale_order_line_input/i18n/de.po
  sale_order_line_input/i18n/es.po
  sale_order_line_input/i18n/it.po
  sale_order_line_input/i18n/sale_order_line_input.pot
  sale_order_line_input/i18n/zh_CN.po
  sale_order_line_input/models/__init__.py
  sale_order_line_input/models/sale_order.py
  sale_order_line_input/readme/CONTRIBUTORS.rst
  sale_order_line_input/readme/DESCRIPTION.rst
  sale_order_line_input/readme/USAGE.rst
  sale_order_line_input/static/description/icon.png
  sale_order_line_input/static/description/index.html
  sale_order_line_input/tests/__init__.py
  sale_order_line_input/tests/test_sale_order_line_input.py
  sale_order_line_input/views/sale_order_line_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_order_line_input/odoo/addons/sale_order_line_input
  setup/sale_order_line_input/setup.py
Labels: 15.0

#1158 Syncing from upstream OCA/sale-workflow (12.0)
  README.md
  sale_invoice_plan/__manifest__.py
  sale_invoice_plan/i18n/fr.po
  sale_invoice_plan/i18n/it.po
  sale_invoice_plan/i18n/nl_NL.po
  sale_invoice_plan/i18n/pt_BR.po
  sale_invoice_plan/i18n/zh_CN.po
  sale_invoice_plan/models/sale.py
Labels: 12.0

#1159 Syncing from upstream OCA/sale-workflow (13.0)
  README.md
  sale_invoice_plan/__manifest__.py
  sale_invoice_plan/models/sale.py
Labels: 13.0

#1160 Syncing from upstream OCA/sale-workflow (14.0)
  README.md
  sale_invoice_plan/__manifest__.py
  sale_invoice_plan/models/sale.py
  sale_invoice_plan/models/sale_invoice_plan.py
Labels: 14.0

#1161 Syncing from upstream OCA/sale-workflow (15.0)
  README.md
  sale_invoice_plan/__manifest__.py
  sale_invoice_plan/models/sale.py
  sale_wishlist/README.rst
  sale_wishlist/__init__.py
  sale_wishlist/__manifest__.py
  sale_wishlist/i18n/es.po
  sale_wishlist/i18n/fr_FR.po
  sale_wishlist/i18n/sale_wishlist.pot
  sale_wishlist/models/__init__.py
  sale_wishlist/models/product_set.py
  sale_wishlist/models/res_partner.py
  sale_wishlist/readme/CONTRIBUTORS.rst
  sale_wishlist/readme/CREDITS.rst
  sale_wishlist/readme/DESCRIPTION.rst
  sale_wishlist/readme/USAGE.rst
  sale_wishlist/static/description/icon.png
  sale_wishlist/static/description/index.html
  sale_wishlist/tests/__init__.py
  sale_wishlist/tests/test_wishlist.py
  sale_wishlist/views/partner.xml
  sale_wishlist/views/product_set.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_wishlist/odoo/addons/sale_wishlist
  setup/sale_wishlist/setup.py
Labels: 15.0

#1162 Syncing from upstream OCA/sale-workflow (13.0)
  sale_coupon_product_management/models/sale_coupon_program.py
Labels: 13.0

#1163 Syncing from upstream OCA/sale-workflow (14.0)
  README.md
  sale_automatic_workflow/__manifest__.py
  sale_automatic_workflow/models/automatic_workflow_job.py
  sale_automatic_workflow_job/__manifest__.py
  sale_automatic_workflow_job/models/automatic_workflow_job.py
  sale_automatic_workflow_job/tests/test_auto_workflow_job.py
Labels: 14.0

#1165 [t132090] sale_order_lot_selection
  oca_dependencies.txt
  sale_order_lot_selection/README.rst
  sale_order_lot_selection/__init__.py
  sale_order_lot_selection/__manifest__.py
  sale_order_lot_selection/demo/sale_demo.xml
  sale_order_lot_selection/i18n/ca.po
  sale_order_lot_selection/i18n/de.po
  sale_order_lot_selection/i18n/el_GR.po
  sale_order_lot_selection/i18n/en.po
  sale_order_lot_selection/i18n/es.po
  sale_order_lot_selection/i18n/es_ES.po
  sale_order_lot_selection/i18n/es_MX.po
  sale_order_lot_selection/i18n/es_VE.po
  sale_order_lot_selection/i18n/fi.po
  sale_order_lot_selection/i18n/fr.po
  sale_order_lot_selection/i18n/gl.po
  sale_order_lot_selection/i18n/hr.po
  sale_order_lot_selection/i18n/hr_HR.po
  sale_order_lot_selection/i18n/hu.po
  sale_order_lot_selection/i18n/it.po
  sale_order_lot_selection/i18n/nl.po
  sale_order_lot_selection/i18n/nl_NL.po
  sale_order_lot_selection/i18n/pt.po
  sale_order_lot_selection/i18n/pt_BR.po
  sale_order_lot_selection/i18n/pt_PT.po
  sale_order_lot_selection/i18n/ro.po
  sale_order_lot_selection/i18n/sale_order_lot_selection.pot
  sale_order_lot_selection/i18n/sk.po
  sale_order_lot_selection/i18n/sl.po
  sale_order_lot_selection/i18n/tr.po
  sale_order_lot_selection/i18n/tr_TR.po
  sale_order_lot_selection/i18n/vi_VN.po
  sale_order_lot_selection/i18n/zh_CN.po
  sale_order_lot_selection/models/__init__.py
  sale_order_lot_selection/models/sale_order_line.py
  sale_order_lot_selection/readme/CONTRIBUTORS.rst
  sale_order_lot_selection/readme/DESCRIPTION.rst
  sale_order_lot_selection/readme/ROADMAP.rst
  sale_order_lot_selection/readme/USAGE.rst
  sale_order_lot_selection/static/description/icon.png
  sale_order_lot_selection/static/description/index.html
  sale_order_lot_selection/tests/__init__.py
  sale_order_lot_selection/tests/test_sale_order_lot_selection.py
  sale_order_lot_selection/view/sale_view.xml
  setup/sale_order_lot_selection/odoo/addons/sale_order_lot_selection
  setup/sale_order_lot_selection/setup.py
  test-requirements.txt
Labels: 15.0.project_sa_650

#1168 Syncing from upstream OCA/sale-workflow (13.0)
  README.md
  sale_manual_delivery/__manifest__.py
  sale_manual_delivery/models/sale_order.py
Labels: 13.0

#1169 Syncing from upstream OCA/sale-workflow (12.0)
  README.md
  sale_require_po_doc/__manifest__.py
  sale_require_po_doc/i18n/sale_require_po_doc.pot
  sale_require_po_doc/models/sale_order.py
Labels: 12.0

#1170 Syncing from upstream OCA/sale-workflow (13.0)
  README.md
  sale_invoice_plan/__manifest__.py
  sale_invoice_plan/models/sale.py
  sale_tier_validation/__manifest__.py
  sale_tier_validation/data/mail_data.xml
Labels: 13.0

#1171 Syncing from upstream OCA/sale-workflow (14.0)
  README.md
  sale_order_general_discount/__manifest__.py
  sale_order_general_discount/models/res_partner.py
  sale_order_general_discount/tests/test_sale_order_general_discount.py
  sale_tier_validation/__manifest__.py
  sale_tier_validation/data/mail_data.xml
  sale_tier_validation/i18n/es.po
  sale_tier_validation/i18n/sale_tier_validation.pot
  sale_tier_validation/i18n/sv.po
  sale_tier_validation/i18n/zh_CN.po
  sale_tier_validation/models/sale_order.py
  sale_tier_validation/tests/test_tier_validation.py
Labels: 14.0
