Repository brain-tec/sale-workflow, pull requests merged in 2022-04, with the labels that each got.

#1019 Syncing from upstream OCA/sale-workflow (14.0)
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .pre-commit-config.yaml
  README.md
  sale_automatic_workflow/models/automatic_workflow_job.py
  sale_automatic_workflow_job/models/queue_job.py
  sale_blanket_order/tests/test_blanket_orders.py
  sale_isolated_quotation/hooks.py
  sale_isolated_quotation/tests/test_sale_isolated_quotation.py
  sale_last_price_info/models/product.py
  sale_order_line_input/models/sale_order.py
  sale_procurement_group_by_line/model/sale.py
  sale_product_set/tests/test_product_set.py
  sale_product_set/wizard/product_set_add.py
  sale_stock_picking_note/tests/test_sale_stock_picking_note.py
  sales_team_security/hooks.py
Labels: 14.0

#1020 Syncing from upstream OCA/sale-workflow (15.0)
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  .t2d.yml
  README.md
Labels: 15.0

#1021 Syncing from upstream OCA/sale-workflow (14.0)
  README.md
  sale_partner_approval/README.rst
  sale_partner_approval/__manifest__.py
  sale_partner_approval/data/exception_rule.xml
  sale_partner_approval/data/init_sale_ok.xml
  sale_partner_approval/models/res_partner.py
  sale_partner_approval/readme/DESCRIPTION.rst
  sale_partner_approval/readme/USAGE.rst
  sale_partner_approval/static/description/index.html
  sale_partner_approval/tests/test_product_approval.py
  sale_partner_approval/views/res_partner.xml
Labels: 14.0

#1022 Syncing from upstream OCA/sale-workflow (14.0)
  README.md
  sale_blanket_order/__manifest__.py
  sale_blanket_order/wizard/create_sale_orders.py
  sale_restricted_qty/README.rst
  sale_restricted_qty/__init__.py
  sale_restricted_qty/__manifest__.py
  sale_restricted_qty/hooks.py
  sale_restricted_qty/i18n/it.po
  sale_restricted_qty/i18n/sale_order_min_qty.pot
  sale_restricted_qty/i18n/sale_restricted_qty.pot
  sale_restricted_qty/models/__init__.py
  sale_restricted_qty/models/product_category.py
  sale_restricted_qty/models/product_product.py
  sale_restricted_qty/models/product_restricted_qty_mixin.py
  sale_restricted_qty/models/product_template.py
  sale_restricted_qty/models/sale.py
  sale_restricted_qty/readme/CONTRIBUTORS.rst
  sale_restricted_qty/readme/DESCRIPTION.rst
  sale_restricted_qty/readme/USAGE.rst
  sale_restricted_qty/static/description/icon.png
  sale_restricted_qty/static/description/index.html
  sale_restricted_qty/tests/__init__.py
  sale_restricted_qty/tests/test_sale.py
  sale_restricted_qty/views/product_category_views.xml
  sale_restricted_qty/views/product_product_views.xml
  sale_restricted_qty/views/product_template_views.xml
  sale_restricted_qty/views/sale_views.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_restricted_qty/odoo/addons/sale_restricted_qty
  setup/sale_restricted_qty/setup.py
Labels: 14.0

#1023 Syncing from upstream OCA/sale-workflow (14.0)
  README.md
  sale_product_set/__manifest__.py
  sale_product_set/i18n/sale_product_set.pot
  sale_product_set/tests/test_product_set.py
  sale_product_set/wizard/product_set_add.py
Labels: 14.0

#1024 Syncing from upstream OCA/sale-workflow (13.0)
  README.md
  sale_advance_payment/README.rst
  sale_advance_payment/__init__.py
  sale_advance_payment/__manifest__.py
  sale_advance_payment/i18n/fr.po
  sale_advance_payment/i18n/sale_advance_payment.pot
  sale_advance_payment/models/__init__.py
  sale_advance_payment/models/payment.py
  sale_advance_payment/models/sale.py
  sale_advance_payment/readme/CONTRIBUTORS.rst
  sale_advance_payment/readme/DESCRIPTION.rst
  sale_advance_payment/readme/ROADMAP.rst
  sale_advance_payment/readme/USAGE.rst
  sale_advance_payment/security/ir.model.access.csv
  sale_advance_payment/static/description/icon.png
  sale_advance_payment/static/description/index.html
  sale_advance_payment/tests/__init__.py
  sale_advance_payment/tests/test_sale_advance_payment.py
  sale_advance_payment/views/sale_view.xml
  sale_advance_payment/wizard/__init__.py
  sale_advance_payment/wizard/sale_advance_payment_wzd.py
  sale_advance_payment/wizard/sale_advance_payment_wzd_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_advance_payment/odoo/addons/sale_advance_payment
  setup/sale_advance_payment/setup.py
Labels: 13.0

#1026 Syncing from upstream OCA/sale-workflow (12.0)
  sale_triple_discount/i18n/it.po
Labels: 12.0

#1027 Syncing from upstream OCA/sale-workflow (14.0)
  product_supplierinfo_for_customer_sale/i18n/it.po
  sale_exception/i18n/it.po
  sale_last_price_info/i18n/it.po
  sale_order_general_discount/i18n/it.po
  sale_order_line_date/i18n/it.po
  sale_order_line_description/i18n/it.po
  sale_order_lot_generator/i18n/it.po
  sale_order_lot_selection/i18n/it.po
  sale_order_priority/i18n/it.po
  sale_order_type/i18n/it.po
  sale_procurement_group_by_line/i18n/it.po
  sale_product_set/i18n/it.po
  sale_rental/i18n/it.po
  sale_restricted_qty/i18n/it.po
  sale_start_end_dates/i18n/it.po
  sale_stock_picking_blocking/i18n/it.po
  sale_triple_discount/i18n/it.po
Labels: 14.0

#1028 Updating from latest OCA 13.0
  README.md
  sale_advance_payment/README.rst
  sale_advance_payment/__init__.py
  sale_advance_payment/__manifest__.py
  sale_advance_payment/i18n/fr.po
  sale_advance_payment/i18n/sale_advance_payment.pot
  sale_advance_payment/models/__init__.py
  sale_advance_payment/models/payment.py
  sale_advance_payment/models/sale.py
  sale_advance_payment/readme/CONTRIBUTORS.rst
  sale_advance_payment/readme/DESCRIPTION.rst
  sale_advance_payment/readme/ROADMAP.rst
  sale_advance_payment/readme/USAGE.rst
  sale_advance_payment/security/ir.model.access.csv
  sale_advance_payment/static/description/icon.png
  sale_advance_payment/static/description/index.html
  sale_advance_payment/tests/__init__.py
  sale_advance_payment/tests/test_sale_advance_payment.py
  sale_advance_payment/views/sale_view.xml
  sale_advance_payment/wizard/__init__.py
  sale_advance_payment/wizard/sale_advance_payment_wzd.py
  sale_advance_payment/wizard/sale_advance_payment_wzd_view.xml
  sale_order_line_input/__manifest__.py
  sale_order_line_input/models/sale_order.py
  sale_procurement_amendment/README.rst
  sale_procurement_amendment/__init__.py
  sale_procurement_amendment/__manifest__.py
  sale_procurement_amendment/i18n/ca.po
  sale_procurement_amendment/i18n/es.po
  sale_procurement_amendment/i18n/sale_procurement_amendment.pot
  sale_procurement_amendment/models/__init__.py
  sale_procurement_amendment/models/sale_order_line.py
  sale_procurement_amendment/models/stock_move.py
  sale_procurement_amendment/models/stock_picking.py
  sale_procurement_amendment/readme/CONTRIBUTORS.rst
  sale_procurement_amendment/readme/DESCRIPTION.rst
  sale_procurement_amendment/readme/HISTORY.rst
  sale_procurement_amendment/readme/INSTALL.rst
  sale_procurement_amendment/readme/USAGE.rst
  sale_procurement_amendment/static/description/icon.png
  sale_procurement_amendment/static/description/index.html
  sale_procurement_amendment/tests/__init__.py
  sale_procurement_amendment/tests/test_sale_procurement_amendment.py
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_advance_payment/odoo/addons/sale_advance_payment
  setup/sale_advance_payment/setup.py
  setup/sale_procurement_amendment/odoo/addons/sale_procurement_amendment
  setup/sale_procurement_amendment/setup.py
Labels: 13.0.project_mi_465

#1030 Syncing from upstream OCA/sale-workflow (14.0)
  sale_start_end_dates/i18n/it.po
Labels: 14.0

#1031 Syncing from upstream OCA/sale-workflow (12.0)
  sale_promotion_rule/i18n/ca.po
Labels: 12.0

#1032 Syncing from upstream OCA/sale-workflow (14.0)
  README.md
  sale_amount_payment_link/__manifest__.py
  sale_amount_payment_link/tests/test_sale_amount_payment_link.py
  sale_invoice_plan/__manifest__.py
  sale_invoice_plan/tests/test_sale_invoice_plan.py
  sale_tier_validation/i18n/es.po
  sale_tier_validation/i18n/sale_tier_validation.pot
  sale_tier_validation/i18n/sv.po
  sale_tier_validation/i18n/zh_CN.po
Labels: 14.0

#1033 Syncing from upstream OCA/sale-workflow (14.0)
  sale_exception/i18n/it.po
Labels: 14.0

#1035 Update travis.yml for swig
  .travis.yml
Labels: 13.0.project_mi_465

#1036 Syncing from upstream OCA/sale-workflow (14.0)
  README.md
  sale_automatic_workflow_payment_mode/__manifest__.py
  sale_automatic_workflow_payment_mode/models/sale_order.py
  sale_automatic_workflow_payment_mode/tests/test_automatic_workflow_payment_mode.py
Labels: 14.0

#1037 Syncing from upstream OCA/sale-workflow (14.0)
  README.md
  sale_exception/i18n/it.po
  sale_isolated_quotation/i18n/it.po
  sale_order_archive/i18n/it.po
  sale_product_set/i18n/it.po
  sale_quotation_template_product_multi_add/README.rst
  sale_quotation_template_product_multi_add/__init__.py
  sale_quotation_template_product_multi_add/__manifest__.py
  sale_quotation_template_product_multi_add/i18n/it.po
  sale_quotation_template_product_multi_add/i18n/sale_quotation_template_product_multi_add.pot
  sale_quotation_template_product_multi_add/readme/CONTRIBUTORS.rst
  sale_quotation_template_product_multi_add/readme/DESCRIPTION.rst
  sale_quotation_template_product_multi_add/readme/USAGE.rst
  sale_quotation_template_product_multi_add/security/ir.model.access.csv
  sale_quotation_template_product_multi_add/static/description/icon.png
  sale_quotation_template_product_multi_add/static/description/index.html
  sale_quotation_template_product_multi_add/tests/__init__.py
  sale_quotation_template_product_multi_add/tests/test_sale.py
  sale_quotation_template_product_multi_add/views/sale_view.xml
  sale_quotation_template_product_multi_add/wizards/__init__.py
  sale_quotation_template_product_multi_add/wizards/sale_template_add_products.py
  sale_quotation_template_product_multi_add/wizards/sale_template_add_products_view.xml
  sale_rental/i18n/it.po
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_quotation_template_product_multi_add/odoo/addons/sale_quotation_template_product_multi_add
  setup/sale_quotation_template_product_multi_add/setup.py
Labels: 14.0
