Repository brain-tec/sale-workflow, pull requests merged in 2022-03, with the labels that each got.

#992 Syncing from upstream OCA/sale-workflow (14.0)
  README.md
  sale_default_uom/README.rst
  sale_default_uom/__init__.py
  sale_default_uom/__manifest__.py
  sale_default_uom/i18n/it.po
  sale_default_uom/i18n/sale_default_uom.pot
  sale_default_uom/models/__init__.py
  sale_default_uom/models/product_template.py
  sale_default_uom/models/sale_order_line.py
  sale_default_uom/readme/CONTRIBUTORS.rst
  sale_default_uom/readme/DESCRIPTION.rst
  sale_default_uom/readme/HISTORY.rst
  sale_default_uom/readme/USAGE.rst
  sale_default_uom/static/description/icon.png
  sale_default_uom/static/description/index.html
  sale_default_uom/tests/__init__.py
  sale_default_uom/tests/test_sale_order_line.py
  sale_default_uom/views/product_template_view.xml
  sale_global_discount/README.rst
  sale_global_discount/__init__.py
  sale_global_discount/__manifest__.py
  sale_global_discount/i18n/es.po
  sale_global_discount/i18n/pt.po
  sale_global_discount/i18n/sale_global_discount.pot
  sale_global_discount/models/__init__.py
  sale_global_discount/models/sale_order.py
  sale_global_discount/readme/CONFIGURE.rst
  sale_global_discount/readme/CONTRIBUTORS.rst
  sale_global_discount/readme/DESCRIPTION.rst
  sale_global_discount/readme/ROADMAP.rst
  sale_global_discount/readme/USAGE.rst
  sale_global_discount/static/description/icon.png
  sale_global_discount/static/description/icon.svg
  sale_global_discount/static/description/index.html
  sale_global_discount/tests/__init__.py
  sale_global_discount/tests/test_sale_global_discount.py
  sale_global_discount/views/report_sale_order.xml
  sale_global_discount/views/sale_order_views.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_default_uom/odoo/addons/sale_default_uom
  setup/sale_default_uom/setup.py
  setup/sale_global_discount/odoo/addons/sale_global_discount
  setup/sale_global_discount/setup.py
Labels: 14.0

#993 Syncing from upstream OCA/sale-workflow (12.0)
  sale_invoice_policy/i18n/it.po
Labels: 12.0

#994 Syncing from upstream OCA/sale-workflow (14.0)
  sale_default_uom/i18n/it.po
  sale_global_discount/i18n/it.po
  sale_procurement_group_by_line/i18n/it.po
Labels: 14.0

#995 Syncing from upstream OCA/sale-workflow (14.0)
  README.md
  sale_partner_approval/README.rst
  sale_partner_approval/__init__.py
  sale_partner_approval/__manifest__.py
  sale_partner_approval/data/exception_rule.xml
  sale_partner_approval/i18n/sale_partner_approval.pot
  sale_partner_approval/models/__init__.py
  sale_partner_approval/models/res_partner.py
  sale_partner_approval/models/res_partner_stage.py
  sale_partner_approval/models/sale_order.py
  sale_partner_approval/readme/CONFIGURE.rst
  sale_partner_approval/readme/CONTRIBUTORS.rst
  sale_partner_approval/readme/DESCRIPTION.rst
  sale_partner_approval/readme/USAGE.rst
  sale_partner_approval/static/description/icon.png
  sale_partner_approval/static/description/index.html
  sale_partner_approval/tests/__init__.py
  sale_partner_approval/tests/test_product_approval.py
  sale_partner_approval/views/res_partner.xml
  sale_partner_approval/views/res_partner_stage.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_partner_approval/odoo/addons/sale_partner_approval
  setup/sale_partner_approval/setup.py
Labels: 14.0

#996 Syncing from upstream OCA/sale-workflow (13.0)
  README.md
  sale_product_set/__manifest__.py
  sale_product_set/tests/test_product_set.py
  sale_product_set/wizard/product_set_add.py
Labels: 13.0

#997 Syncing from upstream OCA/sale-workflow (13.0)
  README.md
  sale_order_type/__manifest__.py
  sale_order_type/models/sale.py
Labels: 13.0

#998 Syncing from upstream OCA/sale-workflow (13.0)
  README.md
  sale_product_set/__manifest__.py
  sale_product_set/i18n/sale_product_set.pot
  sale_product_set/views/product_set.xml
Labels: 13.0

#999 Syncing from upstream OCA/sale-workflow (14.0)
  README.md
  sale_product_set/__manifest__.py
  sale_product_set/views/product_set.xml
Labels: 14.0

#1000 Updating from latest OCA 13.0
  README.md
  sale_order_type/__manifest__.py
  sale_order_type/models/sale.py
  sale_product_set/__manifest__.py
  sale_product_set/i18n/sale_product_set.pot
  sale_product_set/tests/test_product_set.py
  sale_product_set/views/product_set.xml
  sale_product_set/wizard/product_set_add.py
Labels: 13.0.project_mi_465

#1001 Syncing from upstream OCA/sale-workflow (13.0)
  README.md
  sale_order_price_recalculation/README.rst
  sale_order_price_recalculation/__init__.py
  sale_order_price_recalculation/__manifest__.py
  sale_order_price_recalculation/i18n/ca.po
  sale_order_price_recalculation/i18n/de.po
  sale_order_price_recalculation/i18n/el_GR.po
  sale_order_price_recalculation/i18n/en.po
  sale_order_price_recalculation/i18n/es.po
  sale_order_price_recalculation/i18n/es_ES.po
  sale_order_price_recalculation/i18n/es_VE.po
  sale_order_price_recalculation/i18n/fi.po
  sale_order_price_recalculation/i18n/fr.po
  sale_order_price_recalculation/i18n/hr.po
  sale_order_price_recalculation/i18n/hr_HR.po
  sale_order_price_recalculation/i18n/hu.po
  sale_order_price_recalculation/i18n/it.po
  sale_order_price_recalculation/i18n/nl.po
  sale_order_price_recalculation/i18n/nl_NL.po
  sale_order_price_recalculation/i18n/pt.po
  sale_order_price_recalculation/i18n/pt_BR.po
  sale_order_price_recalculation/i18n/ro.po
  sale_order_price_recalculation/i18n/sale_order_price_recalculation.pot
  sale_order_price_recalculation/i18n/sl.po
  sale_order_price_recalculation/i18n/tr.po
  sale_order_price_recalculation/i18n/tr_TR.po
  sale_order_price_recalculation/i18n/vi_VN.po
  sale_order_price_recalculation/i18n/zh_CN.po
  sale_order_price_recalculation/models/__init__.py
  sale_order_price_recalculation/models/sale_order.py
  sale_order_price_recalculation/readme/CONTRIBUTORS.rst
  sale_order_price_recalculation/readme/DESCRIPTION.rst
  sale_order_price_recalculation/readme/INSTALL.rst
  sale_order_price_recalculation/readme/ROADMAP.rst
  sale_order_price_recalculation/readme/USAGE.rst
  sale_order_price_recalculation/static/description/icon.png
  sale_order_price_recalculation/static/description/index.html
  sale_order_price_recalculation/static/description/sale_order_price_recalculation.png
  sale_order_price_recalculation/tests/__init__.py
  sale_order_price_recalculation/tests/test_sale_order_price_recalculation.py
  sale_order_price_recalculation/views/sale_order_view.xml
  sale_product_set/__manifest__.py
  sale_product_set/security/rule_product_set.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_order_price_recalculation/odoo/addons/sale_order_price_recalculation
  setup/sale_order_price_recalculation/setup.py
Labels: 13.0

#1002 Syncing from upstream OCA/sale-workflow (14.0)
  README.md
  sale_product_set/__manifest__.py
  sale_product_set/security/rule_product_set.xml
Labels: 14.0

#1003 Syncing from upstream OCA/sale-workflow (11.0)
  .travis.yml
  sale_sourced_by_line/README.rst
  sale_sourced_by_line/__init__.py
  sale_sourced_by_line/__manifest__.py
  sale_sourced_by_line/i18n/ca.po
  sale_sourced_by_line/i18n/de.po
  sale_sourced_by_line/i18n/el_GR.po
  sale_sourced_by_line/i18n/es.po
  sale_sourced_by_line/i18n/es_ES.po
  sale_sourced_by_line/i18n/es_VE.po
  sale_sourced_by_line/i18n/fi.po
  sale_sourced_by_line/i18n/fr.po
  sale_sourced_by_line/i18n/hr.po
  sale_sourced_by_line/i18n/hr_HR.po
  sale_sourced_by_line/i18n/hu.po
  sale_sourced_by_line/i18n/it.po
  sale_sourced_by_line/i18n/nl.po
  sale_sourced_by_line/i18n/nl_NL.po
  sale_sourced_by_line/i18n/pt.po
  sale_sourced_by_line/i18n/pt_BR.po
  sale_sourced_by_line/i18n/ro.po
  sale_sourced_by_line/i18n/sale_sourced_by_line.pot
  sale_sourced_by_line/i18n/sk.po
  sale_sourced_by_line/i18n/sl.po
  sale_sourced_by_line/i18n/tr.po
  sale_sourced_by_line/i18n/tr_TR.po
  sale_sourced_by_line/i18n/vi_VN.po
  sale_sourced_by_line/i18n/zh_CN.po
  sale_sourced_by_line/model/__init__.py
  sale_sourced_by_line/model/sale.py
  sale_sourced_by_line/static/description/icon.png
  sale_sourced_by_line/test/sale_order_multi_source.yml
  sale_sourced_by_line/test/sale_order_not_sourced.yml
  sale_sourced_by_line/test/sale_order_source.yml
  sale_sourced_by_line/tests/__init__.py
  sale_sourced_by_line/tests/test_sale_is_delivered.py
  sale_sourced_by_line/tests/test_sale_sourced_by_line.py
  sale_sourced_by_line/view/sale_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_sourced_by_line/odoo/addons/sale_sourced_by_line
  setup/sale_sourced_by_line/setup.cfg
  setup/sale_sourced_by_line/setup.py
Labels: 11.0

#1004 Syncing from upstream OCA/sale-workflow (12.0)
  sale_order_line_price_history/i18n/fr.po
Labels: 12.0

#1005 Syncing from upstream OCA/sale-workflow (13.0)
  README.md
  sale_stock_picking_validation_blocking/README.rst
  sale_stock_picking_validation_blocking/__init__.py
  sale_stock_picking_validation_blocking/__manifest__.py
  sale_stock_picking_validation_blocking/i18n/sale_stock_picking_validation_blocking.pot
  sale_stock_picking_validation_blocking/models/__init__.py
  sale_stock_picking_validation_blocking/models/sale_order.py
  sale_stock_picking_validation_blocking/models/stock_picking.py
  sale_stock_picking_validation_blocking/readme/CONTRIBUTORS.rst
  sale_stock_picking_validation_blocking/readme/DESCRIPTION.rst
  sale_stock_picking_validation_blocking/readme/USAGE.rst
  sale_stock_picking_validation_blocking/static/description/icon.png
  sale_stock_picking_validation_blocking/static/description/index.html
  sale_stock_picking_validation_blocking/tests/__init__.py
  sale_stock_picking_validation_blocking/tests/test_sale_stock.py
  sale_stock_picking_validation_blocking/views/sale_order.xml
  sale_stock_picking_validation_blocking/views/stock_picking.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_stock_picking_validation_blocking/odoo/addons/sale_stock_picking_validation_blocking
  setup/sale_stock_picking_validation_blocking/setup.py
Labels: 13.0

#1007 Syncing from upstream OCA/sale-workflow (13.0)
  README.md
  sale_order_line_packaging_qty/__manifest__.py
  sale_order_line_packaging_qty/models/sale_order_line.py
  sale_order_line_packaging_qty/tests/test_sale_order_line_packaging_qty.py
Labels: 13.0

#1008 Syncing from upstream OCA/sale-workflow (14.0)
  README.md
  sale_commitment_date_mandatory/README.rst
  sale_commitment_date_mandatory/__manifest__.py
  sale_commitment_date_mandatory/readme/DESCRIPTION.rst
  sale_commitment_date_mandatory/static/description/index.html
  sale_order_lot_selection/__manifest__.py
  sale_order_lot_selection/view/sale_view.xml
Labels: 14.0

#1009 Syncing from upstream OCA/sale-workflow (15.0)
  README.md
  sale_order_line_date/__manifest__.py
  sale_order_line_date/models/sale_order.py
  sale_order_line_date/models/sale_order_line.py
  sale_order_line_date/tests/test_sale_order_line_date.py
Labels: 15.0

#1010 Syncing from upstream OCA/sale-workflow (12.0)
  README.md
  sale_global_discount/__manifest__.py
Labels: 12.0

#1011 Syncing from upstream OCA/sale-workflow (15.0)
  sale_order_line_date/i18n/ca.po
  sale_order_type/i18n/ca.po
  sale_procurement_group_by_line/i18n/ca.po
Labels: 15.0

#1012 Syncing from upstream OCA/sale-workflow (13.0)
  README.md
  sale_order_price_recalculation/i18n/ca.po
  sale_order_type/__manifest__.py
  sale_order_type/models/sale.py
  sale_product_set/__manifest__.py
  sale_product_set/i18n/es.po
  sale_product_set/models/product_set.py
Labels: 13.0

#1013 Syncing from upstream OCA/sale-workflow (14.0)
  README.md
  sale_product_set/__manifest__.py
  sale_product_set/i18n/es.po
  sale_product_set/models/product_set.py
Labels: 14.0

#1015 Syncing from upstream OCA/sale-workflow (14.0)
  README.md
  sale_procurement_amendment/README.rst
  sale_procurement_amendment/__init__.py
  sale_procurement_amendment/__manifest__.py
  sale_procurement_amendment/i18n/ca.po
  sale_procurement_amendment/i18n/es.po
  sale_procurement_amendment/i18n/sale_procurement_amendment.pot
  sale_procurement_amendment/models/__init__.py
  sale_procurement_amendment/models/sale_order_line.py
  sale_procurement_amendment/models/stock_move.py
  sale_procurement_amendment/models/stock_picking.py
  sale_procurement_amendment/readme/CONTRIBUTORS.rst
  sale_procurement_amendment/readme/DESCRIPTION.rst
  sale_procurement_amendment/readme/HISTORY.rst
  sale_procurement_amendment/readme/INSTALL.rst
  sale_procurement_amendment/readme/USAGE.rst
  sale_procurement_amendment/static/description/icon.png
  sale_procurement_amendment/static/description/index.html
  sale_procurement_amendment/tests/__init__.py
  sale_procurement_amendment/tests/test_sale_procurement_amendment.py
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_procurement_amendment/odoo/addons/sale_procurement_amendment
  setup/sale_procurement_amendment/setup.py
Labels: 14.0

#1016 Syncing from upstream OCA/sale-workflow (13.0)
  README.md
  sale_order_line_input/__manifest__.py
  sale_order_line_input/models/sale_order.py
Labels: 13.0

#1017 Syncing from upstream OCA/sale-workflow (14.0)
  README.md
  sale_order_line_initial_quantity/README.rst
  sale_order_line_initial_quantity/__init__.py
  sale_order_line_initial_quantity/__manifest__.py
  sale_order_line_initial_quantity/i18n/sale_order_line_initial_quantity.pot
  sale_order_line_initial_quantity/models/__init__.py
  sale_order_line_initial_quantity/models/sale_order.py
  sale_order_line_initial_quantity/models/sale_order_line.py
  sale_order_line_initial_quantity/readme/CONFIGURE.rst
  sale_order_line_initial_quantity/readme/CONTRIBUTORS.rst
  sale_order_line_initial_quantity/readme/DESCRIPTION.rst
  sale_order_line_initial_quantity/readme/USAGE.rst
  sale_order_line_initial_quantity/static/description/icon.png
  sale_order_line_initial_quantity/static/description/index.html
  sale_order_line_initial_quantity/tests/__init__.py
  sale_order_line_initial_quantity/tests/test_sale_order_line_initial_quantity.py
  sale_order_line_initial_quantity/views/sale.xml
  sale_pricelist_from_commitment_date/__manifest__.py
  sale_pricelist_from_commitment_date/models/sale_order.py
  sale_pricelist_from_commitment_date/tests/test_pricelist_from_commitment_date.py
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_order_line_initial_quantity/odoo/addons/sale_order_line_initial_quantity
  setup/sale_order_line_initial_quantity/setup.py
Labels: 14.0

#1018 Syncing from upstream OCA/sale-workflow (13.0)
  README.md
  sale_procurement_amendment/README.rst
  sale_procurement_amendment/__init__.py
  sale_procurement_amendment/__manifest__.py
  sale_procurement_amendment/i18n/ca.po
  sale_procurement_amendment/i18n/es.po
  sale_procurement_amendment/i18n/sale_procurement_amendment.pot
  sale_procurement_amendment/models/__init__.py
  sale_procurement_amendment/models/sale_order_line.py
  sale_procurement_amendment/models/stock_move.py
  sale_procurement_amendment/models/stock_picking.py
  sale_procurement_amendment/readme/CONTRIBUTORS.rst
  sale_procurement_amendment/readme/DESCRIPTION.rst
  sale_procurement_amendment/readme/HISTORY.rst
  sale_procurement_amendment/readme/INSTALL.rst
  sale_procurement_amendment/readme/USAGE.rst
  sale_procurement_amendment/static/description/icon.png
  sale_procurement_amendment/static/description/index.html
  sale_procurement_amendment/tests/__init__.py
  sale_procurement_amendment/tests/test_sale_procurement_amendment.py
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_procurement_amendment/odoo/addons/sale_procurement_amendment
  setup/sale_procurement_amendment/setup.py
Labels: 13.0
