Repository brain-tec/sale-workflow, pull requests merged in 2022-08, with the labels that each got.

#1112 Syncing from upstream OCA/sale-workflow (14.0)
  README.md
  sale_order_invoicing_finished_task/__manifest__.py
  sale_order_invoicing_finished_task/views/product_view.xml
Labels: 14.0

#1115 Removing test-requirements as it has been already merged in OCA 15.0
  test-requirements.txt
Labels: bug, 15.0.project_mi_465

#1116 Syncing from upstream OCA/sale-workflow (12.0)
  sale_order_line_input/i18n/fr.po
Labels: 12.0

#1117 Syncing from upstream OCA/sale-workflow (13.0)
  product_form_sale_link/i18n/nb.po
  product_form_sale_link/i18n/nb_NO.po
  sale_force_invoiced/i18n/nb_NO.po
Labels: 13.0

#1118 Syncing from upstream OCA/sale-workflow (14.0)
  sale_delivery_state/i18n/fr.po
Labels: 14.0

#1119 Syncing from upstream OCA/sale-workflow (12.0)
  README.md
  sale_order_rename/README.rst
  sale_order_rename/__manifest__.py
  sale_order_rename/readme/CONTRIBUTORS.rst
  sale_order_rename/static/description/index.html
Labels: 12.0

#1120 Syncing from upstream OCA/sale-workflow (13.0)
  README.md
  sale_order_type/__manifest__.py
  sale_order_type/models/sale.py
  sale_order_type/tests/test_sale_order_type.py
Labels: 13.0

#1121 Syncing from upstream OCA/sale-workflow (13.0)
  README.md
  sale_payment_sheet/__manifest__.py
  sale_payment_sheet/i18n/es.po
  sale_payment_sheet/i18n/sale_payment_sheet.pot
  sale_payment_sheet/wizards/sale_invoice_payment.py
  sale_payment_sheet/wizards/sale_invoice_payment_view.xml
Labels: 13.0

#1122 Syncing from upstream OCA/sale-workflow (14.0)
  README.md
  sale_order_general_discount_triple/__manifest__.py
  sale_order_general_discount_triple/models/sale_order.py
Labels: 14.0

#1124 Syncing from upstream OCA/sale-workflow (12.0)
  sale_invoice_plan/i18n/pt_BR.po
Labels: 12.0

#1125 Syncing from upstream OCA/sale-workflow (14.0)
  sale_advance_payment/i18n/pt_BR.po
Labels: 14.0

#1126 Syncing from upstream OCA/sale-workflow (15.0)
  README.md
  sale_invoice_plan/tests/test_sale_invoice_plan.py
  sale_order_qty_change_no_recompute/tests/test_sale_order_qty_change.py
  sale_order_secondary_unit/README.rst
  sale_order_secondary_unit/__init__.py
  sale_order_secondary_unit/__manifest__.py
  sale_order_secondary_unit/i18n/de.po
  sale_order_secondary_unit/i18n/es.po
  sale_order_secondary_unit/i18n/sale_order_secondary_unit.pot
  sale_order_secondary_unit/i18n/zh_CN.po
  sale_order_secondary_unit/models/__init__.py
  sale_order_secondary_unit/models/product_template.py
  sale_order_secondary_unit/models/sale_order.py
  sale_order_secondary_unit/readme/CONTRIBUTORS.rst
  sale_order_secondary_unit/readme/DESCRIPTION.rst
  sale_order_secondary_unit/readme/USAGE.rst
  sale_order_secondary_unit/report/sale_report_templates.xml
  sale_order_secondary_unit/static/description/icon.png
  sale_order_secondary_unit/static/description/index.html
  sale_order_secondary_unit/tests/__init__.py
  sale_order_secondary_unit/tests/test_sale_order_secondary_unit.py
  sale_order_secondary_unit/views/product_views.xml
  sale_order_secondary_unit/views/sale_order_views.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_order_secondary_unit/odoo/addons/sale_order_secondary_unit
  setup/sale_order_secondary_unit/setup.py
Labels: 15.0

#1129 [FIX] Removed .travis.yml
  .travis.yml
Labels: 13.0.project_mi_465

#1128 Backmerging 13.0 into 13.0.project_MI_465
  README.md
  product_form_sale_link/i18n/nb.po
  product_form_sale_link/i18n/nb_NO.po
  sale_force_invoiced/i18n/nb_NO.po
  sale_order_type/__manifest__.py
  sale_order_type/models/sale.py
  sale_order_type/tests/test_sale_order_type.py
  sale_payment_sheet/__manifest__.py
  sale_payment_sheet/i18n/es.po
  sale_payment_sheet/i18n/sale_payment_sheet.pot
  sale_payment_sheet/wizards/sale_invoice_payment.py
  sale_payment_sheet/wizards/sale_invoice_payment_view.xml
Labels: 13.0.project_mi_465

#1131 Syncing from upstream OCA/sale-workflow (15.0)
  README.md
  sale_procurement_group_by_line/__manifest__.py
  sale_procurement_group_by_line/i18n/ca.po
  sale_procurement_group_by_line/i18n/de.po
  sale_procurement_group_by_line/i18n/el_GR.po
  sale_procurement_group_by_line/i18n/es.po
  sale_procurement_group_by_line/i18n/es_ES.po
  sale_procurement_group_by_line/i18n/es_VE.po
  sale_procurement_group_by_line/i18n/fi.po
  sale_procurement_group_by_line/i18n/fr.po
  sale_procurement_group_by_line/i18n/hr.po
  sale_procurement_group_by_line/i18n/hr_HR.po
  sale_procurement_group_by_line/i18n/hu.po
  sale_procurement_group_by_line/i18n/it.po
  sale_procurement_group_by_line/i18n/nl.po
  sale_procurement_group_by_line/i18n/nl_NL.po
  sale_procurement_group_by_line/i18n/pt.po
  sale_procurement_group_by_line/i18n/pt_BR.po
  sale_procurement_group_by_line/i18n/ro.po
  sale_procurement_group_by_line/i18n/sale_procurement_group_by_line.pot
  sale_procurement_group_by_line/i18n/sk.po
  sale_procurement_group_by_line/i18n/sl.po
  sale_procurement_group_by_line/i18n/tr.po
  sale_procurement_group_by_line/i18n/tr_TR.po
  sale_procurement_group_by_line/i18n/vi_VN.po
  sale_procurement_group_by_line/i18n/zh_CN.po
  sale_procurement_group_by_line/model/__init__.py
  sale_procurement_group_by_line/model/sale.py
  sale_procurement_group_by_line/model/stock_move.py
  sale_procurement_group_by_line/tests/test_sale_procurement_group_by_line.py
Labels: 15.0

#1132 Syncing from upstream OCA/sale-workflow (14.0)
  README.md
  sale_order_type/__manifest__.py
  sale_order_type/models/sale.py
  sale_order_type/tests/test_sale_order_type.py
Labels: 14.0

#1133 Syncing from upstream OCA/sale-workflow (15.0)
  README.md
  sale_order_type/__manifest__.py
  sale_order_type/models/sale.py
  sale_order_type/tests/test_sale_order_type.py
Labels: 15.0

#1134 Syncing from upstream OCA/sale-workflow (13.0)
  README.md
  sale_blanket_order/__manifest__.py
  sale_blanket_order/wizard/create_sale_orders.py
Labels: 13.0

#1135 Syncing from upstream OCA/sale-workflow (15.0)
  README.md
  sale_blanket_order/__manifest__.py
  sale_blanket_order/wizard/create_sale_orders.py
  sale_order_line_menu/README.rst
  sale_order_line_menu/__init__.py
  sale_order_line_menu/__manifest__.py
  sale_order_line_menu/i18n/es.po
  sale_order_line_menu/i18n/fr.po
  sale_order_line_menu/i18n/fr_BE.po
  sale_order_line_menu/i18n/fr_FR.po
  sale_order_line_menu/i18n/sale_order_line_menu.pot
  sale_order_line_menu/readme/CONTRIBUTORS.rst
  sale_order_line_menu/readme/DESCRIPTION.rst
  sale_order_line_menu/readme/USAGE.rst
  sale_order_line_menu/static/description/icon.png
  sale_order_line_menu/static/description/index.html
  sale_order_line_menu/views/sale_order_line_views.xml
  sale_payment_sheet/README.rst
  sale_payment_sheet/__init__.py
  sale_payment_sheet/__manifest__.py
  sale_payment_sheet/i18n/es.po
  sale_payment_sheet/i18n/sale_payment_sheet.pot
  sale_payment_sheet/models/__init__.py
  sale_payment_sheet/models/res_users.py
  sale_payment_sheet/models/sale_payment_sheet.py
  sale_payment_sheet/readme/CONFIGURE.rst
  sale_payment_sheet/readme/CONTRIBUTORS.rst
  sale_payment_sheet/readme/DESCRIPTION.rst
  sale_payment_sheet/readme/USAGE.rst
  sale_payment_sheet/report/report_sale_payment_sheet_summary.xml
  sale_payment_sheet/report/sale_payment_sheet_report.xml
  sale_payment_sheet/security/ir.model.access.csv
  sale_payment_sheet/security/security.xml
  sale_payment_sheet/static/description/icon.png
  sale_payment_sheet/static/description/index.html
  sale_payment_sheet/tests/__init__.py
  sale_payment_sheet/tests/test_sale_payment_sheet.py
  sale_payment_sheet/views/res_users_views.xml
  sale_payment_sheet/views/sale_payment_sheet_menu.xml
  sale_payment_sheet/views/sale_payment_sheet_views.xml
  sale_payment_sheet/wizards/__init__.py
  sale_payment_sheet/wizards/sale_invoice_payment.py
  sale_payment_sheet/wizards/sale_invoice_payment_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_order_line_menu/odoo/addons/sale_order_line_menu
  setup/sale_order_line_menu/setup.py
  setup/sale_payment_sheet/odoo/addons/sale_payment_sheet
  setup/sale_payment_sheet/setup.py
Labels: 15.0

#1136 Syncing from upstream OCA/sale-workflow (14.0)
  .copier-answers.yml
  .gitignore
  .pre-commit-config.yaml
  README.md
  sale_order_line_discount_validation/__manifest__.py
  sale_order_line_discount_validation/report/sale_report.py
Labels: 14.0

#1137 Syncing from upstream OCA/sale-workflow (15.0)
  sale_blanket_order/i18n/fr_FR.po
Labels: 15.0

#1138 Syncing from upstream OCA/sale-workflow (12.0)
  README.md
  sale_blanket_order/__manifest__.py
  sale_blanket_order/i18n/de.po
  sale_blanket_order/i18n/es.po
  sale_blanket_order/i18n/fr_FR.po
  sale_blanket_order/i18n/it.po
  sale_blanket_order/i18n/pt.po
  sale_blanket_order/i18n/sale_blanket_order.pot
  sale_blanket_order/models/__init__.py
  sale_blanket_order/models/sale_order.py
  sale_blanket_order/models/sale_order_line.py
Labels: 12.0

#1139 Syncing from upstream OCA/sale-workflow (14.0)
  README.md
  sale_cancel_reason/__manifest__.py
  sale_cancel_reason/model/sale.py
  sale_order_line_input/i18n/it.po
Labels: 14.0

#1141 Backmerging 13.0 into 13.0.project_MI_465
  README.md
  sale_blanket_order/__manifest__.py
  sale_blanket_order/wizard/create_sale_orders.py
Labels: 13.0.project_mi_465
