Repository brain-tec/sale-workflow, pull requests merged in 2023-10, with the labels that each got.

#1645 Syncing from upstream OCA/sale-workflow (15.0)
  README.md
  sale_planner_calendar/README.rst
  sale_planner_calendar/__manifest__.py
  sale_planner_calendar/models/sale_planner_calendar_event.py
  sale_planner_calendar/static/description/index.html
  sale_planner_calendar/static/src/js/sale_planner_calendar_event_sales.js
Labels: 15.0

#1646 Syncing from upstream OCA/sale-workflow (16.0)
  README.md
  sale_fixed_discount/README.rst
  sale_fixed_discount/__init__.py
  sale_fixed_discount/__manifest__.py
  sale_fixed_discount/i18n/es.po
  sale_fixed_discount/i18n/fr.po
  sale_fixed_discount/i18n/sale_fixed_discount.pot
  sale_fixed_discount/models/__init__.py
  sale_fixed_discount/models/sale_order_line.py
  sale_fixed_discount/readme/CONFIGURE.rst
  sale_fixed_discount/readme/CONTRIBUTORS.rst
  sale_fixed_discount/readme/DESCRIPTION.rst
  sale_fixed_discount/readme/INSTALL.rst
  sale_fixed_discount/readme/USAGE.rst
  sale_fixed_discount/reports/report_sale_order.xml
  sale_fixed_discount/security/res_groups.xml
  sale_fixed_discount/static/description/icon.png
  sale_fixed_discount/static/description/index.html
  sale_fixed_discount/tests/__init__.py
  sale_fixed_discount/tests/test_sale_fixed_discount.py
  sale_fixed_discount/views/account_invoice_views.xml
  sale_fixed_discount/views/sale_order_views.xml
  sale_fixed_discount/views/sale_portal_templates.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_fixed_discount/odoo/addons/sale_fixed_discount
  setup/sale_fixed_discount/setup.py
Labels: 16.0

#1647 Syncing from upstream OCA/sale-workflow (16.0)
  README.md
  sale_quotation_number/README.rst
  sale_quotation_number/__manifest__.py
  sale_quotation_number/models/sale_order.py
  sale_quotation_number/static/description/index.html
  sale_quotation_number/tests/test_sale_order.py
Labels: 16.0

#1648 Syncing from upstream OCA/sale-workflow (15.0)
  README.md
  sale_invoice_frequency/README.rst
  sale_invoice_frequency/__init__.py
  sale_invoice_frequency/__manifest__.py
  sale_invoice_frequency/data/sale_invoice_frequency_data.xml
  sale_invoice_frequency/i18n/es.po
  sale_invoice_frequency/i18n/sale_invoice_frequency.pot
  sale_invoice_frequency/models/__init__.py
  sale_invoice_frequency/models/res_partner.py
  sale_invoice_frequency/models/sale_invoice_frequency.py
  sale_invoice_frequency/models/sale_order.py
  sale_invoice_frequency/readme/CONTRIBUTORS.rst
  sale_invoice_frequency/readme/DESCRIPTION.rst
  sale_invoice_frequency/readme/ROADMAP.rst
  sale_invoice_frequency/readme/USAGE.rst
  sale_invoice_frequency/security/ir.model.access.csv
  sale_invoice_frequency/static/description/icon.png
  sale_invoice_frequency/static/description/index.html
  sale_invoice_frequency/views/res_partner_view.xml
  sale_invoice_frequency/views/sale_invoice_frequency_view.xml
  sale_invoice_frequency/views/sale_order_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_invoice_frequency/odoo/addons/sale_invoice_frequency
  setup/sale_invoice_frequency/setup.py
Labels: 15.0

#1651 Update README in project branch
  README.md
Labels: 16.0.project_ba_688

#1652 Syncing from upstream OCA/sale-workflow (15.0)
  README.md
  sale_planner_calendar/README.rst
  sale_planner_calendar/__manifest__.py
  sale_planner_calendar/models/calendar.py
  sale_planner_calendar/models/res_partner.py
  sale_planner_calendar/static/description/index.html
  sale_planner_calendar/views/calendar_view.xml
  sale_planner_calendar/wizard/sale_planner_calendar_reassign.py
  sale_planner_calendar/wizard/sale_planner_calendar_wizard.py
Labels: 15.0

#1653 Syncing from upstream OCA/sale-workflow (16.0)
  README.md
  sale_commercial_partner/README.rst
  sale_commercial_partner/__manifest__.py
  sale_commercial_partner/static/description/index.html
Labels: 16.0

#1654 Syncing from upstream OCA/sale-workflow (14.0)
  sale_by_packaging/i18n/it.po
  sale_default_uom/i18n/it.po
  sale_discount_display_amount/i18n/it.po
  sale_order_lot_selection/i18n/it.po
  sale_restricted_qty/i18n/it.po
Labels: 14.0

#1655 Syncing from upstream OCA/sale-workflow (8.0)
  sale_properties_easy_creation/i18n/it.po
  sale_start_end_dates/i18n/it.po
Labels: 8.0

#1656 Syncing from upstream OCA/sale-workflow (9.0)
  sale_sourced_by_line/i18n/it.po
  sale_start_end_dates/i18n/it.po
Labels: 9.0

#1657 Syncing from upstream OCA/sale-workflow (10.0)
  sale_start_end_dates/i18n/it.po
Labels: 10.0

#1658 Syncing from upstream OCA/sale-workflow (11.0)
  sale_start_end_dates/i18n/it.po
Labels: 11.0

#1664 Syncing from upstream OCA/sale-workflow (14.0)
  README.md
  sale_stock_return_request/README.rst
  sale_stock_return_request/__init__.py
  sale_stock_return_request/__manifest__.py
  sale_stock_return_request/i18n/ca.po
  sale_stock_return_request/i18n/es.po
  sale_stock_return_request/i18n/fr.po
  sale_stock_return_request/i18n/sale_stock_return_request.pot
  sale_stock_return_request/models/__init__.py
  sale_stock_return_request/models/stock_return_request.py
  sale_stock_return_request/readme/CONTRIBUTORS.rst
  sale_stock_return_request/readme/DESCRIPTION.rst
  sale_stock_return_request/readme/USAGE.rst
  sale_stock_return_request/static/description/icon.png
  sale_stock_return_request/static/description/index.html
  sale_stock_return_request/tests/__init__.py
  sale_stock_return_request/tests/test_stock_return_request.py
  sale_stock_return_request/views/sale_return_request_views.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_stock_return_request/odoo/addons/sale_stock_return_request
  setup/sale_stock_return_request/setup.py
Labels: 14.0

#1665 Syncing from upstream OCA/sale-workflow (15.0)
  README.md
  sale_force_invoiced/i18n/es.po
  sale_invoice_policy/i18n/es.po
  sale_order_line_delivery_state/i18n/es.po
  sale_order_line_price_history/i18n/es.po
  sale_order_line_sequence/i18n/es.po
  sale_order_revision/i18n/es.po
  sale_product_set_layout/i18n/es.po
  sale_rental/i18n/es.po
  sale_resource_booking/i18n/es.po
  sale_sourced_by_line/i18n/es.po
  sale_start_end_dates/i18n/es.po
  sale_stock_return_request/README.rst
  sale_stock_return_request/__manifest__.py
  sale_stock_return_request/models/stock_return_request.py
  sale_stock_return_request/static/description/index.html
Labels: 15.0

#1666 Syncing from upstream OCA/sale-workflow (12.0)
  sale_order_tag/i18n/it.po
Labels: 12.0

#1667 Syncing from upstream OCA/sale-workflow (13.0)
  sale_order_tag/i18n/it.po
Labels: 13.0

#1668 Syncing from upstream OCA/sale-workflow (14.0)
  README.md
  sale_order_general_discount/README.rst
  sale_order_general_discount/__manifest__.py
  sale_order_general_discount/i18n/de.po
  sale_order_general_discount/i18n/es.po
  sale_order_general_discount/i18n/it.po
  sale_order_general_discount/i18n/sale_order_general_discount.pot
  sale_order_general_discount/i18n/zh_CN.po
  sale_order_general_discount/models/__init__.py
  sale_order_general_discount/models/res_company.py
  sale_order_general_discount/models/res_config_settings.py
  sale_order_general_discount/models/sale_order.py
  sale_order_general_discount/models/sale_order_line.py
  sale_order_general_discount/readme/DESCRIPTION.rst
  sale_order_general_discount/readme/USAGE.rst
  sale_order_general_discount/static/description/index.html
  sale_order_general_discount/tests/test_sale_order_general_discount.py
  sale_order_general_discount/views/res_config_settings_view.xml
  sale_order_general_discount_payment_term/README.rst
  sale_order_general_discount_payment_term/__manifest__.py
  sale_order_general_discount_payment_term/static/description/index.html
  sale_order_general_discount_payment_term/tests/test_payment_term_discount.py
  sale_order_general_discount_triple/README.rst
  sale_order_general_discount_triple/__manifest__.py
  sale_order_general_discount_triple/i18n/it.po
  sale_order_general_discount_triple/i18n/sale_order_general_discount_triple.pot
  sale_order_general_discount_triple/models/sale_order.py
  sale_order_general_discount_triple/models/sale_order_line.py
  sale_order_general_discount_triple/static/description/index.html
  sale_order_tag/i18n/it.po
Labels: 14.0

#1669 Syncing from upstream OCA/sale-workflow (15.0)
  sale_product_multi_add/i18n/fr.po
Labels: 15.0

#1670 Syncing from upstream OCA/sale-workflow (16.0)
  product_supplierinfo_for_customer_sale/i18n/de.po
  sale_procurement_group_by_line/i18n/de.po
Labels: 16.0

#1671 Syncing from upstream OCA/sale-workflow (14.0)
  sale_order_general_discount/i18n/it.po
Labels: 14.0

#1672 Syncing from upstream OCA/sale-workflow (16.0)
  sale_fixed_discount/i18n/pt_BR.po
  sale_order_general_discount/i18n/pt_BR.po
  sale_order_line_menu/i18n/pt_BR.po
Labels: 16.0

#1673 Syncing from upstream OCA/sale-workflow (8.0)
  sale_payment_method/i18n/it.po
  sale_quick_payment/i18n/it.po
Labels: 8.0

#1674 Syncing from upstream OCA/sale-workflow (12.0)
  sale_blanket_order/i18n/it.po
  sale_order_line_input/i18n/it.po
Labels: 12.0

#1675 Syncing from upstream OCA/sale-workflow (13.0)
  sale_stock_picking_blocking/i18n/it.po
Labels: 13.0

#1676 Syncing from upstream OCA/sale-workflow (14.0)
  sale_order_line_input/i18n/it.po
  sale_stock_picking_blocking/i18n/it.po
Labels: 14.0

#1677 Syncing from upstream OCA/sale-workflow (15.0)
  sale_order_line_input/i18n/it.po
  sale_stock_picking_blocking/i18n/it.po
Labels: 15.0

#1678 Syncing from upstream OCA/sale-workflow (16.0)
  sale_start_end_dates/i18n/it.po
Labels: 16.0

#1679 Syncing from upstream OCA/sale-workflow (15.0)
  sale_order_discount_invoicing/i18n/es.po
Labels: 15.0

#1680 Syncing from upstream OCA/sale-workflow (16.0)
  sale_fixed_discount/i18n/es.po
  sale_mrp_bom/i18n/es.po
  sale_order_invoicing_finished_task/i18n/es.po
  sale_order_line_delivery_state/i18n/es.po
  sale_order_lot_generator/i18n/es.po
  sale_start_end_dates/i18n/es.po
Labels: 16.0

#1681 Syncing from upstream OCA/sale-workflow (14.0)
  README.md
  sale_invoice_delivery_state/README.rst
  sale_invoice_delivery_state/__init__.py
  sale_invoice_delivery_state/__manifest__.py
  sale_invoice_delivery_state/i18n/fr.po
  sale_invoice_delivery_state/i18n/sale_invoice_delivery_state.pot
  sale_invoice_delivery_state/models/__init__.py
  sale_invoice_delivery_state/models/partner.py
  sale_invoice_delivery_state/models/sale.py
  sale_invoice_delivery_state/readme/CONTRIBUTORS.rst
  sale_invoice_delivery_state/readme/DESCRIPTION.rst
  sale_invoice_delivery_state/static/description/icon.png
  sale_invoice_delivery_state/static/description/index.html
  sale_invoice_delivery_state/tests/__init__.py
  sale_invoice_delivery_state/tests/test_sale_invoice_delivery_state.py
  sale_invoice_delivery_state/views/partner.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_invoice_delivery_state/odoo/addons/sale_invoice_delivery_state
  setup/sale_invoice_delivery_state/setup.py
Labels: 14.0

#1682 Syncing from upstream OCA/sale-workflow (11.0)
  sale_commercial_partner/i18n/it.po
Labels: 11.0

#1683 Syncing from upstream OCA/sale-workflow (12.0)
  sale_commercial_partner/i18n/it.po
Labels: 12.0

#1684 Syncing from upstream OCA/sale-workflow (13.0)
  sale_commercial_partner/i18n/it.po
Labels: 13.0

#1685 Syncing from upstream OCA/sale-workflow (14.0)
  README.md
  sale_commercial_partner/i18n/it.po
  sale_order_product_assortment_quick/README.rst
  sale_order_product_assortment_quick/__init__.py
  sale_order_product_assortment_quick/__manifest__.py
  sale_order_product_assortment_quick/i18n/sale_order_product_assortment_quick.pot
  sale_order_product_assortment_quick/models/__init__.py
  sale_order_product_assortment_quick/models/sale_order.py
  sale_order_product_assortment_quick/readme/CONFIGURE.rst
  sale_order_product_assortment_quick/readme/CONTRIBUTORS.rst
  sale_order_product_assortment_quick/readme/DESCRIPTION.rst
  sale_order_product_assortment_quick/readme/USAGE.rst
  sale_order_product_assortment_quick/static/description/icon.png
  sale_order_product_assortment_quick/static/description/index.html
  sale_order_product_assortment_quick/tests/__init__.py
  sale_order_product_assortment_quick/tests/test_sale_order_product_assortment_quick.py
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_order_product_assortment_quick/odoo/addons/sale_order_product_assortment_quick
  setup/sale_order_product_assortment_quick/setup.py
Labels: 14.0

#1686 Syncing from upstream OCA/sale-workflow (15.0)
  sale_commercial_partner/i18n/it.po
Labels: 15.0

#1687 Syncing from upstream OCA/sale-workflow (16.0)
  README.md
  sale_order_product_recommendation_packaging_default/README.rst
  sale_order_product_recommendation_packaging_default/__init__.py
  sale_order_product_recommendation_packaging_default/__manifest__.py
  sale_order_product_recommendation_packaging_default/i18n/es.po
  sale_order_product_recommendation_packaging_default/i18n/sale_order_product_recommendation_packaging_default.pot
  sale_order_product_recommendation_packaging_default/readme/CONFIGURE.md
  sale_order_product_recommendation_packaging_default/readme/CONTRIBUTORS.md
  sale_order_product_recommendation_packaging_default/readme/DESCRIPTION.md
  sale_order_product_recommendation_packaging_default/readme/INSTALL.md
  sale_order_product_recommendation_packaging_default/readme/USAGE.md
  sale_order_product_recommendation_packaging_default/static/description/icon.png
  sale_order_product_recommendation_packaging_default/static/description/index.html
  sale_order_product_recommendation_packaging_default/tests/__init__.py
  sale_order_product_recommendation_packaging_default/tests/test_recommendation.py
  sale_order_product_recommendation_packaging_default/wizards/__init__.py
  sale_order_product_recommendation_packaging_default/wizards/sale_order_recommendation.py
  sale_order_product_recommendation_packaging_default/wizards/sale_order_recommendation_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_order_product_recommendation_packaging_default/odoo/addons/sale_order_product_recommendation_packaging_default
  setup/sale_order_product_recommendation_packaging_default/setup.py
Labels: 16.0

#1688 Syncing from upstream OCA/sale-workflow (8.0)
  sale_order_weight/i18n/it.po
Labels: 8.0

#1689 Syncing from upstream OCA/sale-workflow (12.0)
  sale_blanket_order/i18n/it.po
Labels: 12.0

#1691 Syncing from upstream OCA/sale-workflow (14.0)
  README.md
  sale_discount_display_amount/README.rst
  sale_discount_display_amount/__manifest__.py
  sale_discount_display_amount/report/sale_report_template.xml
  sale_discount_display_amount/static/description/index.html
Labels: 14.0

#1692 Syncing from upstream OCA/sale-workflow (15.0)
  README.md
  sale_quotation_number/README.rst
  sale_quotation_number/__manifest__.py
  sale_quotation_number/i18n/sale_quotation_number.pot
  sale_quotation_number/migrations/15.0.1.0.2/post-migration.py
  sale_quotation_number/models/sale_order.py
  sale_quotation_number/static/description/index.html
Labels: 15.0

#1693 Syncing from upstream OCA/sale-workflow (16.0)
  README.md
  sale_payment_sheet/README.rst
  sale_payment_sheet/__init__.py
  sale_payment_sheet/__manifest__.py
  sale_payment_sheet/i18n/es.po
  sale_payment_sheet/i18n/sale_payment_sheet.pot
  sale_payment_sheet/models/__init__.py
  sale_payment_sheet/models/res_users.py
  sale_payment_sheet/models/sale_payment_sheet.py
  sale_payment_sheet/readme/CONFIGURE.rst
  sale_payment_sheet/readme/CONTRIBUTORS.rst
  sale_payment_sheet/readme/DESCRIPTION.rst
  sale_payment_sheet/readme/USAGE.rst
  sale_payment_sheet/report/report_sale_payment_sheet_summary.xml
  sale_payment_sheet/report/sale_payment_sheet_report.xml
  sale_payment_sheet/security/ir.model.access.csv
  sale_payment_sheet/security/security.xml
  sale_payment_sheet/static/description/icon.png
  sale_payment_sheet/static/description/index.html
  sale_payment_sheet/tests/__init__.py
  sale_payment_sheet/tests/test_sale_payment_sheet.py
  sale_payment_sheet/views/res_users_views.xml
  sale_payment_sheet/views/sale_payment_sheet_menu.xml
  sale_payment_sheet/views/sale_payment_sheet_views.xml
  sale_payment_sheet/wizards/__init__.py
  sale_payment_sheet/wizards/sale_invoice_payment.py
  sale_payment_sheet/wizards/sale_invoice_payment_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_payment_sheet/odoo/addons/sale_payment_sheet
  setup/sale_payment_sheet/setup.py
Labels: 16.0

#1694 Syncing from upstream OCA/sale-workflow (15.0)
  README.md
  sale_order_type/README.rst
  sale_order_type/__manifest__.py
  sale_order_type/i18n/es.po
  sale_order_type/i18n/sale_order_type.pot
  sale_order_type/static/description/index.html
  sale_order_type/views/sale_order_view.xml
Labels: 15.0

#1695 Syncing from upstream OCA/sale-workflow (16.0)
  README.md
  sale_order_type/README.rst
  sale_order_type/__manifest__.py
  sale_order_type/i18n/es.po
  sale_order_type/i18n/sale_order_type.pot
  sale_order_type/static/description/index.html
  sale_order_type/views/sale_order_view.xml
Labels: 16.0

#1696 Syncing from upstream OCA/sale-workflow (14.0)
  README.md
  sale_order_type/README.rst
  sale_order_type/__manifest__.py
  sale_order_type/i18n/es.po
  sale_order_type/i18n/sale_order_type.pot
  sale_order_type/static/description/index.html
  sale_order_type/views/sale_order_view.xml
Labels: 14.0

#1699 Syncing from upstream OCA/sale-workflow (13.0)
  README.md
  sale_order_line_remove/README.rst
  sale_order_line_remove/__init__.py
  sale_order_line_remove/__manifest__.py
  sale_order_line_remove/i18n/sale_order_line_remove.pot
  sale_order_line_remove/models/__init__.py
  sale_order_line_remove/models/sale_order.py
  sale_order_line_remove/readme/CONTRIBUTORS.rst
  sale_order_line_remove/readme/DESCRIPTION.rst
  sale_order_line_remove/readme/USAGE.rst
  sale_order_line_remove/static/description/icon.png
  sale_order_line_remove/static/description/index.html
  sale_order_line_remove/tests/__init__.py
  sale_order_line_remove/tests/test_sale_order_line.py
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_order_line_remove/odoo/addons/sale_order_line_remove
  setup/sale_order_line_remove/setup.py
Labels: 13.0

#1700 Syncing from upstream OCA/sale-workflow (16.0)
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  sale_tier_validation/i18n/sale_tier_validation.pot
Labels: 16.0

#1701 Syncing from upstream OCA/sale-workflow (15.0)
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  README.md
  sale_blanket_order/README.rst
  sale_blanket_order/__manifest__.py
  sale_blanket_order/i18n/sale_blanket_order.pot
  sale_blanket_order/static/description/index.html
  sale_missing_tracking/README.rst
  sale_missing_tracking/__manifest__.py
  sale_missing_tracking/i18n/sale_missing_tracking.pot
  sale_missing_tracking/static/description/index.html
  sale_payment_sheet/README.rst
  sale_payment_sheet/__manifest__.py
  sale_payment_sheet/i18n/sale_payment_sheet.pot
  sale_payment_sheet/static/description/index.html
  sale_planner_calendar/README.rst
  sale_planner_calendar/__manifest__.py
  sale_planner_calendar/i18n/sale_planner_calendar.pot
  sale_planner_calendar/static/description/index.html
  sale_rental/README.rst
  sale_rental/__manifest__.py
  sale_rental/i18n/es.po
  sale_rental/i18n/sale_rental.pot
  sale_rental/models/sale_order.py
  sale_rental/static/description/index.html
Labels: 15.0

#1702 Syncing from upstream OCA/sale-workflow (16.0)
  README.md
  portal_sale_personal_data_only/README.rst
  portal_sale_personal_data_only/__init__.py
  portal_sale_personal_data_only/__manifest__.py
  portal_sale_personal_data_only/hooks.py
  portal_sale_personal_data_only/i18n/de.po
  portal_sale_personal_data_only/i18n/es.po
  portal_sale_personal_data_only/i18n/portal_sale_personal_data_only.pot
  portal_sale_personal_data_only/i18n/zh_CN.po
  portal_sale_personal_data_only/readme/CONTRIBUTORS.rst
  portal_sale_personal_data_only/readme/DESCRIPTION.rst
  portal_sale_personal_data_only/readme/USAGE.rst
  portal_sale_personal_data_only/security/security.xml
  portal_sale_personal_data_only/static/description/icon.png
  portal_sale_personal_data_only/static/description/index.html
  portal_sale_personal_data_only/tests/__init__.py
  portal_sale_personal_data_only/tests/test_partner_access.py
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/portal_sale_personal_data_only/odoo/addons/portal_sale_personal_data_only
  setup/portal_sale_personal_data_only/setup.py
Labels: 16.0

#1703 Syncing from upstream OCA/sale-workflow (12.0)
  sale_blanket_order/i18n/it.po
  sale_manual_delivery/i18n/it.po
  sale_order_line_input/i18n/it.po
  sale_order_secondary_unit/i18n/it.po
  sale_restricted_qty/i18n/it.po
Labels: 12.0

#1704 Syncing from upstream OCA/sale-workflow (14.0)
  sale_by_packaging/i18n/it.po
  sale_order_line_input/i18n/it.po
  sale_restricted_qty/i18n/it.po
  sale_tier_validation/i18n/es.po
  sale_tier_validation/i18n/sv.po
  sale_tier_validation/i18n/zh_CN.po
Labels: 14.0
