Repository brain-tec/sale-workflow, pull requests merged in 2023-02, with the labels that each got.

#1284 Syncing from upstream OCA/sale-workflow (8.0)
  sale_order_back2draft/i18n/it.po
  sale_order_revision/i18n/it.po
  sale_payment_method/i18n/it.po
  sale_payment_term_interest/i18n/it.po
  sale_procurement_group_by_line/i18n/it.po
  sale_rental/i18n/it.po
  sale_service_fleet/i18n/it.po
  sale_sourced_by_line/i18n/it.po
  sale_validity/i18n/it.po
Labels: 8.0

#1285 Syncing from upstream OCA/sale-workflow (9.0)
  sale_cancel_reason/i18n/it.po
  sale_force_invoiced/i18n/it.po
  sale_order_line_date/i18n/it.po
  sale_order_lot_selection/i18n/it.po
  sale_procurement_group_by_line/i18n/it.po
  sale_rental/i18n/it.po
Labels: 9.0

#1286 Syncing from upstream OCA/sale-workflow (10.0)
  sale_company_currency/i18n/it.po
  sale_exception/i18n/it.po
  sale_force_invoiced/i18n/it.po
  sale_isolated_quotation/i18n/it.po
  sale_order_action_invoice_create_hook/i18n/it.po
  sale_order_margin_percent/i18n/it.po
  sale_order_price_recalculation/i18n/it.po
  sale_order_revision/i18n/it.po
  sale_order_type/i18n/it.po
  sale_procurement_group_by_line/i18n/it.po
  sale_procurement_group_by_requested_date/i18n/it.po
  sale_rental/i18n/it.po
  sale_start_end_dates/i18n/it.po
  sale_stock_picking_blocking/i18n/it.po
Labels: 10.0

#1287 Syncing from upstream OCA/sale-workflow (12.0)
  sale_blanket_order/i18n/it.po
  sale_order_line_sequence/i18n/it.po
  sale_order_type/i18n/it.po
Labels: 12.0

#1288 Syncing from upstream OCA/sale-workflow (13.0)
  sale_order_type/i18n/it.po
Labels: 13.0

#1289 Syncing from upstream OCA/sale-workflow (15.0)
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  README.md
  product_supplierinfo_for_customer_elaboration/README.rst
  product_supplierinfo_for_customer_elaboration/__manifest__.py
  product_supplierinfo_for_customer_elaboration/i18n/es.po
  product_supplierinfo_for_customer_elaboration/i18n/product_supplierinfo_for_customer_elaboration.pot
  product_supplierinfo_for_customer_elaboration/migrations/15.0.2.0.0/post-migration.py
  product_supplierinfo_for_customer_elaboration/migrations/15.0.2.0.0/pre-migration.py
  product_supplierinfo_for_customer_elaboration/models/product_customerinfo.py
  product_supplierinfo_for_customer_elaboration/models/sale_order_line.py
  product_supplierinfo_for_customer_elaboration/readme/CONTRIBUTORS.rst
  product_supplierinfo_for_customer_elaboration/static/description/index.html
  product_supplierinfo_for_customer_elaboration/tests/test_customerinfo_elaboration.py
  product_supplierinfo_for_customer_elaboration/views/product_views.xml
  sale_elaboration/README.rst
  sale_elaboration/__manifest__.py
  sale_elaboration/i18n/de.po
  sale_elaboration/i18n/es.po
  sale_elaboration/i18n/sale_elaboration.pot
  sale_elaboration/migrations/15.0.2.0.0/post-migration.py
  sale_elaboration/migrations/15.0.2.0.0/pre-migration.py
  sale_elaboration/models/sale_order.py
  sale_elaboration/models/stock_picking.py
  sale_elaboration/readme/CONTRIBUTORS.rst
  sale_elaboration/reports/report_deliveryslip.xml
  sale_elaboration/static/description/index.html
  sale_elaboration/tests/test_sale_elaboration.py
  sale_elaboration/views/sale_elaboration_report_views.xml
  sale_elaboration/views/sale_order_views.xml
Labels: 15.0

#1293 Delete en.po in sale_order_lot_selection
  sale_order_lot_selection/i18n/en.po
Labels: 15.0.project_mi_465

#1295 Syncing from upstream OCA/sale-workflow (15.0)
  README.md
  sale_missing_tracking/README.rst
  sale_missing_tracking/__init__.py
  sale_missing_tracking/__manifest__.py
  sale_missing_tracking/data/mail_activity_data.xml
  sale_missing_tracking/data/mail_data.xml
  sale_missing_tracking/data/mail_template_data.xml
  sale_missing_tracking/data/sale_missing_tracking_data.xml
  sale_missing_tracking/i18n/es.po
  sale_missing_tracking/i18n/sale_missing_tracking.pot
  sale_missing_tracking/models/__init__.py
  sale_missing_tracking/models/product.py
  sale_missing_tracking/models/res_company.py
  sale_missing_tracking/models/res_config_settings.py
  sale_missing_tracking/models/res_partner.py
  sale_missing_tracking/models/sale_missing_tracking.py
  sale_missing_tracking/models/sale_missing_tracking_exception.py
  sale_missing_tracking/models/sale_order.py
  sale_missing_tracking/readme/CONFIGURE.rst
  sale_missing_tracking/readme/CONTRIBUTORS.rst
  sale_missing_tracking/readme/DESCRIPTION.rst
  sale_missing_tracking/readme/USAGE.rst
  sale_missing_tracking/security/ir.model.access.csv
  sale_missing_tracking/security/security.xml
  sale_missing_tracking/static/description/icon.png
  sale_missing_tracking/static/description/index.html
  sale_missing_tracking/tests/__init__.py
  sale_missing_tracking/tests/test_sale_missing_tracking.py
  sale_missing_tracking/views/product_views.xml
  sale_missing_tracking/views/res_config_settings_views.xml
  sale_missing_tracking/views/res_partner_views.xml
  sale_missing_tracking/views/sale_missing_tracking_exception_views.xml
  sale_missing_tracking/views/sale_missing_tracking_menu.xml
  sale_missing_tracking/views/sale_missing_tracking_reason_views.xml
  sale_missing_tracking/views/sale_missing_tracking_views.xml
  sale_missing_tracking/views/sale_order_views.xml
  sale_missing_tracking/wizards/__init__.py
  sale_missing_tracking/wizards/sale_missing_tracking_wiz.py
  sale_missing_tracking/wizards/sale_missing_tracking_wiz.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_missing_tracking/odoo/addons/sale_missing_tracking
  setup/sale_missing_tracking/setup.py
Labels: 15.0

#1296 Syncing from upstream OCA/sale-workflow (16.0)
  README.md
  partner_contact_sale_info_propagation/__manifest__.py
  partner_contact_sale_info_propagation/models/res_partner.py
  sale_order_type/i18n/tr.po
Labels: 16.0

#1298 Syncing from upstream OCA/sale-workflow (13.0)
  README.md
  sale_order_line_price_history/__init__.py
  sale_order_line_price_history/__manifest__.py
  sale_order_line_price_history/i18n/de.po
  sale_order_line_price_history/i18n/es.po
  sale_order_line_price_history/i18n/pt.po
  sale_order_line_price_history/i18n/sale_order_line_price_history.pot
  sale_order_line_price_history/i18n/zh_CN.po
  sale_order_line_price_history/migrations/13.0.2.0.0/post-migration.py
  sale_order_line_price_history/models/__init__.py
  sale_order_line_price_history/models/sale_order_line.py
  sale_order_line_price_history/static/src/js/sale_line_price_history_widget.js
  sale_order_line_price_history/views/sale_views.xml
Labels: 13.0

#1299 Syncing from upstream OCA/sale-workflow (14.0)
  README.md
  sale_order_partner_restrict/README.rst
  sale_order_partner_restrict/__manifest__.py
  sale_order_partner_restrict/i18n/it.po
  sale_order_partner_restrict/i18n/sale_order_partner_restrict.pot
  sale_order_partner_restrict/models/res_company.py
  sale_order_partner_restrict/models/sale.py
  sale_order_partner_restrict/readme/CONTRIBUTORS.rst
  sale_order_partner_restrict/readme/DESCRIPTION.rst
  sale_order_partner_restrict/static/description/index.html
  sale_order_partner_restrict/tests/test_sale_order_partner_restrict.py
Labels: 14.0

#1301 Syncing from upstream OCA/sale-workflow (14.0)
  sale_order_partner_restrict/i18n/it.po
  sale_product_category_menu/i18n/it.po
Labels: 14.0

#1303 Syncing from upstream OCA/sale-workflow (14.0)
  README.md
  sale_order_revision/__manifest__.py
  sale_order_revision/models/sale_order.py
  sale_quick/i18n/fr.po
Labels: 14.0

#1304 Syncing from upstream OCA/sale-workflow (16.0)
  sale_triple_discount/i18n/es_MX.po
Labels: 16.0

#1305 Syncing from upstream OCA/sale-workflow (16.0)
  sale_exception/i18n/hr.po
  sale_order_type/i18n/hr.po
Labels: 16.0

#1306 Syncing from upstream OCA/sale-workflow (8.0)
  partner_prepayment/i18n/it.po
  sale_automatic_workflow/i18n/it.po
  sale_order_price_recalculation/i18n/it.po
  sale_order_type/i18n/it.po
  sale_order_type_sale_journal/i18n/it.po
  sale_partner_order_policy/i18n/it.po
  sale_payment_method_transaction_id/i18n/it.po
  sale_properties_dynamic_fields/i18n/it.po
  sale_quotation_number/i18n/it.po
  sale_quotation_sourcing/i18n/it.po
  sale_reason_to_export/i18n/it.po
  sale_service_project/i18n/it.po
  sale_start_end_dates/i18n/it.po
Labels: 8.0

#1307 Syncing from upstream OCA/sale-workflow (9.0)
  sale_automatic_workflow/i18n/it.po
  sale_exception/i18n/it.po
  sale_order_price_recalculation/i18n/it.po
  sale_order_type/i18n/it.po
  sale_revert_done/i18n/it.po
  sale_sourced_by_line/i18n/it.po
Labels: 9.0

#1308 Syncing from upstream OCA/sale-workflow (10.0)
  sale_automatic_workflow/i18n/it.po
  sale_automatic_workflow_payment_mode/i18n/it.po
  sale_cancel_reason/i18n/it.po
  sale_commercial_partner/i18n/it.po
  sale_invoice_group_method/i18n/it.po
  sale_layout_hidden/i18n/it.po
  sale_merge_draft_invoice/i18n/it.po
  sale_order_invoicing_finished_task/i18n/it.po
  sale_order_line_date/i18n/it.po
  sale_order_lot_generator/i18n/it.po
  sale_order_lot_selection/i18n/it.po
  sale_revert_done/i18n/it.po
  sale_shipping_info_helper/i18n/it.po
  sale_sourced_by_line/i18n/it.po
  sale_validity/i18n/it.po
Labels: 10.0

#1311 Syncing from upstream OCA/sale-workflow (14.0)
  README.md
  pricelist_cache/__manifest__.py
  pricelist_cache/i18n/pricelist_cache.pot
  pricelist_cache/migrations/14.0.1.1.0/README.rst
  pricelist_cache/migrations/14.0.1.1.0/post-migrate.py
  pricelist_cache/migrations/14.0.1.1.0/pre-migrate.py
  pricelist_cache/models/product_pricelist.py
  pricelist_cache/models/product_pricelist_cache.py
  pricelist_cache/models/res_partner.py
  pricelist_cache/tests/test_partner_pricelist_cache.py
Labels: 14.0

#1312 Syncing from upstream OCA/sale-workflow (15.0)
  README.md
  sale_stock_return_request/README.rst
  sale_stock_return_request/__init__.py
  sale_stock_return_request/__manifest__.py
  sale_stock_return_request/i18n/ca.po
  sale_stock_return_request/i18n/es.po
  sale_stock_return_request/i18n/fr.po
  sale_stock_return_request/i18n/sale_stock_return_request.pot
  sale_stock_return_request/models/__init__.py
  sale_stock_return_request/models/stock_return_request.py
  sale_stock_return_request/readme/CONTRIBUTORS.rst
  sale_stock_return_request/readme/DESCRIPTION.rst
  sale_stock_return_request/readme/USAGE.rst
  sale_stock_return_request/static/description/icon.png
  sale_stock_return_request/static/description/index.html
  sale_stock_return_request/tests/__init__.py
  sale_stock_return_request/tests/test_stock_return_request.py
  sale_stock_return_request/views/sale_return_request_views.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_stock_return_request/odoo/addons/sale_stock_return_request
  setup/sale_stock_return_request/setup.py
Labels: 15.0

#1310 [t134661] Change Sale Order Line Commitment Date Field From Datetime to Date
  sale_order_line_date/models/sale_order_line.py
  sale_order_line_date/tests/test_sale_order_line_date.py
Labels: 15.0.project_pt_642
