Repository brain-tec/sale-workflow, pull requests merged in 2023-03, with the labels that each got.

#1314 Syncing from upstream OCA/sale-workflow (13.0)
  README.md
  sale_order_secondary_unit/__manifest__.py
  sale_order_secondary_unit/models/sale_order.py
Labels: 13.0

#1315 Syncing from upstream OCA/sale-workflow (15.0)
  README.md
  sale_partner_incoterm/README.rst
  sale_partner_incoterm/__init__.py
  sale_partner_incoterm/__manifest__.py
  sale_partner_incoterm/i18n/ca.po
  sale_partner_incoterm/i18n/de.po
  sale_partner_incoterm/i18n/es.po
  sale_partner_incoterm/i18n/fi.po
  sale_partner_incoterm/i18n/fr.po
  sale_partner_incoterm/i18n/it.po
  sale_partner_incoterm/i18n/nl.po
  sale_partner_incoterm/i18n/sale_partner_incoterm.pot
  sale_partner_incoterm/i18n/sl.po
  sale_partner_incoterm/i18n/tr.po
  sale_partner_incoterm/i18n/zh_CN.po
  sale_partner_incoterm/models/__init__.py
  sale_partner_incoterm/models/res_partner.py
  sale_partner_incoterm/models/sale_order.py
  sale_partner_incoterm/readme/CONTRIBUTORS.rst
  sale_partner_incoterm/readme/DESCRIPTION.rst
  sale_partner_incoterm/static/description/icon.png
  sale_partner_incoterm/static/description/index.html
  sale_partner_incoterm/tests/__init__.py
  sale_partner_incoterm/tests/test_sale_partner_incoterm.py
  sale_partner_incoterm/views/res_partner.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_partner_incoterm/odoo/addons/sale_partner_incoterm
  setup/sale_partner_incoterm/setup.py
Labels: 15.0

#1316 Syncing from upstream OCA/sale-workflow (15.0)
  README.md
  sale_delivery_split_date/README.rst
  sale_delivery_split_date/__init__.py
  sale_delivery_split_date/__manifest__.py
  sale_delivery_split_date/i18n/ca.po
  sale_delivery_split_date/i18n/es.po
  sale_delivery_split_date/i18n/it.po
  sale_delivery_split_date/i18n/pt_PT.po
  sale_delivery_split_date/i18n/sale_delivery_split_date.pot
  sale_delivery_split_date/models/__init__.py
  sale_delivery_split_date/models/sale_order_line.py
  sale_delivery_split_date/readme/CONTRIBUTORS.rst
  sale_delivery_split_date/readme/DESCRIPTION.rst
  sale_delivery_split_date/readme/ROADMAP.rst
  sale_delivery_split_date/static/description/icon.png
  sale_delivery_split_date/static/description/index.html
  sale_delivery_split_date/tests/__init__.py
  sale_delivery_split_date/tests/test_sale_delivery.py
  sale_delivery_split_date/views/stock_picking.xml
  sale_partner_incoterm/i18n/ca.po
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_delivery_split_date/odoo/addons/sale_delivery_split_date
  setup/sale_delivery_split_date/setup.py
Labels: 15.0

#1317 Syncing from upstream OCA/sale-workflow (15.0)
  README.md
  sales_team_security/__manifest__.py
  sales_team_security/models/res_partner.py
Labels: 15.0

#1318 16.0 mig sale partner incoterm
  sale_partner_incoterm/README.rst
  sale_partner_incoterm/__init__.py
  sale_partner_incoterm/__manifest__.py
  sale_partner_incoterm/i18n/ca.po
  sale_partner_incoterm/i18n/de.po
  sale_partner_incoterm/i18n/es.po
  sale_partner_incoterm/i18n/fi.po
  sale_partner_incoterm/i18n/fr.po
  sale_partner_incoterm/i18n/it.po
  sale_partner_incoterm/i18n/nl.po
  sale_partner_incoterm/i18n/sale_partner_incoterm.pot
  sale_partner_incoterm/i18n/sl.po
  sale_partner_incoterm/i18n/tr.po
  sale_partner_incoterm/i18n/zh_CN.po
  sale_partner_incoterm/models/__init__.py
  sale_partner_incoterm/models/res_partner.py
  sale_partner_incoterm/models/sale_order.py
  sale_partner_incoterm/readme/CONTRIBUTORS.rst
  sale_partner_incoterm/readme/DESCRIPTION.rst
  sale_partner_incoterm/static/description/icon.png
  sale_partner_incoterm/static/description/index.html
  sale_partner_incoterm/tests/__init__.py
  sale_partner_incoterm/tests/test_sale_partner_incoterm.py
  sale_partner_incoterm/views/res_partner.xml
  setup/sale_partner_incoterm/odoo/addons/sale_partner_incoterm
  setup/sale_partner_incoterm/setup.py
Labels: 16.0.project_no_681

#1319 Syncing from upstream OCA/sale-workflow (8.0)
  product_margin_classification/i18n/it.po
  sale_properties_easy_creation/i18n/it.po
  sale_service_project/i18n/it.po
Labels: 8.0

#1320 Syncing from upstream OCA/sale-workflow (9.0)
  sale_automatic_workflow/i18n/it.po
  sale_order_variant_mgmt/i18n/it.po
Labels: 9.0

#1321 Syncing from upstream OCA/sale-workflow (12.0)
  sale_blanket_order/i18n/it.po
Labels: 12.0

#1325 Syncing from upstream OCA/sale-workflow (16.0)
  README.md
  sale_automatic_workflow/i18n/es.po
  sale_automatic_workflow/tests/test_multicompany.py
  sale_automatic_workflow_payment_mode/README.rst
  sale_automatic_workflow_payment_mode/__init__.py
  sale_automatic_workflow_payment_mode/__manifest__.py
  sale_automatic_workflow_payment_mode/i18n/ca.po
  sale_automatic_workflow_payment_mode/i18n/de.po
  sale_automatic_workflow_payment_mode/i18n/el_GR.po
  sale_automatic_workflow_payment_mode/i18n/es.po
  sale_automatic_workflow_payment_mode/i18n/es_ES.po
  sale_automatic_workflow_payment_mode/i18n/es_VE.po
  sale_automatic_workflow_payment_mode/i18n/fi.po
  sale_automatic_workflow_payment_mode/i18n/fr.po
  sale_automatic_workflow_payment_mode/i18n/hr.po
  sale_automatic_workflow_payment_mode/i18n/hr_HR.po
  sale_automatic_workflow_payment_mode/i18n/hu.po
  sale_automatic_workflow_payment_mode/i18n/it.po
  sale_automatic_workflow_payment_mode/i18n/nl.po
  sale_automatic_workflow_payment_mode/i18n/nl_NL.po
  sale_automatic_workflow_payment_mode/i18n/pt.po
  sale_automatic_workflow_payment_mode/i18n/pt_BR.po
  sale_automatic_workflow_payment_mode/i18n/ro.po
  sale_automatic_workflow_payment_mode/i18n/sale_automatic_workflow_payment_mode.pot
  sale_automatic_workflow_payment_mode/i18n/sk.po
  sale_automatic_workflow_payment_mode/i18n/sl.po
  sale_automatic_workflow_payment_mode/i18n/tr.po
  sale_automatic_workflow_payment_mode/i18n/tr_TR.po
  sale_automatic_workflow_payment_mode/i18n/vi_VN.po
  sale_automatic_workflow_payment_mode/i18n/zh_CN.po
  sale_automatic_workflow_payment_mode/models/__init__.py
  sale_automatic_workflow_payment_mode/models/account_payment_mode.py
  sale_automatic_workflow_payment_mode/models/automatic_workflow_job.py
  sale_automatic_workflow_payment_mode/models/sale_order.py
  sale_automatic_workflow_payment_mode/readme/CONFIGURE.rst
  sale_automatic_workflow_payment_mode/readme/CONTRIBUTORS.rst
  sale_automatic_workflow_payment_mode/readme/CREDITS.rst
  sale_automatic_workflow_payment_mode/readme/DESCRIPTION.rst
  sale_automatic_workflow_payment_mode/readme/INSTALL.rst
  sale_automatic_workflow_payment_mode/readme/USAGE.rst
  sale_automatic_workflow_payment_mode/static/description/icon.png
  sale_automatic_workflow_payment_mode/static/description/index.html
  sale_automatic_workflow_payment_mode/tests/__init__.py
  sale_automatic_workflow_payment_mode/tests/test_automatic_workflow_payment_mode.py
  sale_automatic_workflow_payment_mode/views/account_payment_mode_views.xml
  sale_exception/i18n/es.po
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_automatic_workflow_payment_mode/odoo/addons/sale_automatic_workflow_payment_mode
  setup/sale_automatic_workflow_payment_mode/setup.py
Labels: 16.0

#1326 Syncing from upstream OCA/sale-workflow (16.0)
  README.md
  sale_tier_validation/README.rst
  sale_tier_validation/__init__.py
  sale_tier_validation/__manifest__.py
  sale_tier_validation/data/mail_data.xml
  sale_tier_validation/i18n/es.po
  sale_tier_validation/i18n/es_MX.po
  sale_tier_validation/i18n/sale_tier_validation.pot
  sale_tier_validation/i18n/sv.po
  sale_tier_validation/i18n/zh_CN.po
  sale_tier_validation/models/__init__.py
  sale_tier_validation/models/sale_order.py
  sale_tier_validation/models/tier_definition.py
  sale_tier_validation/readme/CONFIGURE.rst
  sale_tier_validation/readme/CONTRIBUTORS.rst
  sale_tier_validation/readme/DESCRIPTION.rst
  sale_tier_validation/readme/INSTALL.rst
  sale_tier_validation/readme/USAGE.rst
  sale_tier_validation/static/description/icon.png
  sale_tier_validation/static/description/index.html
  sale_tier_validation/tests/__init__.py
  sale_tier_validation/tests/test_tier_validation.py
  sale_tier_validation/views/sale_order_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_tier_validation/odoo/addons/sale_tier_validation
  setup/sale_tier_validation/setup.py
Labels: 16.0

#1327 Syncing from upstream OCA/sale-workflow (12.0)
  README.md
  account_invoice_pricelist_technical/README.rst
  account_invoice_pricelist_technical/__init__.py
  account_invoice_pricelist_technical/__manifest__.py
  account_invoice_pricelist_technical/i18n/account_invoice_pricelist_technical.pot
  account_invoice_pricelist_technical/i18n/fr.po
  account_invoice_pricelist_technical/models/__init__.py
  account_invoice_pricelist_technical/models/account_invoice.py
  account_invoice_pricelist_technical/readme/CONTRIBUTORS.rst
  account_invoice_pricelist_technical/readme/DESCRIPTION.rst
  account_invoice_pricelist_technical/static/description/icon.png
  account_invoice_pricelist_technical/static/description/index.html
  sale_pricelist_technical/README.rst
  sale_pricelist_technical/__init__.py
  sale_pricelist_technical/__manifest__.py
  sale_pricelist_technical/demo/product_pricelist.xml
  sale_pricelist_technical/demo/res_groups.xml
  sale_pricelist_technical/i18n/fr.po
  sale_pricelist_technical/i18n/sale_pricelist_technical.pot
  sale_pricelist_technical/models/__init__.py
  sale_pricelist_technical/models/product_pricelist.py
  sale_pricelist_technical/models/res_partner.py
  sale_pricelist_technical/models/sale_order.py
  sale_pricelist_technical/readme/CONFIGURE.rst
  sale_pricelist_technical/readme/CONTRIBUTORS.rst
  sale_pricelist_technical/readme/DESCRIPTION.rst
  sale_pricelist_technical/static/description/icon.png
  sale_pricelist_technical/static/description/index.html
  sale_pricelist_technical/views/view_product_pricelist.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/account_invoice_pricelist_technical/odoo/addons/account_invoice_pricelist_technical
  setup/account_invoice_pricelist_technical/setup.py
  setup/sale_pricelist_technical/odoo/addons/sale_pricelist_technical
  setup/sale_pricelist_technical/setup.py
Labels: 12.0

#1328 Syncing from upstream OCA/sale-workflow (14.0)
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
Labels: 14.0

#1329 Syncing from upstream OCA/sale-workflow (15.0)
  .copier-answers.yml
Labels: 15.0

#1330 Syncing from upstream OCA/sale-workflow (16.0)
  .copier-answers.yml
Labels: 16.0

#1331 Syncing from upstream OCA/sale-workflow (12.0)
  .copier-answers.yml
  .github/workflows/pre-commit.yml.rej
  .github/workflows/test.yml.rej
  .pre-commit-config.yaml
Labels: 12.0

#1332 Syncing from upstream OCA/sale-workflow (14.0)
  README.md
  sale_pricelist_discount_decimal_precision/README.rst
  sale_pricelist_discount_decimal_precision/__init__.py
  sale_pricelist_discount_decimal_precision/__manifest__.py
  sale_pricelist_discount_decimal_precision/i18n/it.po
  sale_pricelist_discount_decimal_precision/i18n/sale_pricelist_discount_decimal_precision.pot
  sale_pricelist_discount_decimal_precision/models/__init__.py
  sale_pricelist_discount_decimal_precision/models/pricelist_item.py
  sale_pricelist_discount_decimal_precision/readme/CONTRIBUTORS.rst
  sale_pricelist_discount_decimal_precision/readme/DESCRIPTION.rst
  sale_pricelist_discount_decimal_precision/readme/USAGE.rst
  sale_pricelist_discount_decimal_precision/static/description/icon.png
  sale_pricelist_discount_decimal_precision/static/description/index.html
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_pricelist_discount_decimal_precision/odoo/addons/sale_pricelist_discount_decimal_precision
  setup/sale_pricelist_discount_decimal_precision/setup.py
Labels: 14.0

#1333 Syncing from upstream OCA/sale-workflow (15.0)
  sale_triple_discount/i18n/es.po
Labels: 15.0

#1334 Syncing from upstream OCA/sale-workflow (14.0)
  README.md
  sale_pricelist_item_advanced/README.rst
  sale_pricelist_item_advanced/__init__.py
  sale_pricelist_item_advanced/__manifest__.py
  sale_pricelist_item_advanced/i18n/sale_pricelist_item_advanced.pot
  sale_pricelist_item_advanced/readme/CONTRIBUTORS.rst
  sale_pricelist_item_advanced/readme/DESCRIPTION.rst
  sale_pricelist_item_advanced/readme/HISTORY.rst
  sale_pricelist_item_advanced/readme/USAGE.rst
  sale_pricelist_item_advanced/static/description/icon.png
  sale_pricelist_item_advanced/static/description/index.html
  sale_pricelist_item_advanced/views/product_pricelist_item.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_pricelist_item_advanced/odoo/addons/sale_pricelist_item_advanced
  setup/sale_pricelist_item_advanced/setup.py
Labels: 14.0

#1335 Syncing from upstream OCA/sale-workflow (8.0)
  sale_exceptions/i18n/it.po
  sale_last_price_info/i18n/it.po
Labels: 8.0

#1336 Syncing from upstream OCA/sale-workflow (9.0)
  sale_exception/i18n/it.po
Labels: 9.0

#1337 Syncing from upstream OCA/sale-workflow (11.0)
  sale_last_price_info/i18n/it.po
Labels: 11.0

#1338 Syncing from upstream OCA/sale-workflow (12.0)
  sale_blanket_order/i18n/it.po
  sale_last_price_info/i18n/it.po
  sale_order_line_price_history/i18n/it.po
Labels: 12.0

#1339 Syncing from upstream OCA/sale-workflow (13.0)
  sale_last_price_info/i18n/it.po
  sales_team_security/i18n/it.po
Labels: 13.0

#1340 Syncing from upstream OCA/sale-workflow (14.0)
  sale_last_price_info/i18n/it.po
  sale_pricelist_item_advanced/i18n/it.po
  sales_team_security/i18n/it.po
Labels: 14.0

#1341 Syncing from upstream OCA/sale-workflow (15.0)
  sale_last_price_info/i18n/it.po
  sales_team_security/i18n/it.po
Labels: 15.0

#1342 Syncing from upstream OCA/sale-workflow (14.0)
  sale_cancel_reason/i18n/it.po
  sale_quotation_template_product_multi_add/i18n/it.po
Labels: 14.0

#1343 Syncing from upstream OCA/sale-workflow (15.0)
  .oca/oca-port/blacklist/sale_partner_incoterm.json
  README.md
  sale_discount_display_amount/i18n/it.po
  sale_exception/i18n/it.po
  sale_partner_incoterm/__manifest__.py
  sale_partner_incoterm/views/res_partner.xml
  sale_product_set/i18n/it.po
  sale_rental/i18n/it.po
  sale_stock_picking_blocking/i18n/it.po
Labels: 15.0

#1344 Syncing from upstream OCA/sale-workflow (16.0)
  sale_automatic_workflow/i18n/it.po
  sale_exception/i18n/it.po
  sale_order_type/i18n/it.po
  sale_stock_picking_blocking/i18n/it.po
Labels: 16.0

#1346 Syncing from upstream OCA/sale-workflow (16.0)
  README.md
  sale_order_archive/README.rst
  sale_order_archive/__init__.py
  sale_order_archive/__manifest__.py
  sale_order_archive/i18n/ca.po
  sale_order_archive/i18n/de.po
  sale_order_archive/i18n/es.po
  sale_order_archive/i18n/nl.po
  sale_order_archive/i18n/pt_BR.po
  sale_order_archive/i18n/sale_order_archive.pot
  sale_order_archive/i18n/zh_CN.po
  sale_order_archive/models/__init__.py
  sale_order_archive/models/sale_order.py
  sale_order_archive/readme/CONTRIBUTORS.rst
  sale_order_archive/readme/DESCRIPTION.rst
  sale_order_archive/readme/INSTALL.rst
  sale_order_archive/readme/USAGE.rst
  sale_order_archive/static/description/icon.png
  sale_order_archive/static/description/index.html
  sale_order_archive/tests/__init__.py
  sale_order_archive/tests/test_sale_order_archive.py
  sale_order_archive/views/sale_order.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_order_archive/odoo/addons/sale_order_archive
  setup/sale_order_archive/setup.py
Labels: 16.0

#1347 Syncing from upstream OCA/sale-workflow (16.0)
  README.md
  sale_order_lot_generator/README.rst
  sale_order_lot_generator/__init__.py
  sale_order_lot_generator/__manifest__.py
  sale_order_lot_generator/i18n/ca.po
  sale_order_lot_generator/i18n/de.po
  sale_order_lot_generator/i18n/el_GR.po
  sale_order_lot_generator/i18n/es.po
  sale_order_lot_generator/i18n/es_ES.po
  sale_order_lot_generator/i18n/es_VE.po
  sale_order_lot_generator/i18n/fi.po
  sale_order_lot_generator/i18n/fr.po
  sale_order_lot_generator/i18n/hr.po
  sale_order_lot_generator/i18n/hr_HR.po
  sale_order_lot_generator/i18n/hu.po
  sale_order_lot_generator/i18n/it.po
  sale_order_lot_generator/i18n/nl.po
  sale_order_lot_generator/i18n/nl_NL.po
  sale_order_lot_generator/i18n/pt.po
  sale_order_lot_generator/i18n/pt_BR.po
  sale_order_lot_generator/i18n/ro.po
  sale_order_lot_generator/i18n/sale_order_lot_generator.pot
  sale_order_lot_generator/i18n/sk.po
  sale_order_lot_generator/i18n/sl.po
  sale_order_lot_generator/i18n/tr.po
  sale_order_lot_generator/i18n/tr_TR.po
  sale_order_lot_generator/i18n/vi_VN.po
  sale_order_lot_generator/i18n/zh_CN.po
  sale_order_lot_generator/models/__init__.py
  sale_order_lot_generator/models/product_template.py
  sale_order_lot_generator/models/sale_order.py
  sale_order_lot_generator/models/sale_order_line.py
  sale_order_lot_generator/readme/CONFIGURE.rst
  sale_order_lot_generator/readme/CONTRIBUTORS.rst
  sale_order_lot_generator/readme/DESCRIPTION.rst
  sale_order_lot_generator/readme/USAGE.rst
  sale_order_lot_generator/static/description/icon.png
  sale_order_lot_generator/static/description/index.html
  sale_order_lot_generator/tests/__init__.py
  sale_order_lot_generator/tests/test_sale_order_lot_generator.py
  sale_order_lot_generator/views/product_template.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_order_lot_generator/odoo/addons/sale_order_lot_generator
  setup/sale_order_lot_generator/setup.py
Labels: 16.0

#1350 Syncing from upstream OCA/sale-workflow (9.0)
  sale_rental/i18n/sl.po
Labels: 9.0

#1351 Syncing from upstream OCA/sale-workflow (12.0)
  sale_automatic_workflow/i18n/it.po
  sale_cancel_reason/i18n/it.po
  sale_exception/i18n/it.po
  sale_order_line_price_history/i18n/it.po
  sale_order_type/i18n/it.po
  sale_product_set/i18n/it.po
  sale_product_set_variant/i18n/it.po
  sale_rental/i18n/it.po
  sale_stock_picking_blocking/i18n/it.po
Labels: 12.0

#1352 Syncing from upstream OCA/sale-workflow (13.0)
  sale_automatic_workflow/i18n/it.po
  sale_cancel_reason/i18n/it.po
  sale_exception/i18n/it.po
  sale_order_type/i18n/it.po
  sale_product_set/i18n/it.po
  sale_stock_picking_blocking/i18n/it.po
Labels: 13.0

#1353 Syncing from upstream OCA/sale-workflow (14.0)
  sale_automatic_workflow/i18n/it.po
  sale_default_uom/i18n/it.po
  sale_delivery_date/i18n/it.po
  sale_discount_display_amount/i18n/it.po
  sale_exception/i18n/it.po
  sale_global_discount/i18n/it.po
  sale_order_type/i18n/it.po
  sale_product_set/i18n/it.po
  sale_rental/i18n/it.po
  sale_stock_picking_blocking/i18n/it.po
Labels: 14.0

#1354 Syncing from upstream OCA/sale-workflow (15.0)
  README.md
  sale_automatic_workflow/i18n/it.po
  sale_credit_point/__manifest__.py
  sale_credit_point/models/partner.py
  sale_order_secondary_unit/README.rst
  sale_order_secondary_unit/__manifest__.py
  sale_order_secondary_unit/i18n/de.po
  sale_order_secondary_unit/i18n/es.po
  sale_order_secondary_unit/i18n/sale_order_secondary_unit.pot
  sale_order_secondary_unit/i18n/zh_CN.po
  sale_order_secondary_unit/readme/CONFIGURE.rst
  sale_order_secondary_unit/readme/CONTRIBUTORS.rst
  sale_order_secondary_unit/static/description/index.html
  sale_order_secondary_unit/views/product_secondary_unit_views.xml
  sale_order_type/i18n/it.po
Labels: 15.0

#1355 Syncing from upstream OCA/sale-workflow (16.0)
  sale_tier_validation/i18n/tr.po
Labels: 16.0
