Repository brain-tec/sale-workflow, pull requests merged in 2023-05, with the labels that each got.

#1412 Syncing from upstream OCA/sale-workflow (12.0)
  sale_invoice_policy/i18n/it.po
  sale_rental/i18n/it.po
Labels: 12.0

#1413 Syncing from upstream OCA/sale-workflow (14.0)
  sale_rental/i18n/it.po
  sale_stock_picking_blocking/i18n/es.po
Labels: 14.0

#1414 Syncing from upstream OCA/sale-workflow (15.0)
  sale_rental/i18n/it.po
Labels: 15.0

#1415 Syncing from upstream OCA/sale-workflow (16.0)
  README.md
  sale_automatic_workflow_job/README.rst
  sale_automatic_workflow_job/__init__.py
  sale_automatic_workflow_job/__manifest__.py
  sale_automatic_workflow_job/data/queue_job_data.xml
  sale_automatic_workflow_job/i18n/sale_automatic_workflow_job.pot
  sale_automatic_workflow_job/models/__init__.py
  sale_automatic_workflow_job/models/automatic_workflow_job.py
  sale_automatic_workflow_job/models/queue_job.py
  sale_automatic_workflow_job/readme/CONTRIBUTORS.rst
  sale_automatic_workflow_job/readme/DESCRIPTION.rst
  sale_automatic_workflow_job/static/description/icon.png
  sale_automatic_workflow_job/static/description/index.html
  sale_automatic_workflow_job/tests/__init__.py
  sale_automatic_workflow_job/tests/test_auto_workflow_job.py
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_automatic_workflow_job/odoo/addons/sale_automatic_workflow_job
  setup/sale_automatic_workflow_job/setup.py
Labels: 16.0

#1416 Syncing from upstream OCA/sale-workflow (15.0)
  sale_order_line_price_history/i18n/fr.po
  sale_stock_picking_blocking/i18n/es.po
Labels: 15.0

#1417 Syncing from upstream OCA/sale-workflow (16.0)
  README.md
  sale_exception/__manifest__.py
  sale_exception/tests/test_sale_exception.py
  sale_exception/wizard/sale_exception_confirm.py
  sale_exception/wizard/sale_exception_confirm_view.xml
Labels: 16.0

#1418 Syncing from upstream OCA/sale-workflow (15.0)
  sale_order_line_price_history/i18n/fr.po
Labels: 15.0

#1419 Syncing from upstream OCA/sale-workflow (16.0)
  README.md
  sale_partner_selectable_option/README.rst
  sale_partner_selectable_option/__init__.py
  sale_partner_selectable_option/__manifest__.py
  sale_partner_selectable_option/i18n/es.po
  sale_partner_selectable_option/i18n/sale_partner_selectable_option.pot
  sale_partner_selectable_option/models/__init__.py
  sale_partner_selectable_option/models/res_partner.py
  sale_partner_selectable_option/models/sale_order.py
  sale_partner_selectable_option/readme/CONTRIBUTORS.rst
  sale_partner_selectable_option/readme/DESCRIPTION.rst
  sale_partner_selectable_option/readme/USAGE.rst
  sale_partner_selectable_option/static/description/icon.png
  sale_partner_selectable_option/static/description/index.html
  sale_partner_selectable_option/tests/__init__.py
  sale_partner_selectable_option/tests/test_sale_partner_selectable_option.py
  sale_partner_selectable_option/views/res_partner_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_partner_selectable_option/odoo/addons/sale_partner_selectable_option
  setup/sale_partner_selectable_option/setup.py
Labels: 16.0

#1420 Syncing from upstream OCA/sale-workflow (16.0)
  README.md
  sale_order_qty_change_no_recompute/README.rst
  sale_order_qty_change_no_recompute/__init__.py
  sale_order_qty_change_no_recompute/__manifest__.py
  sale_order_qty_change_no_recompute/i18n/sale_order_qty_change_no_recompute.pot
  sale_order_qty_change_no_recompute/monkeypatching.py
  sale_order_qty_change_no_recompute/readme/CONTRIBUTORS.rst
  sale_order_qty_change_no_recompute/readme/DESCRIPTION.rst
  sale_order_qty_change_no_recompute/readme/ROADMAP.rst
  sale_order_qty_change_no_recompute/readme/USAGE.rst
  sale_order_qty_change_no_recompute/static/description/icon.png
  sale_order_qty_change_no_recompute/static/description/index.html
  sale_order_qty_change_no_recompute/tests/__init__.py
  sale_order_qty_change_no_recompute/tests/test_sale_order_qty_change.py
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_order_qty_change_no_recompute/odoo/addons/sale_order_qty_change_no_recompute
  setup/sale_order_qty_change_no_recompute/setup.py
Labels: 16.0

#1422 Syncing from upstream OCA/sale-workflow (15.0)
  README.md
  sale_order_line_input/__manifest__.py
  sale_order_line_input/models/sale_order.py
  sale_order_partner_restrict/tests/test_sale_order_partner_restrict.py
  sale_order_revision/README.rst
  sale_order_revision/__init__.py
  sale_order_revision/__manifest__.py
  sale_order_revision/i18n/sale_order_revision.pot
  sale_order_revision/models/__init__.py
  sale_order_revision/models/sale_order.py
  sale_order_revision/readme/CONTRIBUTORS.rst
  sale_order_revision/readme/DESCRIPTION.rst
  sale_order_revision/readme/INSTALL.rst
  sale_order_revision/static/description/icon.png
  sale_order_revision/static/description/index.html
  sale_order_revision/tests/__init__.py
  sale_order_revision/tests/test_sale_order_revision.py
  sale_order_revision/view/sale_order.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_order_revision/odoo/addons/sale_order_revision
  setup/sale_order_revision/setup.py
  test-requirements.txt
Labels: 15.0

#1423 Syncing from upstream OCA/sale-workflow (8.0)
  sale_order_add_variants/i18n/it.po
  sale_order_weight/i18n/it.po
  sale_rental/i18n/it.po
  sale_service_project/i18n/it.po
  sale_start_end_dates/i18n/it.po
Labels: 8.0

#1424 Syncing from upstream OCA/sale-workflow (9.0)
  sale_start_end_dates/i18n/it.po
Labels: 9.0

#1425 Syncing from upstream OCA/sale-workflow (10.0)
  product_margin_classification/i18n/it.po
  product_supplierinfo_for_customer_sale/i18n/it.po
  sale_rental/i18n/it.po
  sale_start_end_dates/i18n/it.po
Labels: 10.0

#1426 Syncing from upstream OCA/sale-workflow (11.0)
  product_supplierinfo_for_customer_sale/i18n/it.po
  sale_start_end_dates/i18n/it.po
Labels: 11.0

#1427 Syncing from upstream OCA/sale-workflow (12.0)
  sale_rental/i18n/it.po
  sale_start_end_dates/i18n/it.po
Labels: 12.0

#1428 Syncing from upstream OCA/sale-workflow (13.0)
  product_supplierinfo_for_customer_sale/i18n/it.po
Labels: 13.0

#1429 Syncing from upstream OCA/sale-workflow (14.0)
  product_supplierinfo_for_customer_sale/i18n/it.po
  sale_rental/i18n/it.po
  sale_start_end_dates/i18n/it.po
Labels: 14.0

#1432 Syncing from upstream OCA/sale-workflow (16.0)
  README.md
  sale_order_revision/README.rst
  sale_order_revision/__init__.py
  sale_order_revision/__manifest__.py
  sale_order_revision/i18n/sale_order_revision.pot
  sale_order_revision/models/__init__.py
  sale_order_revision/models/sale_order.py
  sale_order_revision/readme/CONTRIBUTORS.rst
  sale_order_revision/readme/DESCRIPTION.rst
  sale_order_revision/readme/INSTALL.rst
  sale_order_revision/static/description/icon.png
  sale_order_revision/static/description/index.html
  sale_order_revision/tests/__init__.py
  sale_order_revision/tests/test_sale_order_revision.py
  sale_order_revision/view/sale_order.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_order_revision/odoo/addons/sale_order_revision
  setup/sale_order_revision/setup.py
  test-requirements.txt
Labels: 16.0

#1433 Syncing from upstream OCA/sale-workflow (14.0)
  README.md
  sale_stock_line_customer_ref/README.rst
  sale_stock_line_customer_ref/__init__.py
  sale_stock_line_customer_ref/__manifest__.py
  sale_stock_line_customer_ref/hooks.py
  sale_stock_line_customer_ref/i18n/sale_stock_line_customer_ref.pot
  sale_stock_line_customer_ref/models/__init__.py
  sale_stock_line_customer_ref/models/sale_order_line.py
  sale_stock_line_customer_ref/models/stock_move.py
  sale_stock_line_customer_ref/models/stock_move_line.py
  sale_stock_line_customer_ref/models/stock_package_level.py
  sale_stock_line_customer_ref/models/stock_picking.py
  sale_stock_line_customer_ref/models/stock_quant_package.py
  sale_stock_line_customer_ref/readme/CONTRIBUTORS.rst
  sale_stock_line_customer_ref/readme/DESCRIPTION.rst
  sale_stock_line_customer_ref/readme/USAGE.rst
  sale_stock_line_customer_ref/static/description/icon.png
  sale_stock_line_customer_ref/static/description/index.html
  sale_stock_line_customer_ref/tests/__init__.py
  sale_stock_line_customer_ref/tests/test_customer_ref.py
  sale_stock_line_customer_ref/views/sale_order.xml
  sale_stock_line_customer_ref/views/stock_move.xml
  sale_stock_line_customer_ref/views/stock_move_line.xml
  sale_stock_line_customer_ref/views/stock_package_level.xml
  sale_stock_line_customer_ref/views/stock_picking.xml
  sale_stock_line_customer_ref/views/stock_quant_package.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_stock_line_customer_ref/odoo/addons/sale_stock_line_customer_ref
  setup/sale_stock_line_customer_ref/setup.py
Labels: 14.0

#1434 Syncing from upstream OCA/sale-workflow (15.0)
  README.md
  sale_planner_calendar/__manifest__.py
  sale_planner_calendar/migrations/15.0.1.0.1/post-migration.py
  sale_planner_calendar/models/sale_planner_calendar_event.py
  sale_planner_calendar/models/sale_planner_calendar_summary.py
  sale_planner_calendar/wizard/sale_planner_calendar_reassign.py
  sale_planner_calendar/wizard/sale_planner_calendar_wizard.py
Labels: 15.0

#1435 Syncing from upstream OCA/sale-workflow (8.0)
  sale_order_add_variants/i18n/it.po
  sale_service_project/i18n/it.po
Labels: 8.0

#1436 Syncing from upstream OCA/sale-workflow (9.0)
  sale_packaging_price/i18n/it.po
Labels: 9.0

#1437 Syncing from upstream OCA/sale-workflow (10.0)
  product_margin_classification/i18n/it.po
Labels: 10.0

#1438 Syncing from upstream OCA/sale-workflow (12.0)
  product_supplierinfo_for_customer_sale/i18n/it.po
  sale_order_invoicing_finished_task/i18n/it.po
  sale_order_line_date/i18n/it.po
  sale_order_line_description/i18n/it.po
  sale_order_lot_generator/i18n/it.po
  sale_procurement_group_by_line/i18n/it.po
  sale_start_end_dates/i18n/it.po
Labels: 12.0

#1439 Syncing from upstream OCA/sale-workflow (13.0)
  sale_order_lot_selection/i18n/it.po
Labels: 13.0

#1440 Syncing from upstream OCA/sale-workflow (14.0)
  README.md
  sale_order_type/__manifest__.py
  sale_order_type/tests/test_sale_order_type.py
Labels: 14.0

#1441 Syncing from upstream OCA/sale-workflow (15.0)
  README.md
  sale_order_line_date/i18n/it.po
  sale_order_line_description/i18n/it.po
  sale_order_line_sequence/i18n/it.po
  sale_planner_calendar/__manifest__.py
  sale_planner_calendar/i18n/es.po
  sale_planner_calendar/i18n/sale_planner_calendar.pot
  sale_planner_calendar/models/res_partner.py
  sale_planner_calendar/models/sale_order.py
  sale_planner_calendar/models/sale_planner_calendar_summary.py
  sale_procurement_group_by_line/i18n/it.po
  sale_rental/i18n/it.po
  sale_sourced_by_line/i18n/it.po
  sale_start_end_dates/i18n/it.po
Labels: 15.0

#1442 Syncing from upstream OCA/sale-workflow (16.0)
  sale_exception/i18n/fr.po
  sale_stock_picking_blocking/i18n/it.po
Labels: 16.0

#1443 Syncing from upstream OCA/sale-workflow (16.0)
  .eslintrc.yml
  README.md
  sale_order_line_price_history/README.rst
  sale_order_line_price_history/__init__.py
  sale_order_line_price_history/__manifest__.py
  sale_order_line_price_history/i18n/de.po
  sale_order_line_price_history/i18n/es.po
  sale_order_line_price_history/i18n/pt.po
  sale_order_line_price_history/i18n/sale_order_line_price_history.pot
  sale_order_line_price_history/i18n/zh_CN.po
  sale_order_line_price_history/models/__init__.py
  sale_order_line_price_history/models/sale_order_line.py
  sale_order_line_price_history/readme/CONTRIBUTORS.rst
  sale_order_line_price_history/readme/DESCRIPTION.rst
  sale_order_line_price_history/readme/ROADMAP.rst
  sale_order_line_price_history/readme/USAGE.rst
  sale_order_line_price_history/security/ir.model.access.csv
  sale_order_line_price_history/static/description/icon.png
  sale_order_line_price_history/static/description/index.html
  sale_order_line_price_history/static/src/js/sale_line_price_history_widget.js
  sale_order_line_price_history/static/src/xml/sale_line_price_history_widget.xml
  sale_order_line_price_history/tests/__init__.py
  sale_order_line_price_history/tests/test_sale_order_line_price_history.py
  sale_order_line_price_history/views/sale_views.xml
  sale_order_line_price_history/wizards/__init__.py
  sale_order_line_price_history/wizards/sale_order_line_price_history.py
  sale_order_line_price_history/wizards/sale_order_line_price_history.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_order_line_price_history/odoo/addons/sale_order_line_price_history
  setup/sale_order_line_price_history/setup.py
Labels: 16.0

#1445 Syncing from upstream OCA/sale-workflow (15.0)
  README.md
  sale_order_type/__manifest__.py
  sale_order_type/tests/test_sale_order_type.py
Labels: 15.0

#1446 Syncing from upstream OCA/sale-workflow (16.0)
  README.md
  sale_order_product_availability_inline/README.rst
  sale_order_product_availability_inline/__init__.py
  sale_order_product_availability_inline/__manifest__.py
  sale_order_product_availability_inline/i18n/ca.po
  sale_order_product_availability_inline/i18n/es.po
  sale_order_product_availability_inline/i18n/sale_order_product_availability_inline.pot
  sale_order_product_availability_inline/models/__init__.py
  sale_order_product_availability_inline/models/product_product.py
  sale_order_product_availability_inline/models/sale.py
  sale_order_product_availability_inline/readme/CONTRIBUTORS.rst
  sale_order_product_availability_inline/readme/DESCRIPTION.rst
  sale_order_product_availability_inline/readme/USAGE.rst
  sale_order_product_availability_inline/static/description/icon.png
  sale_order_product_availability_inline/static/description/index.html
  sale_order_product_availability_inline/tests/__init__.py
  sale_order_product_availability_inline/tests/test_sale_order_product_availability_inline.py
  sale_order_product_availability_inline/views/sale_views.xml
  sale_order_type/__manifest__.py
  sale_order_type/tests/test_sale_order_type.py
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_order_product_availability_inline/odoo/addons/sale_order_product_availability_inline
  setup/sale_order_product_availability_inline/setup.py
Labels: 16.0

#1447 Syncing from upstream OCA/sale-workflow (15.0)
  README.md
  sale_planner_calendar/__manifest__.py
  sale_planner_calendar/models/sale_order.py
Labels: 15.0

#1448 Syncing from upstream OCA/sale-workflow (16.0)
  README.md
  sale_partner_incoterm/README.rst
  sale_partner_incoterm/__init__.py
  sale_partner_incoterm/__manifest__.py
  sale_partner_incoterm/i18n/ca.po
  sale_partner_incoterm/i18n/de.po
  sale_partner_incoterm/i18n/es.po
  sale_partner_incoterm/i18n/fi.po
  sale_partner_incoterm/i18n/fr.po
  sale_partner_incoterm/i18n/it.po
  sale_partner_incoterm/i18n/nl.po
  sale_partner_incoterm/i18n/sale_partner_incoterm.pot
  sale_partner_incoterm/i18n/sl.po
  sale_partner_incoterm/i18n/tr.po
  sale_partner_incoterm/i18n/zh_CN.po
  sale_partner_incoterm/models/__init__.py
  sale_partner_incoterm/models/res_partner.py
  sale_partner_incoterm/models/sale_order.py
  sale_partner_incoterm/readme/CONTRIBUTORS.rst
  sale_partner_incoterm/readme/DESCRIPTION.rst
  sale_partner_incoterm/static/description/icon.png
  sale_partner_incoterm/static/description/index.html
  sale_partner_incoterm/tests/__init__.py
  sale_partner_incoterm/tests/test_sale_partner_incoterm.py
  sale_partner_incoterm/views/res_partner.xml
  sale_partner_incoterm/views/sale_order.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_partner_incoterm/odoo/addons/sale_partner_incoterm
  setup/sale_partner_incoterm/setup.py
Labels: 16.0

#1449 Syncing from upstream OCA/sale-workflow (8.0)
  sale_comment_propagation/i18n/it.po
Labels: 8.0

#1450 Syncing from upstream OCA/sale-workflow (11.0)
  sale_order_line_input/i18n/it.po
Labels: 11.0

#1451 Syncing from upstream OCA/sale-workflow (12.0)
  sale_manual_delivery/i18n/it.po
Labels: 12.0

#1452 Syncing from upstream OCA/sale-workflow (15.0)
  README.md
  sale_order_type/__manifest__.py
  sale_order_type/models/sale.py
Labels: 15.0

#1453 Syncing from upstream OCA/sale-workflow (16.0)
  sale_partner_incoterm/i18n/ca.po
  sale_partner_incoterm/i18n/de.po
  sale_partner_incoterm/i18n/es.po
  sale_partner_incoterm/i18n/fi.po
  sale_partner_incoterm/i18n/fr.po
  sale_partner_incoterm/i18n/it.po
  sale_partner_incoterm/i18n/nl.po
  sale_partner_incoterm/i18n/sl.po
  sale_partner_incoterm/i18n/tr.po
  sale_partner_incoterm/i18n/zh_CN.po
Labels: 16.0

#1454 Syncing from upstream OCA/sale-workflow (8.0)
  sale_automatic_workflow/i18n/it.po
  sale_order_type/i18n/it.po
Labels: 8.0

#1455 Syncing from upstream OCA/sale-workflow (9.0)
  sale_order_type/i18n/it.po
Labels: 9.0

#1456 Syncing from upstream OCA/sale-workflow (10.0)
  sale_automatic_workflow/i18n/it.po
  sale_order_type/i18n/it.po
Labels: 10.0

#1457 Syncing from upstream OCA/sale-workflow (11.0)
  sale_automatic_workflow/i18n/it.po
  sale_order_type/i18n/it.po
Labels: 11.0

#1458 Syncing from upstream OCA/sale-workflow (12.0)
  sale_automatic_workflow/i18n/it.po
  sale_order_type/i18n/it.po
Labels: 12.0

#1459 Syncing from upstream OCA/sale-workflow (13.0)
  sale_automatic_workflow/i18n/it.po
  sale_order_type/i18n/it.po
Labels: 13.0

#1460 Syncing from upstream OCA/sale-workflow (14.0)
  README.md
  sale_advance_payment/README.rst
  sale_advance_payment/__manifest__.py
  sale_advance_payment/i18n/es.po
  sale_advance_payment/i18n/fr.po
  sale_advance_payment/i18n/pt_BR.po
  sale_advance_payment/i18n/sale_advance_payment.pot
  sale_advance_payment/readme/CONTRIBUTORS.rst
  sale_advance_payment/static/description/index.html
  sale_advance_payment/tests/test_sale_advance_payment.py
  sale_advance_payment/wizard/sale_advance_payment_wzd.py
  sale_automatic_workflow/i18n/it.po
  sale_order_type/i18n/it.po
Labels: 14.0

#1461 Syncing from upstream OCA/sale-workflow (15.0)
  README.md
  product_supplierinfo_for_customer_elaboration/README.rst
  product_supplierinfo_for_customer_elaboration/__manifest__.py
  product_supplierinfo_for_customer_elaboration/i18n/es.po
  product_supplierinfo_for_customer_elaboration/i18n/product_supplierinfo_for_customer_elaboration.pot
  product_supplierinfo_for_customer_elaboration/models/sale_order_line.py
  product_supplierinfo_for_customer_elaboration/readme/CONTRIBUTORS.rst
  product_supplierinfo_for_customer_elaboration/static/description/index.html
  sale_automatic_workflow/i18n/it.po
  sale_order_type/i18n/it.po
Labels: 15.0

#1462 Syncing from upstream OCA/sale-workflow (16.0)
  sale_automatic_workflow/i18n/it.po
  sale_order_type/i18n/it.po
Labels: 16.0

#1463 Syncing from upstream OCA/sale-workflow (15.0)
  README.md
  sale_advance_payment/README.rst
  sale_advance_payment/__manifest__.py
  sale_advance_payment/i18n/fr.po
  sale_advance_payment/i18n/sale_advance_payment.pot
  sale_advance_payment/readme/CONTRIBUTORS.rst
  sale_advance_payment/static/description/index.html
  sale_advance_payment/tests/test_sale_advance_payment.py
  sale_advance_payment/wizard/sale_advance_payment_wzd.py
  sale_order_qty_change_no_recompute/__manifest__.py
  sale_order_qty_change_no_recompute/tests/test_sale_order_qty_change.py
  sale_order_secondary_unit/__manifest__.py
  sale_order_secondary_unit/i18n/de.po
  sale_order_secondary_unit/i18n/es.po
  sale_order_secondary_unit/i18n/sale_order_secondary_unit.pot
  sale_order_secondary_unit/i18n/zh_CN.po
  sale_order_secondary_unit/models/__init__.py
  sale_order_secondary_unit/models/product.py
  sale_order_secondary_unit/models/product_template.py
  sale_order_secondary_unit/models/sale_order.py
  sale_order_secondary_unit/tests/test_sale_order_secondary_unit.py
  sale_order_secondary_unit/views/product_views.xml
  sale_order_secondary_unit/views/sale_order_views.xml
  sale_planner_calendar/__manifest__.py
  sale_planner_calendar/i18n/es.po
  sale_planner_calendar/i18n/sale_planner_calendar.pot
  sale_planner_calendar/views/sale_planner_calendar_summary_view.xml
Labels: 15.0

#1464 Syncing from upstream OCA/sale-workflow (8.0)
  sale_order_merge/i18n/it.po
  sale_payment_method/i18n/it.po
  sale_payment_method_automatic_workflow/i18n/it.po
Labels: 8.0

#1465 Syncing from upstream OCA/sale-workflow (9.0)
  sale_cancel_reason/i18n/it.po
  sale_order_variant_mgmt/i18n/it.po
  sale_product_set/i18n/it.po
  sale_rental/i18n/it.po
Labels: 9.0

#1466 Syncing from upstream OCA/sale-workflow (10.0)
  sale_cancel_reason/i18n/it.po
  sale_isolated_quotation/i18n/it.po
  sale_product_set/i18n/it.po
  sale_rental/i18n/it.po
Labels: 10.0

#1467 Syncing from upstream OCA/sale-workflow (11.0)
  sale_isolated_quotation/i18n/it.po
  sale_product_set/i18n/it.po
Labels: 11.0

#1468 Syncing from upstream OCA/sale-workflow (12.0)
  sale_blanket_order/i18n/it.po
Labels: 12.0

#1469 Syncing from upstream OCA/sale-workflow (14.0)
  .copier-answers.yml
  .github/workflows/test.yml
  README.md
  sale_procurement_group_by_commitment_date/README.rst
  sale_procurement_group_by_commitment_date/__init__.py
  sale_procurement_group_by_commitment_date/__manifest__.py
  sale_procurement_group_by_commitment_date/i18n/ca.po
  sale_procurement_group_by_commitment_date/i18n/de.po
  sale_procurement_group_by_commitment_date/i18n/el_GR.po
  sale_procurement_group_by_commitment_date/i18n/es.po
  sale_procurement_group_by_commitment_date/i18n/es_ES.po
  sale_procurement_group_by_commitment_date/i18n/es_VE.po
  sale_procurement_group_by_commitment_date/i18n/fi.po
  sale_procurement_group_by_commitment_date/i18n/fr.po
  sale_procurement_group_by_commitment_date/i18n/hr.po
  sale_procurement_group_by_commitment_date/i18n/hr_HR.po
  sale_procurement_group_by_commitment_date/i18n/hu.po
  sale_procurement_group_by_commitment_date/i18n/it.po
  sale_procurement_group_by_commitment_date/i18n/nl.po
  sale_procurement_group_by_commitment_date/i18n/nl_NL.po
  sale_procurement_group_by_commitment_date/i18n/pt.po
  sale_procurement_group_by_commitment_date/i18n/pt_BR.po
  sale_procurement_group_by_commitment_date/i18n/ro.po
  sale_procurement_group_by_commitment_date/i18n/sale_procurement_group_by_commitment_date.pot
  sale_procurement_group_by_commitment_date/i18n/sale_procurement_group_by_requested_date.pot
  sale_procurement_group_by_commitment_date/i18n/sl.po
  sale_procurement_group_by_commitment_date/i18n/tr.po
  sale_procurement_group_by_commitment_date/i18n/tr_TR.po
  sale_procurement_group_by_commitment_date/i18n/vi_VN.po
  sale_procurement_group_by_commitment_date/i18n/zh_CN.po
  sale_procurement_group_by_commitment_date/models/__init__.py
  sale_procurement_group_by_commitment_date/models/sale_order.py
  sale_procurement_group_by_commitment_date/readme/CONTRIBUTORS.rst
  sale_procurement_group_by_commitment_date/readme/DESCRIPTION.rst
  sale_procurement_group_by_commitment_date/readme/INSTALL.rst
  sale_procurement_group_by_commitment_date/readme/ROADMAP.rst
  sale_procurement_group_by_commitment_date/readme/USAGE.rst
  sale_procurement_group_by_commitment_date/static/description/icon.png
  sale_procurement_group_by_commitment_date/static/description/index.html
  sale_procurement_group_by_commitment_date/tests/__init__.py
  sale_procurement_group_by_commitment_date/tests/test_sale_procurement_group_by_commitment_date.py
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_procurement_group_by_commitment_date/odoo/addons/sale_procurement_group_by_commitment_date
  setup/sale_procurement_group_by_commitment_date/setup.py
Labels: 14.0

#1471 [t137855] Forcing a company to the rental route to fix issues under m…
  sale_rental/data/rental_data.xml
Labels: 15.0.project_sc_691

#1472 Syncing from upstream OCA/sale-workflow (8.0)
  product_margin_classification/i18n/it.po
  sale_automatic_workflow/i18n/it.po
  sale_cancel_reason/i18n/it.po
  sale_change_price/i18n/it.po
  sale_exceptions/i18n/it.po
  sale_order_merge/i18n/it.po
  sale_order_type/i18n/it.po
  sale_packaging_price/i18n/it.po
  sale_payment_method/i18n/it.po
  sale_product_set/i18n/it.po
  sale_properties_easy_creation/i18n/it.po
  sale_quick_payment/i18n/it.po
  sale_quotation_sourcing/i18n/it.po
  sale_reason_to_export/i18n/it.po
  sale_rental/i18n/it.po
  sales_team_security/i18n/it.po
Labels: 8.0

#1473 Syncing from upstream OCA/sale-workflow (9.0)
  sale_automatic_workflow/i18n/it.po
  sale_delivery_block/i18n/it.po
  sale_exception/i18n/it.po
  sale_order_variant_mgmt/i18n/it.po
  sale_rental/i18n/it.po
Labels: 9.0

#1474 Syncing from upstream OCA/sale-workflow (14.0)
  README.md
  pricelist_cache/__manifest__.py
  pricelist_cache/models/product_pricelist.py
Labels: 14.0

#1476 Syncing from upstream OCA/sale-workflow (8.0)
  sale_product_multi_add/i18n/it.po
Labels: 8.0

#1477 Syncing from upstream OCA/sale-workflow (10.0)
  product_price_category/i18n/it.po
  sale_automatic_workflow/i18n/it.po
  sale_cancel_reason/i18n/it.po
  sale_exception/i18n/it.po
  sale_invoice_group_method/i18n/it.po
  sale_order_type/i18n/it.po
  sale_product_set/i18n/it.po
  sale_rental/i18n/it.po
  sale_stock_picking_blocking/i18n/it.po
Labels: 10.0

#1478 Syncing from upstream OCA/sale-workflow (11.0)
  sale_automatic_workflow/i18n/it.po
  sale_exception/i18n/it.po
  sale_invoice_group_method/i18n/it.po
  sale_order_type/i18n/it.po
  sale_product_set/i18n/it.po
  sale_product_set_variant/i18n/it.po
  sale_stock_picking_blocking/i18n/it.po
Labels: 11.0

#1481 Syncing from upstream OCA/sale-workflow (9.0)
  sale_product_set/i18n/it.po
Labels: 9.0
