Repository brain-tec/sale-workflow, pull requests merged in 2023-04, with the labels that each got.

#1356 Syncing from upstream OCA/sale-workflow (8.0)
  sale_order_add_variants/i18n/sl.po
  sale_service_project/i18n/sl.po
Labels: 8.0

#1357 Syncing from upstream OCA/sale-workflow (9.0)
  sale_packaging_price/i18n/sl.po
Labels: 9.0

#1358 Syncing from upstream OCA/sale-workflow (13.0)
  sale_cancel_reason/i18n/sl.po
  sale_exception/i18n/sl.po
  sale_product_set/i18n/sl.po
Labels: 13.0

#1359 Syncing from upstream OCA/sale-workflow (14.0)
  sale_automatic_workflow/i18n/sl.po
  sale_exception/i18n/sl.po
  sale_order_type/i18n/sl.po
  sale_product_set/i18n/sl.po
  sale_rental/i18n/sl.po
  sale_stock_picking_blocking/i18n/sl.po
Labels: 14.0

#1360 Syncing from upstream OCA/sale-workflow (15.0)
  sale_automatic_workflow/i18n/sl.po
  sale_exception/i18n/sl.po
  sale_product_set/i18n/sl.po
  sale_stock_picking_blocking/i18n/sl.po
Labels: 15.0

#1361 Syncing from upstream OCA/sale-workflow (15.0)
  README.md
  product_supplierinfo_for_customer_sale/__manifest__.py
  product_supplierinfo_for_customer_sale/i18n/ca.po
  product_supplierinfo_for_customer_sale/i18n/de.po
  product_supplierinfo_for_customer_sale/i18n/es.po
  product_supplierinfo_for_customer_sale/i18n/it.po
  product_supplierinfo_for_customer_sale/i18n/product_supplierinfo_for_customer_sale.pot
  product_supplierinfo_for_customer_sale/i18n/pt.po
  product_supplierinfo_for_customer_sale/views/product_customerinfo_views.xml
Labels: 15.0

#1362 Syncing from upstream OCA/sale-workflow (12.0)
  sale_blanket_order/i18n/it.po
Labels: 12.0

#1363 Syncing from upstream OCA/sale-workflow (8.0)
  sales_team_security/i18n/it.po
Labels: 8.0

#1364 Syncing from upstream OCA/sale-workflow (12.0)
  sale_blanket_order/i18n/it.po
Labels: 12.0

#1365 Syncing from upstream OCA/sale-workflow (12.0)
  sale_blanket_order/i18n/it.po
  sale_invoice_plan/i18n/it.po
Labels: 12.0

#1366 Syncing from upstream OCA/sale-workflow (15.0)
  README.md
  sale_order_discount_invoicing/README.rst
  sale_order_discount_invoicing/__init__.py
  sale_order_discount_invoicing/__manifest__.py
  sale_order_discount_invoicing/i18n/fr.po
  sale_order_discount_invoicing/i18n/sale_order_discount_invoicing.pot
  sale_order_discount_invoicing/models/__init__.py
  sale_order_discount_invoicing/models/account_move.py
  sale_order_discount_invoicing/models/account_move_line.py
  sale_order_discount_invoicing/models/product_category.py
  sale_order_discount_invoicing/models/product_template.py
  sale_order_discount_invoicing/models/res_company.py
  sale_order_discount_invoicing/models/res_config_settings.py
  sale_order_discount_invoicing/models/sale_order_line.py
  sale_order_discount_invoicing/readme/CONFIGURE.rst
  sale_order_discount_invoicing/readme/DESCRIPTION.rst
  sale_order_discount_invoicing/readme/USAGE.rst
  sale_order_discount_invoicing/static/description/icon.png
  sale_order_discount_invoicing/static/description/index.html
  sale_order_discount_invoicing/tests/__init__.py
  sale_order_discount_invoicing/tests/test_sale_discount.py
  sale_order_discount_invoicing/views/product_category.xml
  sale_order_discount_invoicing/views/product_template.xml
  sale_order_discount_invoicing/views/res_config_settings.xml
  sale_order_discount_invoicing/views/sale_order.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_order_discount_invoicing/odoo/addons/sale_order_discount_invoicing
  setup/sale_order_discount_invoicing/setup.py
Labels: 15.0

#1367 Syncing from upstream OCA/sale-workflow (8.0)
  sale_automatic_workflow/i18n/it.po
  sale_cancel_reason/i18n/it.po
  sale_comment_propagation/i18n/it.po
  sale_delivery_split_date/i18n/it.po
  sale_exception_nostock/i18n/it.po
  sale_exceptions/i18n/it.po
  sale_line_price_properties_based/i18n/it.po
  sale_line_quantity_properties_based/i18n/it.po
  sale_order_add_variants/i18n/it.po
  sale_order_calendar_event/i18n/it.po
  sale_order_line_date/i18n/it.po
  sale_order_line_description/i18n/it.po
  sale_order_line_variant_description/i18n/it.po
  sale_order_lot_selection/i18n/it.po
  sale_order_type/i18n/it.po
  sale_owner_stock_sourcing/i18n/it.po
  sale_packaging_price/i18n/it.po
  sale_partner_incoterm/i18n/it.po
  sale_payment_method/i18n/it.po
  sale_payment_method_automatic_workflow/i18n/it.po
  sale_pricelist_discount/i18n/it.po
  sale_pricelist_triple_discount/i18n/it.po
  sale_procurement_group_by_line/i18n/it.po
  sale_properties_dynamic_fields/i18n/it.po
  sale_quotation_sourcing/i18n/it.po
  sale_quotation_sourcing_stock_route_transit/i18n/it.po
  sale_rental/i18n/it.po
  sale_service_project/i18n/it.po
  sale_sourced_by_line/i18n/it.po
  sale_sourced_by_line_sale_transport_multi_address/i18n/it.po
  sale_start_end_dates/i18n/it.po
  sale_triple_discount/i18n/it.po
  sales_team_security/i18n/it.po
Labels: 8.0

#1368 Syncing from upstream OCA/sale-workflow (9.0)
  sale_automatic_workflow/i18n/it.po
  sale_automatic_workflow_payment_mode/i18n/it.po
  sale_delivery_block/i18n/it.po
  sale_order_line_date/i18n/it.po
  sale_order_lot_selection/i18n/it.po
  sale_packaging_price/i18n/it.po
  sale_procurement_group_by_line/i18n/it.po
  sale_procurement_group_by_requested_date/i18n/it.po
  sale_shipping_info_helper/i18n/it.po
  sale_start_end_dates/i18n/it.po
  sale_validity/i18n/it.po
Labels: 9.0

#1369 Syncing from upstream OCA/sale-workflow (10.0)
  sale_automatic_workflow/i18n/it.po
  sale_delivery_split_date/i18n/it.po
  sale_order_priority/i18n/it.po
  sale_owner_stock_sourcing/i18n/it.po
  sale_procurement_group_by_line/i18n/it.po
  sale_rental/i18n/it.po
  sale_start_end_dates/i18n/it.po
Labels: 10.0

#1370 Syncing from upstream OCA/sale-workflow (11.0)
  sale_automatic_workflow/i18n/it.po
  sale_order_line_input/i18n/it.po
Labels: 11.0

#1371 Syncing from upstream OCA/sale-workflow (12.0)
  sale_automatic_workflow/i18n/it.po
  sale_blanket_order/i18n/it.po
  sale_commercial_partner/i18n/it.po
  sale_delivery_split_date/i18n/it.po
  sale_delivery_state/i18n/it.po
  sale_force_invoiced/i18n/it.po
  sale_invoice_plan/i18n/it.po
  sale_invoice_policy/i18n/it.po
  sale_manual_delivery/i18n/it.po
  sale_order_general_discount/i18n/it.po
  sale_order_line_date/i18n/it.po
  sale_order_line_input/i18n/it.po
  sale_order_lot_selection/i18n/it.po
  sale_order_priority/i18n/it.po
  sale_order_revision/i18n/it.po
  sale_order_secondary_unit/i18n/it.po
  sale_order_tag/i18n/it.po
  sale_procurement_group_by_commitment_date/i18n/it.po
  sale_quotation_number/i18n/it.po
  sale_rental/i18n/it.po
  sale_restricted_qty/i18n/it.po
  sale_stock_picking_blocking/i18n/it.po
  sale_stock_picking_note/i18n/it.po
Labels: 12.0

#1372 Syncing from upstream OCA/sale-workflow (13.0)
  product_supplierinfo_for_customer_sale/i18n/it.po
  sale_automatic_workflow/i18n/it.po
  sale_order_invoicing_finished_task/i18n/it.po
  sale_order_line_date/i18n/it.po
  sale_order_line_description/i18n/it.po
  sale_order_line_sequence/i18n/it.po
  sale_order_priority/i18n/it.po
  sale_order_tag/i18n/it.po
  sale_order_type/i18n/it.po
  sale_procurement_group_by_commitment_date/i18n/it.po
  sale_procurement_group_by_line/i18n/it.po
  sale_sourced_by_line/i18n/it.po
  sale_stock_picking_blocking/i18n/it.po
Labels: 13.0

#1373 Syncing from upstream OCA/sale-workflow (14.0)
  sale_automatic_workflow/i18n/it.po
  sale_delivery_split_date/i18n/it.po
  sale_order_line_input/i18n/it.po
  sale_order_line_sequence/i18n/it.po
  sale_order_tag/i18n/it.po
Labels: 14.0

#1374 Syncing from upstream OCA/sale-workflow (15.0)
  sale_automatic_workflow/i18n/it.po
  sale_delivery_split_date/i18n/it.po
  sale_order_line_input/i18n/it.po
  sale_stock_picking_blocking/i18n/it.po
Labels: 15.0

#1375 Syncing from upstream OCA/sale-workflow (16.0)
  sale_automatic_workflow/i18n/it.po
  sale_stock_picking_blocking/i18n/it.po
Labels: 16.0

#1376 Syncing from upstream OCA/sale-workflow (15.0)
  README.md
  sale_resource_booking/README.rst
  sale_resource_booking/__init__.py
  sale_resource_booking/__manifest__.py
  sale_resource_booking/i18n/es.po
  sale_resource_booking/i18n/fr.po
  sale_resource_booking/i18n/fr_CH.po
  sale_resource_booking/i18n/sale_resource_booking.pot
  sale_resource_booking/models/__init__.py
  sale_resource_booking/models/product_template.py
  sale_resource_booking/models/resource_booking.py
  sale_resource_booking/models/resource_booking_type.py
  sale_resource_booking/models/sale_order.py
  sale_resource_booking/models/sale_order_line.py
  sale_resource_booking/readme/CONFIGURE.rst
  sale_resource_booking/readme/CONTRIBUTORS.rst
  sale_resource_booking/readme/DESCRIPTION.rst
  sale_resource_booking/readme/INSTALL.rst
  sale_resource_booking/readme/USAGE.rst
  sale_resource_booking/security/ir.model.access.csv
  sale_resource_booking/static/description/icon.png
  sale_resource_booking/static/description/index.html
  sale_resource_booking/tests/__init__.py
  sale_resource_booking/tests/test_sale_resource_booking.py
  sale_resource_booking/views/product_template_views.xml
  sale_resource_booking/views/resource_booking_type_views.xml
  sale_resource_booking/views/resource_booking_views.xml
  sale_resource_booking/views/sale_order_views.xml
  sale_resource_booking/wizards/__init__.py
  sale_resource_booking/wizards/resource_booking_sale.py
  sale_resource_booking/wizards/resource_booking_sale_views.xml
  sale_resource_booking/wizards/sale_order_booking_confirm.py
  sale_resource_booking/wizards/sale_order_booking_confirm_views.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_resource_booking/odoo/addons/sale_resource_booking
  setup/sale_resource_booking/setup.py
Labels: 15.0

#1377 Syncing from upstream OCA/sale-workflow (8.0)
  sale_service_project/i18n/sl.po
Labels: 8.0

#1378 Syncing from upstream OCA/sale-workflow (14.0)
  sale_cancel_reason/i18n/sl.po
Labels: 14.0

#1379 Syncing from upstream OCA/sale-workflow (16.0)
  sale_automatic_workflow/i18n/sl.po
  sale_exception/i18n/sl.po
  sale_order_type/i18n/sl.po
  sale_stock_picking_blocking/i18n/sl.po
Labels: 16.0

#1297 [t134622] [MIFR15] [DEV] Migration v15 - sale-workflow (15.0.project_MI_465)
  sale_advance_payment/tests/test_sale_advance_payment.py
  sale_fixed_discount/tests/test_sale_fixed_discount.py
  sale_order_lot_selection/tests/test_sale_order_lot_selection.py
  sale_order_product_recommendation/wizards/sale_order_recommendation.py
Labels: 15.0.project_mi_465

#1380 Syncing from upstream OCA/sale-workflow (12.0)
  sale_blanket_order/i18n/it.po
  sale_order_digitized_signature/i18n/it.po
Labels: 12.0

#1381 Syncing from upstream OCA/sale-workflow (16.0)
  README.md
  product_supplierinfo_for_customer_sale/README.rst
  product_supplierinfo_for_customer_sale/__init__.py
  product_supplierinfo_for_customer_sale/__manifest__.py
  product_supplierinfo_for_customer_sale/i18n/ca.po
  product_supplierinfo_for_customer_sale/i18n/de.po
  product_supplierinfo_for_customer_sale/i18n/es.po
  product_supplierinfo_for_customer_sale/i18n/it.po
  product_supplierinfo_for_customer_sale/i18n/product_supplierinfo_for_customer_sale.pot
  product_supplierinfo_for_customer_sale/i18n/pt.po
  product_supplierinfo_for_customer_sale/models/__init__.py
  product_supplierinfo_for_customer_sale/models/sale_order_line.py
  product_supplierinfo_for_customer_sale/readme/CONTRIBUTORS.rst
  product_supplierinfo_for_customer_sale/readme/DESCRIPTION.rst
  product_supplierinfo_for_customer_sale/readme/ROADMAP.rst
  product_supplierinfo_for_customer_sale/readme/USAGE.rst
  product_supplierinfo_for_customer_sale/security/ir.model.access.csv
  product_supplierinfo_for_customer_sale/static/description/configuration_customer.png
  product_supplierinfo_for_customer_sale/static/description/description_code.png
  product_supplierinfo_for_customer_sale/static/description/description_code_2.png
  product_supplierinfo_for_customer_sale/static/description/icon.png
  product_supplierinfo_for_customer_sale/static/description/index.html
  product_supplierinfo_for_customer_sale/static/description/search_code.png
  product_supplierinfo_for_customer_sale/static/description/search_code_2.png
  product_supplierinfo_for_customer_sale/tests/__init__.py
  product_supplierinfo_for_customer_sale/tests/test_product_name_search.py
  product_supplierinfo_for_customer_sale/tests/test_product_supplierinfo_for_customer_sale.py
  product_supplierinfo_for_customer_sale/views/product_customerinfo_views.xml
  product_supplierinfo_for_customer_sale/views/sale_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/product_supplierinfo_for_customer_sale/odoo/addons/product_supplierinfo_for_customer_sale
  setup/product_supplierinfo_for_customer_sale/setup.py
Labels: 16.0

#1382 Syncing from upstream OCA/sale-workflow (12.0)
  sale_blanket_order/i18n/it.po
Labels: 12.0

#1383 Syncing from upstream OCA/sale-workflow (12.0)
  sale_cancel_reason/i18n/it.po
  sale_isolated_quotation/i18n/it.po
  sale_product_set/i18n/it.po
  sale_rental/i18n/it.po
Labels: 12.0

#1384 Syncing from upstream OCA/sale-workflow (13.0)
  sale_cancel_reason/i18n/it.po
  sale_isolated_quotation/i18n/it.po
  sale_product_set/i18n/it.po
Labels: 13.0

#1385 Syncing from upstream OCA/sale-workflow (14.0)
  sale_cancel_reason/i18n/it.po
Labels: 14.0

#1386 Syncing from upstream OCA/sale-workflow (15.0)
  sale_rental/i18n/it.po
Labels: 15.0

#1388 Syncing from upstream OCA/sale-workflow (12.0)
  sale_manual_delivery/i18n/it.po
  sale_order_tag/i18n/it.po
Labels: 12.0

#1389 Syncing from upstream OCA/sale-workflow (13.0)
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  sale_order_line_description/i18n/en.po
  sale_order_lot_selection/i18n/en.po
  sale_order_price_recalculation/i18n/en.po
  sale_order_tag/i18n/it.po
Labels: 13.0

#1391 Syncing from upstream OCA/sale-workflow (16.0)
  sale_automatic_workflow_payment_mode/i18n/es.po
Labels: 16.0

#1392 [16.0][MIG] sale_order_secondary_unit
  sale_order_secondary_unit/README.rst
  sale_order_secondary_unit/__init__.py
  sale_order_secondary_unit/__manifest__.py
  sale_order_secondary_unit/i18n/de.po
  sale_order_secondary_unit/i18n/es.po
  sale_order_secondary_unit/i18n/sale_order_secondary_unit.pot
  sale_order_secondary_unit/i18n/zh_CN.po
  sale_order_secondary_unit/models/__init__.py
  sale_order_secondary_unit/models/product_product.py
  sale_order_secondary_unit/models/product_template.py
  sale_order_secondary_unit/models/sale_order.py
  sale_order_secondary_unit/readme/CONFIGURE.rst
  sale_order_secondary_unit/readme/CONTRIBUTORS.rst
  sale_order_secondary_unit/readme/DESCRIPTION.rst
  sale_order_secondary_unit/readme/USAGE.rst
  sale_order_secondary_unit/report/sale_report_templates.xml
  sale_order_secondary_unit/static/description/icon.png
  sale_order_secondary_unit/static/description/index.html
  sale_order_secondary_unit/tests/__init__.py
  sale_order_secondary_unit/tests/test_sale_order_secondary_unit.py
  sale_order_secondary_unit/views/product_secondary_unit_views.xml
  sale_order_secondary_unit/views/product_views.xml
  sale_order_secondary_unit/views/sale_order_views.xml
  setup/sale_order_secondary_unit/odoo/addons/sale_order_secondary_unit
  setup/sale_order_secondary_unit/setup.py
Labels: 16.0.project_ba_688

#1393 Syncing from upstream OCA/sale-workflow (8.0)
  sale_properties_easy_creation/i18n/it.po
Labels: 8.0

#1394 Syncing from upstream OCA/sale-workflow (12.0)
  sale_restricted_qty/i18n/it.po
Labels: 12.0

#1395 Syncing from upstream OCA/sale-workflow (14.0)
  sale_restricted_qty/i18n/it.po
Labels: 14.0

#1400 Create deploy.yaml
  .braintec/deploy.yaml
Labels: 15.0.project_mi_465

#1402 Syncing from upstream OCA/sale-workflow (12.0)
  sale_order_tag/i18n/it.po
Labels: 12.0

#1403 Syncing from upstream OCA/sale-workflow (13.0)
  sale_order_tag/i18n/it.po
Labels: 13.0

#1404 Syncing from upstream OCA/sale-workflow (14.0)
  sale_order_tag/i18n/it.po
Labels: 14.0

#1406 Syncing from upstream OCA/sale-workflow (12.0)
  sale_blanket_order/i18n/it.po
Labels: 12.0

#1407 Syncing from upstream OCA/sale-workflow (14.0)
  sale_order_secondary_unit/i18n/fr.po
Labels: 14.0

#1408 Syncing from upstream OCA/sale-workflow (14.0)
  README.md
  sale_global_discount/__init__.py
  sale_global_discount/__manifest__.py
  sale_global_discount/hooks.py
  sale_order_secondary_unit/i18n/fr.po
Labels: 14.0

#1409 Syncing from upstream OCA/sale-workflow (16.0)
  README.md
  sale_invoice_policy/README.rst
  sale_invoice_policy/__init__.py
  sale_invoice_policy/__manifest__.py
  sale_invoice_policy/i18n/ca.po
  sale_invoice_policy/i18n/es.po
  sale_invoice_policy/i18n/es_MX.po
  sale_invoice_policy/i18n/fr.po
  sale_invoice_policy/i18n/pt.po
  sale_invoice_policy/i18n/sale_invoice_policy.pot
  sale_invoice_policy/models/__init__.py
  sale_invoice_policy/models/product_template.py
  sale_invoice_policy/models/res_config_settings.py
  sale_invoice_policy/models/sale_order.py
  sale_invoice_policy/models/sale_order_line.py
  sale_invoice_policy/post_init_hook.py
  sale_invoice_policy/readme/CONTRIBUTORS.rst
  sale_invoice_policy/readme/DESCRIPTION.rst
  sale_invoice_policy/readme/USAGE.rst
  sale_invoice_policy/static/description/icon.png
  sale_invoice_policy/static/description/index.html
  sale_invoice_policy/tests/__init__.py
  sale_invoice_policy/tests/test_sale_invoice_policy.py
  sale_invoice_policy/views/product_template_view.xml
  sale_invoice_policy/views/res_config_settings_view.xml
  sale_invoice_policy/views/sale_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_invoice_policy/odoo/addons/sale_invoice_policy
  setup/sale_invoice_policy/setup.py
Labels: 16.0
