Repository brain-tec/sale-workflow, pull requests merged in 2024-10, with the labels that each got.

#2128 Syncing from upstream OCA/sale-workflow (16.0)
  README.md
  sale_order_line_menu/README.rst
  sale_order_line_menu/__manifest__.py
  sale_order_line_menu/readme/CONTEXT.md
  sale_order_line_menu/readme/DESCRIPTION.md
  sale_order_line_menu/readme/USAGE.md
  sale_order_line_menu/static/description/index.html
  sale_order_line_menu/static/description/sale_order_line_menu.png
  sale_order_line_menu/static/description/sales_order_lines.png
Labels: 16.0

#2129 Syncing from upstream OCA/sale-workflow (16.0)
  README.md
  sale_transaction_form_link/README.rst
  sale_transaction_form_link/__init__.py
  sale_transaction_form_link/__manifest__.py
  sale_transaction_form_link/demo/payment_transaction.xml
  sale_transaction_form_link/i18n/es.po
  sale_transaction_form_link/i18n/sale_transaction_form_link.pot
  sale_transaction_form_link/models/__init__.py
  sale_transaction_form_link/models/sale_order.py
  sale_transaction_form_link/readme/CONTRIBUTORS.rst
  sale_transaction_form_link/readme/DESCRIPTION.rst
  sale_transaction_form_link/readme/USAGE.rst
  sale_transaction_form_link/static/description/icon.png
  sale_transaction_form_link/static/description/index.html
  sale_transaction_form_link/tests/__init__.py
  sale_transaction_form_link/tests/test_sale_order.py
  sale_transaction_form_link/views/sale_order.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_transaction_form_link/odoo/addons/sale_transaction_form_link
  setup/sale_transaction_form_link/setup.py
Labels: 16.0

#2130 Syncing from upstream OCA/sale-workflow (8.0)
  sales_team_security/i18n/it.po
Labels: 8.0

#2131 Syncing from upstream OCA/sale-workflow (15.0)
  README.md
  sale_order_invoicing_finished_task/README.rst
  sale_order_invoicing_finished_task/__manifest__.py
  sale_order_invoicing_finished_task/static/description/index.html
  sale_order_invoicing_finished_task/views/project_view.xml
Labels: 15.0

#2132 Syncing from upstream OCA/sale-workflow (16.0)
  sale_delivery_state/i18n/it.po
  sale_stock_delivery_state/i18n/it.po
  sale_transaction_form_link/i18n/it.po
Labels: 16.0

#2133 Syncing from upstream OCA/sale-workflow (17.0)
  sale_delivery_state/i18n/it.po
Labels: 17.0

#2134 Syncing from upstream OCA/sale-workflow (14.0)
  README.md
  sale_triple_discount/README.rst
  sale_triple_discount/__manifest__.py
  sale_triple_discount/models/sale_order.py
  sale_triple_discount/static/description/index.html
  sale_triple_discount/tests/test_sale_triple_discount.py
Labels: 14.0

#2135 Syncing from upstream OCA/sale-workflow (15.0)
  README.md
  sale_planner_calendar/README.rst
  sale_planner_calendar/__manifest__.py
  sale_planner_calendar/static/description/index.html
  sale_planner_calendar/static/src/js/basic_controller.js
Labels: 15.0

#2136 Syncing from upstream OCA/sale-workflow (14.0)
  README.md
  sale_order_line_input/README.rst
  sale_order_line_input/__manifest__.py
  sale_order_line_input/models/sale_order.py
  sale_order_line_input/static/description/index.html
Labels: 14.0

#2137 Syncing from upstream OCA/sale-workflow (16.0)
  sale_payment_sheet/i18n/it.po
Labels: 16.0

#2138 Syncing from upstream OCA/sale-workflow (16.0)
  product_price_category/i18n/it.po
Labels: 16.0

#2139 Syncing from upstream OCA/sale-workflow (12.0)
  README.md
  sale_order_weight/README.rst
  sale_order_weight/__init__.py
  sale_order_weight/__manifest__.py
  sale_order_weight/i18n/fr.po
  sale_order_weight/models/sale_order_line.py
  sale_order_weight/post_init_hook.py
  sale_order_weight/pre_init_hook.py
  sale_order_weight/static/description/index.html
  sale_order_weight/tests/test_sale_order_weight.py
  sale_order_weight/views/sale_order_view.xml
Labels: 12.0

#2140 Syncing from upstream OCA/sale-workflow (16.0)
  README.md
  sale_triple_discount/README.rst
  sale_triple_discount/__manifest__.py
  sale_triple_discount/models/sale_order_line.py
  sale_triple_discount/static/description/index.html
Labels: 16.0

#2141 Syncing from upstream OCA/sale-workflow (17.0)
  README.md
  sale_force_invoiced/README.rst
  sale_force_invoiced/__manifest__.py
  sale_force_invoiced/i18n/ca.po
  sale_force_invoiced/i18n/de.po
  sale_force_invoiced/i18n/el_GR.po
  sale_force_invoiced/i18n/es.po
  sale_force_invoiced/i18n/es_ES.po
  sale_force_invoiced/i18n/es_VE.po
  sale_force_invoiced/i18n/fi.po
  sale_force_invoiced/i18n/fr.po
  sale_force_invoiced/i18n/hr.po
  sale_force_invoiced/i18n/hr_HR.po
  sale_force_invoiced/i18n/hu.po
  sale_force_invoiced/i18n/it.po
  sale_force_invoiced/i18n/nl.po
  sale_force_invoiced/i18n/nl_NL.po
  sale_force_invoiced/i18n/pt.po
  sale_force_invoiced/i18n/pt_BR.po
  sale_force_invoiced/i18n/ro.po
  sale_force_invoiced/i18n/sale_force_invoiced.pot
  sale_force_invoiced/i18n/sk.po
  sale_force_invoiced/i18n/sl.po
  sale_force_invoiced/i18n/tr.po
  sale_force_invoiced/i18n/tr_TR.po
  sale_force_invoiced/i18n/vi_VN.po
  sale_force_invoiced/i18n/zh_CN.po
  sale_force_invoiced/model/sale_order.py
  sale_force_invoiced/readme/CONTRIBUTORS.md
  sale_force_invoiced/readme/USAGE.md
  sale_force_invoiced/static/description/index.html
  sale_force_invoiced/tests/test_sale_force_invoiced.py
Labels: 17.0

#2142 Syncing from upstream OCA/sale-workflow (18.0)
  .copier-answers.yml
  .eslintrc.yml
  .pre-commit-config.yaml
  .prettierrc.yml
  eslint.config.cjs
  prettier.config.cjs
Labels: 18.0

#2143 Syncing from upstream OCA/sale-workflow (14.0)
  README.md
  product_supplierinfo_for_customer_sale_quick/README.rst
  product_supplierinfo_for_customer_sale_quick/__init__.py
  product_supplierinfo_for_customer_sale_quick/__manifest__.py
  product_supplierinfo_for_customer_sale_quick/i18n/product_supplierinfo_for_customer_sale_quick.pot
  product_supplierinfo_for_customer_sale_quick/models/__init__.py
  product_supplierinfo_for_customer_sale_quick/models/product_product.py
  product_supplierinfo_for_customer_sale_quick/models/sale_order.py
  product_supplierinfo_for_customer_sale_quick/readme/CONTRIBUTORS.rst
  product_supplierinfo_for_customer_sale_quick/readme/DESCRIPTION.rst
  product_supplierinfo_for_customer_sale_quick/static/description/icon.png
  product_supplierinfo_for_customer_sale_quick/static/description/index.html
  product_supplierinfo_for_customer_sale_quick/tests/__init__.py
  product_supplierinfo_for_customer_sale_quick/tests/test_product_supplierinfo_for_customer_sale_quick.py
  product_supplierinfo_for_customer_sale_quick/views/product_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/product_supplierinfo_for_customer_sale_quick/odoo/addons/product_supplierinfo_for_customer_sale_quick
  setup/product_supplierinfo_for_customer_sale_quick/setup.py
Labels: 14.0

#2144 Syncing from upstream OCA/sale-workflow (17.0)
  sale_force_invoiced/i18n/it.po
Labels: 17.0

#2145 Syncing from upstream OCA/sale-workflow (14.0)
  product_supplierinfo_for_customer_sale_quick/i18n/it.po
Labels: 14.0

#2146 Syncing from upstream OCA/sale-workflow (15.0)
  README.md
  sale_order_type/README.rst
  sale_order_type/__manifest__.py
  sale_order_type/models/res_partner.py
  sale_order_type/static/description/index.html
Labels: 15.0

#2147 Syncing from upstream OCA/sale-workflow (17.0)
  README.md
  sale_automatic_workflow/README.rst
  sale_automatic_workflow/__manifest__.py
  sale_automatic_workflow/models/account_move.py
  sale_automatic_workflow/models/automatic_workflow_job.py
  sale_automatic_workflow/models/sale_order.py
  sale_automatic_workflow/static/description/index.html
  sale_automatic_workflow/tests/test_automatic_workflow.py
  sale_discount_display_amount/README.rst
  sale_discount_display_amount/__manifest__.py
  sale_discount_display_amount/hooks.py
  sale_discount_display_amount/i18n/ca.po
  sale_discount_display_amount/i18n/de.po
  sale_discount_display_amount/i18n/es.po
  sale_discount_display_amount/i18n/es_ES.po
  sale_discount_display_amount/i18n/fr.po
  sale_discount_display_amount/i18n/it.po
  sale_discount_display_amount/i18n/nl.po
  sale_discount_display_amount/i18n/sale_discount_display_amount.pot
  sale_discount_display_amount/i18n/zh_CN.po
  sale_discount_display_amount/migrations/17.0.1.1.0/post-compute-subtotal-columns.py
  sale_discount_display_amount/migrations/17.0.1.1.0/pre-add-subtotal-columns.py
  sale_discount_display_amount/models/res_company.py
  sale_discount_display_amount/models/res_config_settings.py
  sale_discount_display_amount/models/sale_order_line.py
  sale_discount_display_amount/report/sale_report_template.xml
  sale_discount_display_amount/static/description/index.html
  sale_discount_display_amount/views/res_config_settings_views.xml
  sale_discount_display_amount/views/sale_view.xml
Labels: 17.0

#2148 Syncing from upstream OCA/sale-workflow (16.0)
  README.md
  sale_order_line_input/i18n/it.po
  sale_planner_calendar/README.rst
  sale_planner_calendar/__manifest__.py
  sale_planner_calendar/models/res_partner.py
  sale_planner_calendar/static/description/index.html
  sale_planner_calendar/tests/test_sale_planner_calendar.py
Labels: 16.0

#2149 Syncing from upstream OCA/sale-workflow (17.0)
  sale_discount_display_amount/i18n/it.po
  sale_order_line_input/i18n/it.po
Labels: 17.0

#2150 [MIG]17.0 sale_order_line_price_history
  sale_order_line_price_history/README.rst
  sale_order_line_price_history/__init__.py
  sale_order_line_price_history/__manifest__.py
  sale_order_line_price_history/i18n/de.po
  sale_order_line_price_history/i18n/es.po
  sale_order_line_price_history/i18n/it.po
  sale_order_line_price_history/i18n/pt.po
  sale_order_line_price_history/i18n/pt_BR.po
  sale_order_line_price_history/i18n/sale_order_line_price_history.pot
  sale_order_line_price_history/i18n/zh_CN.po
  sale_order_line_price_history/models/__init__.py
  sale_order_line_price_history/models/sale_order_line.py
  sale_order_line_price_history/pyproject.toml
  sale_order_line_price_history/readme/CONTRIBUTORS.md
  sale_order_line_price_history/readme/DESCRIPTION.md
  sale_order_line_price_history/readme/ROADMAP.md
  sale_order_line_price_history/readme/USAGE.md
  sale_order_line_price_history/security/ir.model.access.csv
  sale_order_line_price_history/static/description/icon.png
  sale_order_line_price_history/static/description/index.html
  sale_order_line_price_history/static/src/js/sale_line_price_history_widget.esm.js
  sale_order_line_price_history/static/src/js/set_price_to_line_widget.esm.js
  sale_order_line_price_history/static/src/xml/sale_line_price_history_widget.xml
  sale_order_line_price_history/static/src/xml/set_price_to_line_widget.xml
  sale_order_line_price_history/tests/__init__.py
  sale_order_line_price_history/tests/test_sale_order_line_price_history.py
  sale_order_line_price_history/views/sale_views.xml
  sale_order_line_price_history/wizards/__init__.py
  sale_order_line_price_history/wizards/sale_order_line_price_history.py
  sale_order_line_price_history/wizards/sale_order_line_price_history.xml
Labels: 17.0.project_ba_688

#2151 Syncing from upstream OCA/sale-workflow (15.0)
  README.md
  sale_planner_calendar/README.rst
  sale_planner_calendar/__manifest__.py
  sale_planner_calendar/static/description/index.html
  sale_planner_calendar/tests/test_sale_planner_calendar.py
  sale_planner_calendar/wizard/sale_planner_calendar_reassign.py
Labels: 15.0

#2152 Syncing from upstream OCA/sale-workflow (17.0)
  sale_advance_payment/i18n/fr.po
Labels: 17.0

#2153 Syncing from upstream OCA/sale-workflow (15.0)
  README.md
  sale_planner_calendar/README.rst
  sale_planner_calendar/__manifest__.py
  sale_planner_calendar/i18n/ca_ES.po
  sale_planner_calendar/i18n/es.po
  sale_planner_calendar/i18n/sale_planner_calendar.pot
  sale_planner_calendar/static/description/index.html
  sale_planner_calendar/wizard/sale_planner_calendar_reassign.py
  sale_planner_calendar/wizard/sale_planner_calendar_wizard.py
Labels: 15.0

#2154 Syncing from upstream OCA/sale-workflow (16.0)
  README.md
  sale_quotation_number/README.rst
  sale_quotation_number/__manifest__.py
  sale_quotation_number/models/sale_order.py
  sale_quotation_number/static/description/index.html
Labels: 16.0
