Repository brain-tec/sale-workflow, pull requests merged in 2025-04, with the labels that each got.

#2322 Syncing from upstream OCA/sale-workflow (12.0)
  README.md
  sale_discount_display_amount/README.rst
  sale_discount_display_amount/__manifest__.py
  sale_discount_display_amount/i18n/ca.po
  sale_discount_display_amount/i18n/de.po
  sale_discount_display_amount/i18n/es.po
  sale_discount_display_amount/i18n/es_ES.po
  sale_discount_display_amount/i18n/fr.po
  sale_discount_display_amount/i18n/it.po
  sale_discount_display_amount/i18n/pt.po
  sale_discount_display_amount/i18n/sale_discount_display_amount.pot
  sale_discount_display_amount/i18n/zh_CN.po
  sale_discount_display_amount/models/sale_order.py
  sale_discount_display_amount/models/sale_order_line.py
  sale_discount_display_amount/static/description/index.html
Labels: 12.0

#2323 Syncing from upstream OCA/sale-workflow (14.0)
  README.md
  sale_order_line_note/README.rst
  sale_order_line_note/__manifest__.py
  sale_order_line_note/readme/CONTRIBUTORS.rst
  sale_order_line_note/static/description/index.html
  sale_order_note_template/README.rst
  sale_order_note_template/__manifest__.py
  sale_order_note_template/readme/CONTRIBUTORS.rst
  sale_order_note_template/static/description/index.html
Labels: 14.0

#2324 Syncing from upstream OCA/sale-workflow (15.0)
  README.md
  sale_partner_incoterm/README.rst
  sale_partner_incoterm/__manifest__.py
  sale_partner_incoterm/i18n/ca.po
  sale_partner_incoterm/i18n/de.po
  sale_partner_incoterm/i18n/es.po
  sale_partner_incoterm/i18n/fi.po
  sale_partner_incoterm/i18n/fr.po
  sale_partner_incoterm/i18n/it.po
  sale_partner_incoterm/i18n/nl.po
  sale_partner_incoterm/i18n/sale_partner_incoterm.pot
  sale_partner_incoterm/i18n/sl.po
  sale_partner_incoterm/i18n/tr.po
  sale_partner_incoterm/i18n/zh_CN.po
  sale_partner_incoterm/models/res_partner.py
  sale_partner_incoterm/models/sale_order.py
  sale_partner_incoterm/static/description/index.html
  sale_partner_incoterm/tests/test_sale_partner_incoterm.py
  sale_partner_incoterm/views/res_partner.xml
  sale_partner_incoterm/views/sale_order.xml
Labels: 15.0

#2327 Syncing from upstream OCA/sale-workflow (18.0)
  README.md
  sale_order_disable_user_autosubscribe/i18n/it.po
  sale_order_note_template/i18n/it.po
  sale_order_requested_delivery/README.rst
  sale_order_requested_delivery/__init__.py
  sale_order_requested_delivery/__manifest__.py
  sale_order_requested_delivery/i18n/sale_order_requested_delivery.pot
  sale_order_requested_delivery/models/__init__.py
  sale_order_requested_delivery/models/sale_order.py
  sale_order_requested_delivery/models/sale_order_line.py
  sale_order_requested_delivery/pyproject.toml
  sale_order_requested_delivery/readme/CONTRIBUTORS.md
  sale_order_requested_delivery/readme/DESCRIPTION.md
  sale_order_requested_delivery/static/description/icon.png
  sale_order_requested_delivery/static/description/index.html
  sale_order_requested_delivery/tests/__init__.py
  sale_order_requested_delivery/tests/test_sale_order.py
  sale_order_requested_delivery/tests/test_sale_order_line.py
  sale_order_requested_delivery/views/sale_order.xml
  setup/_metapackage/pyproject.toml
Labels: 18.0

#2328 Syncing from upstream OCA/sale-workflow (17.0)
  README.md
  sale_elaboration/README.rst
  sale_elaboration/__init__.py
  sale_elaboration/__manifest__.py
  sale_elaboration/hooks.py
  sale_elaboration/i18n/de.po
  sale_elaboration/i18n/es.po
  sale_elaboration/i18n/it.po
  sale_elaboration/i18n/sale_elaboration.pot
  sale_elaboration/models/__init__.py
  sale_elaboration/models/product.py
  sale_elaboration/models/product_elaboration.py
  sale_elaboration/models/product_elaboration_mixin.py
  sale_elaboration/models/product_elaboration_profile.py
  sale_elaboration/models/product_template.py
  sale_elaboration/models/res_config_settings.py
  sale_elaboration/models/sale_order.py
  sale_elaboration/models/stock_move.py
  sale_elaboration/models/stock_picking.py
  sale_elaboration/models/stock_rule.py
  sale_elaboration/pyproject.toml
  sale_elaboration/readme/CONFIGURE.md
  sale_elaboration/readme/CONTRIBUTORS.md
  sale_elaboration/readme/DESCRIPTION.md
  sale_elaboration/readme/USAGE.md
  sale_elaboration/reports/report_base.xml
  sale_elaboration/reports/report_deliveryslip.xml
  sale_elaboration/reports/report_picking_operations.xml
  sale_elaboration/security/ir.model.access.csv
  sale_elaboration/security/security.xml
  sale_elaboration/static/description/icon.png
  sale_elaboration/static/description/index.html
  sale_elaboration/tests/__init__.py
  sale_elaboration/tests/test_sale_elaboration.py
  sale_elaboration/views/product_views.xml
  sale_elaboration/views/res_config_settings_views.xml
  sale_elaboration/views/sale_elaboration_profile_views.xml
  sale_elaboration/views/sale_elaboration_report_views.xml
  sale_elaboration/views/sale_elaboration_views.xml
  sale_elaboration/views/sale_order_views.xml
  sale_elaboration/views/stock_move_line_views.xml
  sale_elaboration/views/stock_move_views.xml
  sale_elaboration/views/stock_picking_views.xml
  sale_order_line_menu/i18n/de.po
  sale_order_line_menu/i18n/es.po
  sale_order_line_menu/i18n/fi.po
  sale_order_line_menu/i18n/fr.po
  sale_order_line_menu/i18n/fr_BE.po
  sale_order_line_menu/i18n/fr_FR.po
  sale_order_line_menu/i18n/hr.po
  sale_order_line_menu/i18n/it.po
  sale_order_line_menu/i18n/pt_BR.po
  sale_order_line_menu/i18n/sale_order_line_menu.pot
  setup/_metapackage/pyproject.toml
Labels: 17.0

#2329 Syncing from upstream OCA/sale-workflow (18.0)
  sale_order_note_template/i18n/it.po
Labels: 18.0

#2331 Syncing from upstream OCA/sale-workflow (18.0)
  README.md
  sale_automatic_workflow/tests/common.py
  sale_automatic_workflow/tests/test_automatic_workflow.py
  sale_automatic_workflow_job/README.rst
  sale_automatic_workflow_job/__init__.py
  sale_automatic_workflow_job/__manifest__.py
  sale_automatic_workflow_job/data/queue_job_data.xml
  sale_automatic_workflow_job/i18n/es.po
  sale_automatic_workflow_job/i18n/it.po
  sale_automatic_workflow_job/i18n/sale_automatic_workflow_job.pot
  sale_automatic_workflow_job/models/__init__.py
  sale_automatic_workflow_job/models/automatic_workflow_job.py
  sale_automatic_workflow_job/models/queue_job.py
  sale_automatic_workflow_job/pyproject.toml
  sale_automatic_workflow_job/readme/CONTRIBUTORS.md
  sale_automatic_workflow_job/readme/CREDITS.md
  sale_automatic_workflow_job/readme/DESCRIPTION.md
  sale_automatic_workflow_job/static/description/icon.png
  sale_automatic_workflow_job/static/description/index.html
  sale_automatic_workflow_job/tests/__init__.py
  sale_automatic_workflow_job/tests/test_auto_workflow_job.py
  sale_automatic_workflow_periodicity/tests/test_auto_workflow_periodicity.py
  setup/_metapackage/pyproject.toml
Labels: 18.0

#2332 Syncing from upstream OCA/sale-workflow (8.0)
  sale_rental/i18n/it.po
Labels: 8.0

#2333 Syncing from upstream OCA/sale-workflow (9.0)
  sale_rental/i18n/it.po
Labels: 9.0

#2334 Syncing from upstream OCA/sale-workflow (10.0)
  sale_rental/i18n/it.po
Labels: 10.0

#2335 Syncing from upstream OCA/sale-workflow (12.0)
  sale_invoice_plan/i18n/it.po
  sale_order_line_price_history/i18n/it.po
  sale_rental/i18n/it.po
Labels: 12.0

#2336 Syncing from upstream OCA/sale-workflow (14.0)
  sale_rental/i18n/it.po
Labels: 14.0

#2337 Syncing from upstream OCA/sale-workflow (15.0)
  sale_rental/i18n/it.po
Labels: 15.0

#2338 Syncing from upstream OCA/sale-workflow (18.0)
  sale_order_requested_delivery/i18n/it.po
Labels: 18.0

#2339 Syncing from upstream OCA/sale-workflow (15.0)
  README.md
  sales_team_invoiced_target_domain/README.rst
  sales_team_invoiced_target_domain/__init__.py
  sales_team_invoiced_target_domain/__manifest__.py
  sales_team_invoiced_target_domain/i18n/sales_team_invoiced_target_domain.pot
  sales_team_invoiced_target_domain/model/__init__.py
  sales_team_invoiced_target_domain/model/crm_team.py
  sales_team_invoiced_target_domain/model/res_company.py
  sales_team_invoiced_target_domain/model/res_config_settings.py
  sales_team_invoiced_target_domain/readme/CONTRIBUTORS.rst
  sales_team_invoiced_target_domain/readme/DESCRIPTION.rst
  sales_team_invoiced_target_domain/readme/USAGE.rst
  sales_team_invoiced_target_domain/static/description/icon.png
  sales_team_invoiced_target_domain/static/description/index.html
  sales_team_invoiced_target_domain/tests/__init__.py
  sales_team_invoiced_target_domain/tests/test_crm_team.py
  sales_team_invoiced_target_domain/views/res_config_settings_views.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sales_team_invoiced_target_domain/odoo/addons/sales_team_invoiced_target_domain
  setup/sales_team_invoiced_target_domain/setup.py
Labels: 15.0

#2340 Syncing from upstream OCA/sale-workflow (18.0)
  README.md
  sale_partner_incoterm/README.rst
  sale_partner_incoterm/__init__.py
  sale_partner_incoterm/__manifest__.py
  sale_partner_incoterm/i18n/ca.po
  sale_partner_incoterm/i18n/de.po
  sale_partner_incoterm/i18n/es.po
  sale_partner_incoterm/i18n/fi.po
  sale_partner_incoterm/i18n/fr.po
  sale_partner_incoterm/i18n/it.po
  sale_partner_incoterm/i18n/nl.po
  sale_partner_incoterm/i18n/sale_partner_incoterm.pot
  sale_partner_incoterm/i18n/sl.po
  sale_partner_incoterm/i18n/tr.po
  sale_partner_incoterm/i18n/zh_CN.po
  sale_partner_incoterm/models/__init__.py
  sale_partner_incoterm/models/res_partner.py
  sale_partner_incoterm/models/sale_order.py
  sale_partner_incoterm/pyproject.toml
  sale_partner_incoterm/readme/CONTRIBUTORS.md
  sale_partner_incoterm/readme/DESCRIPTION.md
  sale_partner_incoterm/static/description/icon.png
  sale_partner_incoterm/static/description/index.html
  sale_partner_incoterm/tests/__init__.py
  sale_partner_incoterm/tests/test_sale_partner_incoterm.py
  sale_partner_incoterm/views/res_partner.xml
  sale_partner_incoterm/views/sale_order.xml
  sale_stock_picking_note/README.rst
  sale_stock_picking_note/__init__.py
  sale_stock_picking_note/__manifest__.py
  sale_stock_picking_note/i18n/ca.po
  sale_stock_picking_note/i18n/de.po
  sale_stock_picking_note/i18n/es.po
  sale_stock_picking_note/i18n/fr.po
  sale_stock_picking_note/i18n/it.po
  sale_stock_picking_note/i18n/sale_stock_picking_note.pot
  sale_stock_picking_note/models/__init__.py
  sale_stock_picking_note/models/res_partner.py
  sale_stock_picking_note/models/sale_order.py
  sale_stock_picking_note/models/stock_picking.py
  sale_stock_picking_note/pyproject.toml
  sale_stock_picking_note/readme/CONTRIBUTORS.md
  sale_stock_picking_note/readme/DESCRIPTION.md
  sale_stock_picking_note/readme/USAGE.md
  sale_stock_picking_note/static/description/icon.png
  sale_stock_picking_note/static/description/index.html
  sale_stock_picking_note/tests/__init__.py
  sale_stock_picking_note/tests/test_sale_stock_picking_note.py
  sale_stock_picking_note/views/report_deliveryslip.xml
  sale_stock_picking_note/views/res_partner_view.xml
  sale_stock_picking_note/views/sale_order_view.xml
  sale_stock_picking_note/views/stock_picking_view.xml
  setup/_metapackage/pyproject.toml
Labels: 18.0

#2341 Syncing from upstream OCA/sale-workflow (18.0)
  README.md
  sale_order_price_recalculation/README.rst
  sale_order_price_recalculation/__init__.py
  sale_order_price_recalculation/__manifest__.py
  sale_order_price_recalculation/i18n/ca.po
  sale_order_price_recalculation/i18n/de.po
  sale_order_price_recalculation/i18n/el_GR.po
  sale_order_price_recalculation/i18n/es.po
  sale_order_price_recalculation/i18n/es_ES.po
  sale_order_price_recalculation/i18n/es_VE.po
  sale_order_price_recalculation/i18n/fi.po
  sale_order_price_recalculation/i18n/fr.po
  sale_order_price_recalculation/i18n/hr.po
  sale_order_price_recalculation/i18n/hr_HR.po
  sale_order_price_recalculation/i18n/hu.po
  sale_order_price_recalculation/i18n/it.po
  sale_order_price_recalculation/i18n/nl.po
  sale_order_price_recalculation/i18n/nl_NL.po
  sale_order_price_recalculation/i18n/pt.po
  sale_order_price_recalculation/i18n/pt_BR.po
  sale_order_price_recalculation/i18n/ro.po
  sale_order_price_recalculation/i18n/sale_order_price_recalculation.pot
  sale_order_price_recalculation/i18n/sl.po
  sale_order_price_recalculation/i18n/tr.po
  sale_order_price_recalculation/i18n/tr_TR.po
  sale_order_price_recalculation/i18n/vi_VN.po
  sale_order_price_recalculation/i18n/zh_CN.po
  sale_order_price_recalculation/models/__init__.py
  sale_order_price_recalculation/models/sale_order.py
  sale_order_price_recalculation/pyproject.toml
  sale_order_price_recalculation/readme/CONTRIBUTORS.md
  sale_order_price_recalculation/readme/DESCRIPTION.md
  sale_order_price_recalculation/readme/INSTALL.md
  sale_order_price_recalculation/readme/ROADMAP.md
  sale_order_price_recalculation/readme/USAGE.md
  sale_order_price_recalculation/static/description/icon.png
  sale_order_price_recalculation/static/description/index.html
  sale_order_price_recalculation/static/description/sale_order_price_recalculation.drawio.png
  sale_order_price_recalculation/tests/__init__.py
  sale_order_price_recalculation/tests/test_sale_order_price_recalculation.py
  sale_order_price_recalculation/views/sale_order_view.xml
  sale_order_requested_delivery/i18n/it.po
  setup/_metapackage/pyproject.toml
Labels: 18.0

#2342 Syncing from upstream OCA/sale-workflow (18.0)
  README.md
  product_set_sell_only_by_packaging/README.rst
  product_set_sell_only_by_packaging/__init__.py
  product_set_sell_only_by_packaging/__manifest__.py
  product_set_sell_only_by_packaging/data/ir_cron.xml
  product_set_sell_only_by_packaging/i18n/es.po
  product_set_sell_only_by_packaging/i18n/it.po
  product_set_sell_only_by_packaging/i18n/product_set_sell_only_by_packaging.pot
  product_set_sell_only_by_packaging/models/__init__.py
  product_set_sell_only_by_packaging/models/product_product.py
  product_set_sell_only_by_packaging/models/product_set_line.py
  product_set_sell_only_by_packaging/models/product_template.py
  product_set_sell_only_by_packaging/pyproject.toml
  product_set_sell_only_by_packaging/readme/CONTRIBUTORS.md
  product_set_sell_only_by_packaging/readme/CREDITS.md
  product_set_sell_only_by_packaging/readme/DESCRIPTION.md
  product_set_sell_only_by_packaging/static/description/icon.png
  product_set_sell_only_by_packaging/static/description/index.html
  product_set_sell_only_by_packaging/tests/__init__.py
  product_set_sell_only_by_packaging/tests/test_product_set_packaging.py
  product_set_sell_only_by_packaging/views/product_set_line.xml
  product_set_sell_only_by_packaging/views/product_template.xml
  sale_order_lot_selection/i18n/nl_NL.po
  setup/_metapackage/pyproject.toml
Labels: 18.0

#2343 Syncing from upstream OCA/sale-workflow (16.0)
  sale_order_product_assortment/i18n/nl.po
Labels: 16.0

#2344 Syncing from upstream OCA/sale-workflow (18.0)
  sale_stock_line_customer_ref/i18n/nl.po
Labels: 18.0

#2345 Syncing from upstream OCA/sale-workflow (12.0)
  sale_blanket_order/i18n/it.po
Labels: 12.0

#2346 Syncing from upstream OCA/sale-workflow (14.0)
  product_supplierinfo_for_customer_sale_blanket_order/i18n/it.po
  sale_blanket_order/i18n/it.po
  sale_blanket_order_revision/i18n/it.po
  sale_quick_blanket_order/i18n/it.po
Labels: 14.0

#2347 Syncing from upstream OCA/sale-workflow (16.0)
  sale_blanket_order/i18n/it.po
Labels: 16.0

#2348 Syncing from upstream OCA/sale-workflow (17.0)
  sale_blanket_order/i18n/it.po
  sale_elaboration/i18n/nl.po
  sale_elaboration/i18n/nl_NL.po
  sale_fixed_discount/i18n/fr.po
Labels: 17.0

#2349 Syncing from upstream OCA/sale-workflow (18.0)
  README.md
  product_customerinfo_sale/README.rst
  product_customerinfo_sale/__init__.py
  product_customerinfo_sale/__manifest__.py
  product_customerinfo_sale/i18n/ca.po
  product_customerinfo_sale/i18n/de.po
  product_customerinfo_sale/i18n/es.po
  product_customerinfo_sale/i18n/it.po
  product_customerinfo_sale/i18n/product_customerinfo_sale.pot
  product_customerinfo_sale/i18n/product_supplierinfo_for_customer_sale.pot
  product_customerinfo_sale/i18n/pt.po
  product_customerinfo_sale/models/__init__.py
  product_customerinfo_sale/models/sale_order_line.py
  product_customerinfo_sale/pyproject.toml
  product_customerinfo_sale/readme/CONTRIBUTORS.md
  product_customerinfo_sale/readme/DESCRIPTION.md
  product_customerinfo_sale/readme/ROADMAP.md
  product_customerinfo_sale/readme/USAGE.md
  product_customerinfo_sale/security/ir.model.access.csv
  product_customerinfo_sale/static/description/configuration_customer.png
  product_customerinfo_sale/static/description/description_code.png
  product_customerinfo_sale/static/description/description_code_2.png
  product_customerinfo_sale/static/description/icon.png
  product_customerinfo_sale/static/description/index.html
  product_customerinfo_sale/static/description/search_code.png
  product_customerinfo_sale/static/description/search_code_2.png
  product_customerinfo_sale/tests/__init__.py
  product_customerinfo_sale/tests/test_product_customerinfo_sale.py
  product_customerinfo_sale/views/product_customerinfo_views.xml
  product_customerinfo_sale/views/sale_view.xml
  product_set_sell_only_by_packaging/i18n/it.po
  setup/_metapackage/pyproject.toml
Labels: 18.0

#2352 Syncing from upstream OCA/sale-workflow (16.0)
  sale_order_line_price_history/i18n/tr.po
Labels: 16.0

#2353 Syncing from upstream OCA/sale-workflow (18.0)
  README.md
  pricelist_cache/i18n/it.po
  product_form_sale_link/README.rst
  product_form_sale_link/__init__.py
  product_form_sale_link/__manifest__.py
  product_form_sale_link/i18n/ca.po
  product_form_sale_link/i18n/es.po
  product_form_sale_link/i18n/fr.po
  product_form_sale_link/i18n/it.po
  product_form_sale_link/i18n/product_form_sale_link.pot
  product_form_sale_link/models/__init__.py
  product_form_sale_link/models/product_product.py
  product_form_sale_link/models/product_template.py
  product_form_sale_link/pyproject.toml
  product_form_sale_link/readme/CONTRIBUTORS.md
  product_form_sale_link/readme/DESCRIPTION.md
  product_form_sale_link/readme/USAGE.md
  product_form_sale_link/static/description/icon.png
  product_form_sale_link/static/description/index.html
  product_form_sale_link/static/description/product_sale.png
  product_form_sale_link/tests/__init__.py
  product_form_sale_link/tests/test_product.py
  product_form_sale_link/views/product_product.xml
  product_form_sale_link/views/product_template.xml
  product_form_sale_link/views/sale_order_line.xml
  setup/_metapackage/pyproject.toml
Labels: 18.0

#2355 Syncing from upstream OCA/sale-workflow (16.0)
  sale_elaboration/i18n/nl.po
Labels: 16.0

#2356 Syncing from upstream OCA/sale-workflow (17.0)
  sale_order_carrier_auto_assign/i18n/it.po
  sale_promotion_rule/i18n/it.po
Labels: 17.0

#2357 Syncing from upstream OCA/sale-workflow (15.0)
  README.md
  sales_team_invoiced_target_domain/README.rst
  sales_team_invoiced_target_domain/__manifest__.py
  sales_team_invoiced_target_domain/i18n/sales_team_invoiced_target_domain.pot
  sales_team_invoiced_target_domain/migrations/15.0.1.0.1/pre-migration.py
  sales_team_invoiced_target_domain/model/crm_team.py
  sales_team_invoiced_target_domain/model/res_company.py
  sales_team_invoiced_target_domain/model/res_config_settings.py
  sales_team_invoiced_target_domain/readme/USAGE.rst
  sales_team_invoiced_target_domain/static/description/index.html
  sales_team_invoiced_target_domain/tests/test_crm_team.py
  sales_team_invoiced_target_domain/views/res_config_settings_views.xml
Labels: 15.0

#2358 Syncing from upstream OCA/sale-workflow (17.0)
  sale_promotion_rule/i18n/it.po
Labels: 17.0

#2360 Creating project branch
  partner_sale_pivot/README.rst
  partner_sale_pivot/__init__.py
  partner_sale_pivot/__manifest__.py
  partner_sale_pivot/i18n/ca.po
  partner_sale_pivot/i18n/ca_ES.po
  partner_sale_pivot/i18n/de.po
  partner_sale_pivot/i18n/es.po
  partner_sale_pivot/i18n/hr.po
  partner_sale_pivot/i18n/it.po
  partner_sale_pivot/i18n/partner_sale_pivot.pot
  partner_sale_pivot/pyproject.toml
  partner_sale_pivot/readme/CONTRIBUTORS.md
  partner_sale_pivot/readme/DESCRIPTION.md
  partner_sale_pivot/readme/USAGE.md
  partner_sale_pivot/static/description/icon.png
  partner_sale_pivot/static/description/index.html
  partner_sale_pivot/views/res_partner_views.xml
  partner_sale_pivot/views/sale_report_views.xml
Labels: 18.0.project_pe_692

#2361 Syncing from upstream OCA/sale-workflow (16.0)
  .copier-answers.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  README.md
  sale_triple_discount/README.rst
  sale_triple_discount/__manifest__.py
  sale_triple_discount/static/description/index.html
  setup/sale_triple_discount/setup.py
Labels: 16.0
